### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by xk0der** [postmanlabs/postman-app-support#11595]
### Describe your current workflow

Please ignore

### Describe your ideal workflow

N/A

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by postman-support** [comment]
Test
via @xk0der | Postman Support

**Comment by postman-support** [comment]
Test 2
via @xk0der | Postman Support

**Comment by xk0der** [comment]
Check GitHub -> ZD Sync

**Comment by postman-support** [comment]
ZD -> GH sync

**Comment by xk0der** [comment]
Check GitHub -> ZD Sync

**Comment by xk0der** [comment]
Check GitHub -> ZD Sync

**Comment by postman-support** [comment]
Worked!

**Comment by xk0der** [comment]
**Comments on GitHub Issue!**

Yes!

**Comment by postman-support** [comment]
Alright!

via @xk0der | Postman Support

**Comment by xk0der** [comment]
All automations 🟢  - Closing this next!
