### ISSUE TITLE
Ability to view the full raw HTTP transaction.

### ISSUE THREAD

**Issue by rrice** [postmanlabs/postman-app-support#119]
I would like to have a raw view of the request and response with the option having the complete HTTP transaction available. It does not have to be the "on the wire view", just something complete and accurate enough that I could copy-and-paste into documentation.

Suggestion: maybe a new "full HTTP transaction" tab.

**Example:**  full raw request

``` javascript
POST /path/to/my/resource HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
   "name": "rrice",
   "site": "https://github.com/rrice"
}
```

**Example:** full raw response

``` javascript
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 80
Server: Jetty(6.1.26)
Location: http://localhost:8080/path/to/my/resource/2938

{
    "id": 2938,
    "name":  "rrice",
    "site": "https://github.com/rrice"
}
```

**Comment by adenysenko** [comment]
+1

**Comment by anton-arsentyev** [comment]
@a85 can you point me how to view raw request ?
all issues closed, but still i cant find the way to see it

**Comment by a85** [comment]
Go to View > Console and you should see the full HTTP request logged.

**Comment by lukeholder** [comment]
This is still not solved. The console is not the raw text of the whole response.

I need the full exact response to copy and paste easily into a external test suite.

**Comment by ysmintor** [comment]
@a85 Thanks, I look around for a while, finally you help me out this problem. Now the desktop version should View -> Show postman console,

**Comment by TheRealMilagro** [comment]
but unfortunately the console does not have possibility to switch display mode to raw :(
It is using kind of a pretty view, but sometimes a raw-view is desired.

**Comment by lukeholder** [comment]
@TheRealMilagro is right, it still is not the full raw http request that is able to be copied and pasted.

Looks like I will be switching to https://paw.cloud/

**Comment by sdnts** [comment]
We're working on an actual raw view in the Console, and a build is supposed to hit our Canary channels tonight. I'll let you guys know here when it is out.

**Comment by lukeholder** [comment]
thanks @madebysid will take a look.

**Comment by a85** [comment]
Raw dumps are part of the console now: https://www.dropbox.com/s/6wggehds1qcp6k8/Screenshot%202017-10-11%2014.34.22.png?dl=0. So glad to finally close this issue. :)

**Comment by Pacerier** [comment]
@a85 , How to send **full** raw requests? (not just for post-body)

(Also c https://marketplace.visualstudio.com/items?itemName=humao.rest-client .)
