### ISSUE TITLE
Response size

### ISSUE THREAD

**Issue by mjjohnson** [postmanlabs/postman-app-support#156]
I find Postman extremely useful, and I was thinking it would be even handier if there were an indicator of the size of the response. (Especially since APIs are often used for mobile, where every kB matters.) I'd be happy to dig in and try to code up this feature, if you think it would be a worthwhile addition, but I wanted to check here first before coding. Does this sound like a good addition?

If so, I was thinking it would work great just to the right of the status and time indicators in the response bar. Just a simple `SIZE 3.34 kB`, matching the existing styling. Thoughts?

**Comment by penguinawesome** [comment]
Any updates??

**Comment by koenkarsten** [comment]
+1

**Comment by tofra** [comment]
+1

**Comment by mrberggg** [comment]
+1

**Comment by konfilios** [comment]
+1

**Comment by a85** [comment]
@shamasis @czardoz Possible to get this in any way?

**Comment by mjoyce91** [comment]
+1

**Comment by czardoz** [comment]
@a85 possible, but very unreliable

**Comment by shamasis** [comment]
The actual memory consumption depends on the HTTP client's implementation. Nevertheless, showing the size of the body (as long as it is text and not binary) is semi-accurate and fast enough. It would hit performance for very large responses though. Also, the size of response header influences the total size. Thus, the computed size would be "indicative" only.

**Comment by a85** [comment]
This is good enough IMHO

**Comment by togonow** [comment]
+1

**Comment by martinjbaker** [comment]
+1

**Comment by nass600** [comment]
+1

**Comment by eXeDK** [comment]
+1

**Comment by ankitsharma301093** [comment]
+1

**Comment by gablorquet** [comment]
+1

**Comment by jaydp17** [comment]
+1

**Comment by antong314** [comment]
+1

**Comment by Mathiou04** [comment]
+1

**Comment by gukoff** [comment]
+1

**Comment by mderazon** [comment]
How does Chrome inspector calculate that ?

http://stackoverflow.com/questions/8072921/chrome-dev-tools-size-vs-content

**Comment by numaanashraf** [comment]
@mderazon Chrome Inspector has access to the lower level network information via the Chrome Debugging Protocol. Postman Chrome App doesn't have access to this information.

http://chromedevtools.github.io/debugger-protocol-viewer-1.1/Network/#event-dataReceived

**Comment by gukoff** [comment]
Can't the application ask for permission to access this information? Or show the dev tools window itself?

**Comment by yogamaha** [comment]
+1 

Recently we had an issue due to Service not compressing the response. 
I was looking for a way to see the response size with Compression enabled/disabled. 
Having this feature to see the size would have helped me.

I see there is feature in Advanced REST client - to show the Timing information (Wait Time, Receive Time) available in Chrome Developer Tools.  If this can be embedded into Postman, it would be very handy indeed as I prefer using Postman.

**Comment by tjwebb** [comment]
+1

**Comment by gitis** [comment]
+1

**Comment by martinjbaker** [comment]
This doesn't have to be byte accurate... To the nearest KB would be better than nothing. It can just say "approximately" in the UI.

**Comment by guillaumegarcia13** [comment]
+1

**Comment by andreybeta** [comment]
+1

**Comment by foragerr** [comment]
👍

**Comment by shamasis** [comment]
Hello everyone! I've some good news on this issue. Since we upgraded the internals of our requesting engine, we are now in a position to safely implement this feature and others like it.

Read more about postman runtime: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

Get your copy of Postman Canary and give it a spin. The response size would come to it sometime this week. 😊 And will soon follow into the production apps.

**Comment by a85** [comment]
This is available in Postman native apps now. Will be available in the Chrome app soon. Feels so good to finally close this!

**Comment by rylanb** [comment]
In Postman 5.2.0 for Mac I am not seeing a size set anywhere, just the time and status. :(

**Comment by cendrizzi** [comment]
As Rylanb said, I've been looking for this too. I see it in the docs, then saw this issue after doing a search, but can't find it anywhere in the client.

I am also using the mac version and this feature would be really useful.

Maybe a new issue needs to be created...

**Comment by ipaskhover** [comment]
Version 5.5.0 on Mac includes the feature and it looks like this:
![screenshot 2018-01-09 09 37 27](https://user-images.githubusercontent.com/34438704/34709688-d8714594-f520-11e7-84ee-bc8291e3d154.png)

**Comment by veneMarcos** [comment]
I had this feature just in my 6.0.9 version on mac, after I using a 5.5.0 version this feature doesn`t work.
