### ISSUE TITLE
Link to relative URLs

### ISSUE THREAD

**Issue by jjmartin** [postmanlabs/postman-app-support#171]
I am consuming a REST API that uses relative URLs. (Team City)

the looks something like this:
"href": "/httpAuth/app/rest/builds/id:50"

where 
http://myserver.com//httpAuth/app/rest/builds/id:50

would be a valid REST request.

would be nice if these were linkable - perhaps only if "href" or other common link names were used in as a property name.

**Comment by vkaegis** [comment]
@jjmartin @noise @mikenerone Hey guys, this is fixed and working in production. Looks like we missed closing this request and informing you all. Let me know if relative URLs are working as expected.

**Comment by vkaegis** [comment]
Just a clarification, Postman allows you to open relative URLs in the response in a new tab where we automatically append the base URL to it. We also now have variables with which you can reuse these values.

**Comment by claudiavasquezipsum** [comment]
Hola Alguno me puede decir como funciona lo de las rutas relativas no he podido hacer funcionar en mi postman... gracias
