### ISSUE TITLE
Feature Request: Provide direct external links to saved requests within a collection

### ISSUE THREAD

**Issue by snarglefarg** [postmanlabs/postman-app-support#196]
I would find it quite useful if it were possible to provide a link within an external program which when clicked, opens a saved request within Postman. For instance:

postman://[url to collectionId/id]

would open the specific request. This would be quite useful if you use other programs to write test cases and want to provide a link to run the request.

Currently the URL bar while using Postman is empty. Filling it with the URL to the query would make it easy to share the URL with others.

Of course this would be highly dependent on other's having the same collections on their PC.  Perhaps a timestamp would need to be stored with each request so that you can guarantee that one person is running the exact same request as another after clicking a link.

**Comment by henry-wasserman-wellogic** [comment]
I was also looking for this feature

**Comment by anudeepmedicharla** [comment]
Hi @snarglefarg,
Deep linking in the Postman app is on our roadmap. Cannot give you an ETA yet. Stay tuned for updates in the future. :)

**Comment by snarglefarg** [comment]
Staying tuned!

**Comment by a85** [comment]
Just wanted to point out that Postman now has in browser views for collections that can help reference a request/collection from other places. We are working on tying together these web views with the app so the app can be opened in a particular state either from the Postman web views or directly from any other place.

**Comment by michaelsonnleitner** [comment]
any date you can announce for deep links from/to web and postman app?

**Comment by arlemi** [comment]
@michaelsonnleitner We're hoping to get this solved this year when Postman will be available on browser.

**Comment by ruedigerm-playster** [comment]
Issue is closed, but I think its still not available. Would be a nice and useful feature.

**Comment by arlemi** [comment]
@ruedigerm-playster If you're using [Postman in your browser](https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/) you can now share the URLs directly with your teammates and it'll open the same request, they need to be part of the same workspace to access it though.
