### ISSUE TITLE
output API doc

### ISSUE THREAD

**Issue by masterkrang** [postmanlabs/postman-app-support#204]
I was just thinking a great feature to have would to be able to output a one click beautifully formatted api doc in markdown (or whatever format you want). Have a feature like this? Seems like all of the elements are there, like, since you can build your routes, describe what they do in descriptions. You could even place them into different collections. (would be cool to nest selections, like sitename -> projects, sitename -> users). 

In my workflow, I'm creating API docs from scratch, and testing them out in postman. But since I'm already testing them out in postman, it would be great just to click "Generate API" (or whatever) and to keep my API doc in sync.

**Comment by tomhall** [comment]
This would be awesome!

**Comment by cphoover** [comment]
bump bump +1 :thumbsup:

I also think this would be a nice feature

**Comment by johnrees** [comment]
:+1: especially with something like [swagger-ui](http://petstore.swagger.wordnik.com/) integration, so that end-users can test the api directly from the documentation

**Comment by abhijitkane** [comment]
We're working on a feature on these lines, and should have an update soon.

**Comment by johnrees** [comment]
Great news. I'll just throw in [Slate](https://github.com/tripit/slate) as another suggestion. Really nice docs generated from a single markdown file.

**Comment by JakeWorrell** [comment]
I threw something together to do this using PHP: https://github.com/JakeWorrell/docodile

it's very rough and ready, but it works reasonably well. What would really help is if we could add more metadata such as descriptions to fields etc.

**Comment by davidwallen** [comment]
Swagger....

Support parsing swagger YAML to create/update test collections and QED.

**Comment by khansei** [comment]
Is it still coming ?

**Comment by neowulf** [comment]
+1

**Comment by dev-mraj** [comment]
+++1

**Comment by davidevernizzi** [comment]
I also wanted such a feature. I didn't find docodile, so I also hacked together something. My solution is a single page app written in javascript and based on react.

I did a github repo https://github.com/davidevernizzi/docman and you can try it at http://www.vernizzis.it/docman/

The project is very simple and only has basic features (those I needed), but comments and requests are very welcome.

**Comment by a85** [comment]
Just as a heads-up. Postman's latest version has an in-built documentation browser. Screenshot here: https://www.dropbox.com/s/pqc69lq0t3y0f5s/collection-browser.png?dl=0. External documentation will be available soon. We are also exploring the ability to export API Blueprint, RAML and Swagger definitions.

**Comment by aliuygur** [comment]
+1

**Comment by felipeplets** [comment]
Any news on this topic? 
Support to API Blueprint is welcome.

**Comment by davidevernizzi** [comment]
Are you talking about Postman's builtin or about my docman project? I'm not sure about the former, but the latter has now the ability to download the documentation and a [new landing page](http://docman.launchrock.com) :-)

I develop it in my spare time and according to my needs, but feel free to fork or ask for features if interested

**Comment by felipeplets** [comment]
@davidevernizzi I was talking about Postman builtin feature. 
I just looked on the docman and seems to be exactly what I need, thanks for that!

**Comment by a85** [comment]
This is available as part of Postman Cloud: http://blog.getpostman.com/2015/12/10/introducing-postman-cloud/. Cloud hosts, updates and maintains documentation for everyone. I'd suggest http://docman.launchrock.com/ and https://github.com/JakeWorrell/docodile for generating one-time documentation from Collections.

**Comment by aubm** [comment]
Hello :) In addition to the tools that you mentionned, you might be interested by this one I'm currently working on: https://github.com/aubm/postmanerator.

Don't hesitate to have a look if you will, and feel free to submit issues if you have questions or you have ideas that could make it better :)

**Comment by orarbel** [comment]
Started a flask based project to convert postman collection to slate: https://github.com/YoApp/postman2slate 
https://postman2slate.herokuapp.com

**Comment by jungor** [comment]
+13800138000

**Comment by bansalvks** [comment]
trillions of upvote for the feature

**Comment by sdnts** [comment]
Guys, starting with Postman 5.0, this is possible for all users when they sign in :)

**Comment by bansalvks** [comment]
@madebysid can you provide steps to create a api documentation from postman

**Comment by a85** [comment]
@bansalvks Please check the docs at getpostman.com/docs

**Comment by psi-4ward** [comment]
Pls give an option to download the docs
