### ISSUE TITLE
Allow collections to be associated with "favorite" environments

### ISSUE THREAD

**Issue by snarglefarg** [postmanlabs/postman-app-support#213]
Although I have about 20 environments configured, not each of these environments is useful for any given collection. Perhaps 3-4 environments are part of the same project. It would be useful if an Environment dropdown were available to each collection. The entire list of collections would be visible and the user would place a checkmark next to those environments that are used by the collection. In effect, these would be "favorite" enviroments.

Once configured, the user would then select a request within a collection. When the environment dropdown is selected, the "favorite" enviroments are sorted to the top, a line separator would then show the rest of the non-favorite enviroments. Finally, another line and the "manage enviroments" selection.

Doing this would make it easy for the user to switch between environments without having to search a long list. All environments would still be available, but they're sorted in a more useful, logical way.

**Comment by kevinjalbert** [comment]
+1

**Comment by jackchen83** [comment]
+1. This is a feature that I am looking for

**Comment by curtisgibby** [comment]
+1

**Comment by miguelbalboa** [comment]
+1

**Comment by jainprash** [comment]
+1

**Comment by halilim** [comment]
+1 for "project" support. Currently I can use the environment of a project in another project and that doesn't make sense. Instead, I'd like to group collections, environments and presets etc. as projects in which;
- The said environments and presets would only be available in that project,
- When a request which belongs to a project is opened, the top environment for that project would be automatically selected.

Though for collections, I'd like to set a collection as a project instead. Because most of the times a project would have a single collection, two levels with the same name (project name and collection name) would be redundant.

**Comment by zdegner1** [comment]
+1 We have a collection per micro-service and managing all of the environments is a bit of a problem. If a collection could be associated with zero or more environments that would be perfect.

An example would be, a remote team publishes the "ABC Service" collection which is associated with the "ABC Service - Integration" and "ABC Service - Release Candidate" environments. Other teams can easily subscribe to that collection and any associated environments.

**Comment by mjonas87** [comment]
+1

**Comment by Ciki** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by sarathkumarbaskaran** [comment]
+1

**Comment by a85** [comment]
Will be solved by Workspaces: #3205. Closing this issue but will reference it in future updates.

**Comment by snarglefarg** [comment]
Good things come to those that wait. Thanks for implementing this! Much appreciated.

**Comment by AlbertoP64** [comment]
_(will have added +1 here, but now the things have moved...)_

@snarglefarg 
Sorry but no, seems still not already implemented (and mind that your request dates from 2013...)

Now this issue has been merged into **<kbd>Workspaces: #3205 Issue</kbd>**....
It is also **second place** in **Planned list (not yet worked nor considered!!)** into the NEW awesome Postman Roadmap (see below) with **ONLY 6 votes** _(while the sum of comments on GitHub for this and the other merged issues amounts to 20+)_ 😞 

@ALL:
Seems that **we all commenters here** _(are any of the 16 other posters still subscribed to this thread? Or I need to spam them all..._ 😝 _)_ :

* are now somewhat required to **subscribe to <kbd>[Trello site](https://trello.com/)</kbd>** (where Postman's roadmap has moved on)

* **open up Postman's Trello dashboard here**:
<kbd>[Trello Postman's roadmap dashboard](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers)</kbd>

* **Find our request** "Workspaces in Postman" (nr. 14) in "Planned" rightmost column -second issue at this moment - **direct link**:
<kbd>["Workspaces in Postman" (#14)](https://trello.com/c/g8eFmCr0/14-workspaces-in-postman)</kbd>

* and **vote it up**

...or it seems that maybe the issue will stay forever in planned state 😞 

* Also, please do **<kbd>subscribe to the new #3205</kbd>** issue to stay updated

_to @a85 @madebysid, no flames but, to explicitly advertise also here about the Trello moving affair would have been a great idea IMHO_ 😉

**Comment by Slemgrim** [comment]
+1
