### ISSUE TITLE
oauth_verifier and oauth_callback needed in the form for oauth calls

### ISSUE THREAD

**Issue by sonarxavier** [postmanlabs/postman-app-support#283]
The oauth form is missing 2 fields:
the callback and the verifier (oauth_callback and oauth_verifier)

I know I can set them manually in the Authorization header but it get overridden everytime I refresh the oauth request.

Cheers :)

**Comment by willaerk** [comment]
Is there any chance of this being added? I would like to use Postman to document 
the OAuth 1.0a flow we use in our applications, but I'm stuck because I cannot
add the oauth_verifier to the request for obtaining the access_token.

Regards.

**Comment by arunstan** [comment]
Yes this will be much appreciated. Include the oauth_verifier field in the form and include it for signature construction.

**Comment by saulopaiva** [comment]
Hi,

Adding to the discussion, in the new WordPress API to get the access token via OAuth1, the step of "[Token Exchange](http://oauth1.wp-api.org/docs/basics/Auth-Flow.html#token-exchange)" is necessary, in which the sending of "oauth_verifier" is obrigatory.

Because this API is becoming standard and being integrated into the Core of WordPress, this type of test by Postman will turn out to be more common.

Thank you,

**Comment by HardikThakkar** [comment]
@a85, any updates on this?

**Comment by redmamoth** [comment]
Is this being added soon? I'm trying to test an OAuth service and can't even get past the first step as the oauth_callback is required.  It needs to be included and signed in the Authorization part of the header and I can't figure out any way to get it in there.

**Comment by joaquin-becerra** [comment]
In Magento you need this two parameters to get the tokens to use the rest API.

Is very important!

I can insert the oauth_callback in the Oauth header an it work, but when I do the same with the oauth_verifier the sign seems to be broken

**Comment by mihailmeleca** [comment]
on May 21, 2013 "The oauth form is missing 2 fields". 4 years passed, still not fixed :(

**Comment by a85** [comment]
@harryi3t I believe this is fixed now?

**Comment by harryi3t** [comment]
@a85 I am afraid it's not.
Creating an internal ticket for this.

**Comment by HolisticDeveloper** [comment]
Interested in a resolution for this as well.

**Comment by skhg** [comment]
+1

**Comment by Remi-Tuy** [comment]
+1 been 5 years ?!

**Comment by andig** [comment]
+1 - 5 years and still not available. Prevents me from postman with the discovergy API. Now I need to roll my own client just for testing purposes :(

**Comment by jon-whit** [comment]
+1 Not having this support is a big deterrent from using Postman.

**Comment by brazenest-zz** [comment]
@harryi3t Are we going to see this feature implemented?? I'm really wondering why Postman lacks these fields 5+ yrs after OP's report, especially now that 1) WordPress is a HUGE use case for the `oauth_verifier` field, and 2) Postman is a HUGE app for developers many of whom are interacting with the WP REST API...

Please provide the community with a status update. Thanks! 😺

**Comment by bradparks** [comment]
Insomnia supports callback, and is an opensource cross platform REST client:

https://github.com/getinsomnia/insomnia

**Comment by IGx89** [comment]
Was very excited to use Postman to ease testing of OAuth 1.0a APIs and just ran into this myself. Since it's a tiny change but has been open for 6 years I can only assume Postman has no plans to do this. Guess I'll have to find a different testing client!

**Comment by Raghav-Kathuria** [comment]
Postman listens to only SSL requests, not user's requests.

**Comment by ZephSibley** [comment]
Adding my support for this feature.
Pushed for Postman to be used for the fairly extensive automated API testing I need to set up for work, but this roadblock is practically fatal.

**Comment by Flole998** [comment]
@vkaegis You are assigned to this one. Any chance to get this fixed after more than 6 years?

**Comment by nolazybits** [comment]
@Flole998 I myself moved from Postman to Insomnia a long time ago
https://insomnia.rest/

**Comment by johnny-solargard** [comment]
FWIW, I ran into this same issue and found if you add oauth_verifier as a query string it worked.  I haven't tried oauth_callback, but I presume it would work as well.  I'm using Postman 7.17.0

**I found inspiration here:**  https://wordpress.stackexchange.com/questions/213006/how-to-use-oauth-authentication-with-rest-api-via-curl-commands/239873#239873

Hope this helps someone!

**Comment by vdespa** [comment]
I have tested a full OAuth 1.0 workflow with Postman. While it does not work as well as OAuth 2.0 it is still usable. 

I have created here a tutorial, in case anyone is struggling to get this to work: 
https://www.youtube.com/watch?v=3gXPjj5iEAA

**Comment by mohitranka** [comment]
This has been released in the lastest Postman app V7.27. Please upgrade and give it a go!

**Comment by HolisticDeveloper** [comment]
I'm now able to get my OAuth1.0a flow working in Postman. Thanks!
