### ISSUE TITLE
Live Share Collections

### ISSUE THREAD

**Issue by jpumph** [postmanlabs/postman-app-support#315]
I have a team working on api calls with postman. As any of us makes a change to the Collection we work from we, 1)upload it and then 2)email everyone to 3)delete their collection, then 4)download the latest collection. Feature request to be able to Live Share Collections. Maybe instead of sending a file or uploading to a url there could be a third option to point to a google doc and pull from it at each launch?

**Comment by jscadden** [comment]
@a85 last update was on Dec 23, 2014.  What is the latest on this feature?

**Comment by a85** [comment]
Available in public beta now! Sign up here: http://www.getpostman.com/beta.
