### ISSUE TITLE
On redirect there is no way to see the URL you were redirected to

### ISSUE THREAD

**Issue by collinpeters** [postmanlabs/postman-app-support#319]
I am writing an OAuth2 app and am testing the implicit grant type which involves a redirect. Everything works great, but I cannot see the URL that I was redirected to. In the case of the implicit grant type, the URL contains query parameters that are needed

Please advise if I am mistaken

**Comment by marktyers** [comment]
+1

**Comment by AlexZeitler** [comment]
+1

**Comment by rcrisp** [comment]
+1

**Comment by abhijitkane** [comment]
This is now possible with version 0.2.9 of the Interceptor and version 1.0.11 of the Postman Packaged app.

Interceptor - https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en

You need to enable the Interceptor in Postman, go to the Settings modal and disable automatic redirection.
@rcrisp @AlexZeitler can you confirm if this works for you?

**Comment by AlexZeitler** [comment]
@abhijitkane Tried it using interceptor and it works :+1:

**Comment by csokol** [comment]
+1 is it possible to add the solution from Interceptor extension to postman core?

**Comment by jhorbulyk** [comment]
+1 for @csokol

**Comment by abhijitkane** [comment]
No. The interceptor is a Postman extension, and has access to APIs that the main Postman app does not.

**Comment by jhorbulyk** [comment]
I understand what was meant above.  Here are the steps I followed to get this working:
1. Install the newest version of postman: https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?utm_source=chrome-ntp-launcher
2. Install the Interceptor add-on:https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo
3. In the new postman under settings set "Automatically follow redirects" to no.

**Comment by csokol** [comment]
@abhijitkane maybe this issue should be closed them, since it's simply impossible to solve it.

**Comment by gmta** [comment]
For everyone who gets here from Google; instructions from @jhorbulyk are no longer complete as of 2016-12-01. You also need to explicitly enable Postman Interceptor in the top of the Postman app. This is a toggle to the left of the "Sync" button.
