### ISSUE TITLE
Selecting "JSON (application/json)" does not set Content-Type header.

### ISSUE THREAD

**Issue by lukebakken** [postmanlabs/postman-app-support#327]
@a85 - I'm using the dev branch currently.

When I select "JSON (application/json)" the `Content-Type` header is still `application/xml`.

See these related issues:

#298 
#241
#235
#296 

How can I help debug? I have the repo cloned to `C:\proj\src\POSTMan-Chrome-Extension` with the `dev` branch checked out. I have this directory as the extension installation point in Chrome (see screenshot).

I will also try out the `dev-v2` branch.

![postman-screenshot](https://f.cloud.github.com/assets/514926/812628/1e34a4e2-eef3-11e2-9e9e-bdcc21995e81.png)

**Comment by reekoheek** [comment]
I have the same problem here, I use Postman downloaded from Chrome WebStore.

The server didn't recognize that postman send the Content-Type header.

**Comment by ZebGirouard** [comment]
Just installed Postman from Chrome web store last week.  This seems to be happening for me as well.  I see this when I examine curl request:

curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: e27e5c15-fdb6-4bbd-ad70-525fa9d6afda" -d '{
"name": "Piccapizza",
"sauce": "bad sauce",
"cheese": true,
"mushrooms": true
}' "http://localhost:9292/pizzas"

...but very much have (key) Content-Type and (value) application/json set in the Headers section.  My body is raw JSON.  This used to work for me, but I started getting empty requests in the console server-side, and found this thread.  

I've gone back to command-line curl for now.  It's a shame, the Postman GUI was making things so easy, but I can't test without the ability to add a JSON header.  No idea how I got into this state.  May try uninstalling/reinstalling.

**Comment by ZebGirouard** [comment]
Uninstalled and reinstalled, still see the same "problem" (header doesn't show up) for all my POST requests. But this issue is a real stumper.  I am an instructor, and this issue (empty object) seems to be unique to one app from one of my students, but they can make it work from their computer (and their Postman extension) just fine.  Also command-line curl works from my machine, so I'm 99% sure it's not an issue with their code.  Wish I could be more helpful, but I'm really confused.

**Comment by a85** [comment]
@ZebGirouard Not sure why you are facing this. Can you show me a screenshot of Postman?

**Comment by stillatmylinux** [comment]
Instead of using "Content-Type:application/json" try using "Accept:application/json"

**Comment by heyitscoco** [comment]
I'm having the same problem. I have the most recent version of Postman (4.10.5) and I have an application running in production and on localhost. When I direct the request to localhost (or even when I just copy the cURL command), the Content-Type header is included as expected. But when I change the url to hit the production app, the Content-Type header is missing.

**Comment by jeffmcmahan** [comment]
Yeah, same problem with the latest version (4.10.7); no matter what I do, no content-type header is set.

**Comment by cyruszhang** [comment]
got the same problem with the chrome extension. the app works though.

**Comment by dimiork** [comment]
Postman 5.1.3 - it still doesn't seem to work

**Comment by sdnts** [comment]
Guys, can you check this on our [native apps](https://getpostman.com/apps)?
The native apps work on an improved request framework, and things like this shouldn't happen. I'd recommend shifting to it anyway, since Google will deprecate Chrome apps soon.

**Comment by aminhotob** [comment]
Have same issue with macOS application  5.2.0 PostmanRuntime/6.3.2

**Comment by ozbillwang** [comment]
Thanks, @madebysid 

Seems it is fine on my mac with this native apps `version 5.2.0`. I can set headers `Content-Type` to `application/json`, and `GET` works.

But when I test `POST` request and set body with `format data` (several key-values),  for example, 

```
name: wrwe
address: werewr
```

It always reports 

```
{
    "message": "Invalid content type (multipart/form-data).  These are valid: application/json"
}
```
I have to set with raws data with below json format directly

```
{
  "name": "wrwe",
  "address": "werewr"
}
```

Now it works. But why it doesn't work with `format-data`?

**Comment by ShahramHaftlang** [comment]
I have the same problem and had to use raw format for POST body
