### ISSUE TITLE
Import a HAR?

### ISSUE THREAD

**Issue by tomardern** [postmanlabs/postman-app-support#350]
It would be awesome if you could copy "HAR" from Chrome (Network -> Right click -> Copy as HAR) or cURL (Network -> Right Click -> copy cURL) into the app to use.

**Comment by DoctorQ** [comment]
+1

**Comment by mohammedpithapurwalasc** [comment]
ping !

**Comment by ZaidDireya** [comment]
+1

**Comment by Arrow7000** [comment]
Any update on this? Why was this closed?

**Comment by sdnts** [comment]
HAR import support is not available at the moment, but you can import a cURL as discussed in #86

**Comment by Arrow7000** [comment]
Ah I see, thank you!

**Comment by Bluscream** [comment]
HAR file support please!

**Comment by cdax** [comment]
+1

**Comment by cpoissonnier** [comment]
+1

**Comment by whitemalt** [comment]
+1 pls

**Comment by bneigher** [comment]
+1 would b cool

**Comment by anurbol** [comment]
+1 Yes please. Absence of this feature stops me from using postman for few years...

**Comment by cherepanov** [comment]
+1

**Comment by merkuriy** [comment]
+1 HTTP Archive (HAR)

**Comment by studgeek** [comment]
#86 is related to this, but not exactly the same (and closed). This request is to support importing the HAR (HTTP Archive) format that Chrome and other tools support (including IE,  FIrefox, Fiddler, and Charles Proxy).
http://www.softwareishard.com/blog/har-12-spec/
https://en.wikipedia.org/wiki/.har

**Comment by andydude** [comment]
https://har.tech/

**Comment by gustaf-uy** [comment]
Hi, everybody!
I implemented a php script for importing .har files into postman collection v2.
https://github.com/gustaf-uy/postman-importer

I spect this helps.

**Comment by leMedi** [comment]
+1

**Comment by BalazsR** [comment]
+1

**Comment by Bluscream** [comment]
Hm

**Comment by koneko096** [comment]
+1

**Comment by garmr** [comment]
Hello,

+1

**Comment by jithintomz** [comment]
+1

**Comment by Rezi** [comment]
+1

**Comment by diofeher** [comment]
+1

**Comment by denisdanielyan** [comment]
+1

**Comment by dorokhin** [comment]
+1

**Comment by mjarraya** [comment]
+1

**Comment by Bluscream** [comment]
+1

**Comment by ChristianRich** [comment]
+1

**Comment by carlosabrantessumup** [comment]
+1

**Comment by Malek-Zytoon** [comment]
+1

**Comment by SamuelYvon** [comment]
+1!

**Comment by TheLastWarrior** [comment]
+1

**Comment by igatanasov** [comment]
+1

**Comment by pavlalexandr** [comment]
+1

**Comment by ManuelSch** [comment]
+1
is anyone even looking at this? it's been 5 years since the initial request...

**Comment by verissimor** [comment]
+1

**Comment by sourcec0de** [comment]
Doesn't look like postman wants to support HAR. You can import curl.
If anyone is looking for the solution. https://apimatic.io/transformer

This transformer can transform to and from a bunch of API specs. Including `HAR -> Postman 2.0`

**Comment by nshkg** [comment]
+1 to har. Nobody wants to use external services with phone registrations for import collection

**Comment by GregoirePiat** [comment]
+1

**Comment by cciatti** [comment]
+1

**Comment by pavlalexandr** [comment]
+1+1+1+1 👍

**Comment by yoavprat** [comment]
+1

**Comment by schwichti** [comment]
+1

**Comment by ttodua** [comment]
Probably it's better to use "Copy as Curl" and then import in Postman with "raw text"

**Comment by zlfnhmd** [comment]
+1

**Comment by Bluscream** [comment]
+1

**Comment by lrcarvalho** [comment]
+1

**Comment by vlad88sv** [comment]
+1!

**Comment by vlad88sv** [comment]
> Probably it's better to use "Copy as Curl" and then import in Postman with "raw text"

Thanks @zlfnhmd !

**Comment by JovanovicJovan** [comment]
+100

**Comment by cschnierer** [comment]
+1!

**Comment by mateusfccp** [comment]
+1

**Comment by sanjeetbisht** [comment]
+1

**Comment by rverma-nikiai** [comment]
+1

**Comment by glja021** [comment]
+1

**Comment by jorgefdt** [comment]
+1

**Comment by DavAlbert** [comment]
+1+1+1+1+1+1

**Comment by benwillkommen** [comment]
"Copy as curl" workaround worked for me! Thanks @ttodua!

**Comment by kotx** [comment]
Is there a reason for this not being implemented while being heavily requested for several years?

edit: iirc copy as curl does not support posting files?? last time I checked

**Comment by eduardoturconi** [comment]
There must be a reason...

+1

**Comment by a85** [comment]
We'd love to hear about specific workflows that people are doing with HAR. We support several formats and most tools export as curl or in some other way. What tools are you using and what is the workflow like?

**Comment by dada051** [comment]
Because HAR is a file format, so it makes it easier to share. IE only allows exporting as HAR. Firefox allows to copy AND EXPORT as HAR, but only to copy as cURL.

**Comment by 4selin** [comment]
+1

**Comment by togakangaroo** [comment]
When doing something like qraphql which contains `\n` inside a json field. When copying as cURL and pasting into postman (on a mac at least) those come across simply as `n` dropping the back slash.

Doing as HAR would give us another alternative

**Comment by clounie** [comment]
> We'd love to hear about specific workflows that people are doing with HAR. We support several formats and most tools export as curl or in some other way. What tools are you using and what is the workflow like?

1. Perform action(s) in browser
2. Copy HAR so you can "replay" the actions in postman
3. Import HAR as a postman collection
4. Run all in a row, or individually, in postman, to debug issue

**Comment by MeghnaChhabria** [comment]
Using HAR you can import multiple curl requests at once. Which is not otherwise possible.

**Comment by Greek** [comment]
stop with the +1s jesus

**Comment by puff** [comment]
> stop with the +1s jesus

+1

**Comment by jpmzx1** [comment]
+1

**Comment by Regenhardt** [comment]
Still nothing? This has been open for 7 years now, and still not in development?

**Comment by kotsh** [comment]
This is disappointing and says something about Postman's development as a whole.

**Comment by JakeTrock** [comment]
> We'd love to hear about specific workflows that people are doing with HAR. We support several formats and most tools export as curl or in some other way. What tools are you using and what is the workflow like?

I want to move my workspace over from insomnia, because insomnia has no unit testing tools to speak of(something I wish I knew when I started using it), and I have around 50 complex requests that I have to move over, I could either do it manually, or attempt to export as a HAR, and import it into postman. Sadly this isn't possible, which means I'll have to use the more tedious model.

**Comment by rmharrison** [comment]
@JakeTrock Thanks for sharing. I called-out the callousness of Postman-only exports in a [review](https://medium.com/@rmharrison/an-honest-review-of-insomnia-designer-and-insomnia-core-62e24a447ce). If it were the other way-round, you'd be o.k. As Insomnia Designer supports Postman and HAR imports, as well as HAR exports.

**Comment by JakeTrock** [comment]
@rmharrison Just read the article, I can't believe this has been going on for 7 whole years! Let's hope this is the last. I ended up using a GUI automator to record all of my actions and play them back on the insomnia gui, but this is certainly not ideal for my teammates.

**Comment by a85** [comment]
@rmharrison Postman Collections do not have a 1:1 mapping between HAR files. This thread is about importing HAR files and not exporting. Thank you for reviewing Postman though. The article was insightful though not sure if I entirely agree with some parts.

@JakeTrock We are tracking this thread. Postman supports many formats along with the inter-conversion between them. It is not possible to support every single format that somebody else invented and it takes multiple years for support on either side to mature. Format creators do not wait for tooling vendors to update their tools and the more formats we support, the more we have to catch up. For example, we are the only tool that supports OpenAPI, Swagger 2.0, RAML, GraphQL along with several other imports. We look at feature requests that accumulate interest over time for a large majority rather than a small feature request that is needed by a loud minority. The other way of looking at it is that this feature was never requested in large numbers by Postman's user base because people needed other things.

Why is this thread open? Because we don't like to close threads even if there is a single user who needs a feature. Most repos have a policy of auto-closing when the feature can't be implemented. We don't do that. Yes, it looks outrageous that this is open for that long but there are 2-3 issues that are open for that long. There are hundreds of others that have been closed. 

In the last 7 years, we have grown from a single developer to now 100+ and we are doing things in a single week which used to take 6 months before. We have a high confidence that we will get this done this year. If not, we will update the tracker here.

**Comment by javieraviles** [comment]
Hi everybody in the thread.

A collegue and I are implementing an online tool/node package to convert `har` files to `postman collections`. It is already working quite nice for our use cases (api tests regresion from existing frontend) even though we have some more features to be implemented in the backlog (see readme) if we see some people interested. Here is the repo:

https://github.com/javieraviles/Har2Postman 

and here the online page for the tool where you can directly upload a har file and get the output for the collection:

https://javieraviles.github.io/Har2Postman/

We would like to measure if there is some interest on it from the community to keep developing it or not, so some stars/issues would be much much appreciated. Thank you all!

**Comment by eduardoturconi** [comment]
@a85 seriously?
"It is not possible to support every single format that somebody else invented"
Do you know that the HAR format has a spec written by the W3C group? The format is NOT a "single format that somebody else invented".

**Comment by jgouro-hub** [comment]
+500

**Comment by pmneve** [comment]
+1

**Comment by johndpope** [comment]
Having spent $$$ on this for subscription for a tester without this feature it’s crippling to get setup and to prime the collections from output of a Charles capture from mobile app. 
Do you guys need to build your own transparent proxy to compete here? I’m sure you have the bandwidth. I want to record mobile app traffic and play it back as a test. If you don’t want to touch http archive file format / that’s fine. But give me a solution to this use case. 
I will have a go at using the open source options / thank you developers for building this. Again / We’re not asking har export just http archive import. I want to use system / turn on monitoring /NB  the open api json did get us some where but not as useful as it containing sample values / queries. For the 100x developers working on other problems / please buy out Charles proxy software and put in a export to postman. Done. You win / we win. 

Update - fixed it
https://github.com/ambertests/charles_to_postman

**Comment by gustavguez** [comment]
A few years ago I did this: https://github.com/gustavguez/postman-importer, is it still valid?

**Comment by axd3** [comment]
+1

**Comment by eduardoturconi** [comment]
+1

**Comment by KrishAmal** [comment]
+1

**Comment by summersjc** [comment]
+2

**Comment by johndpope** [comment]
might help (in relation to Charles software) - Acquisitions - how to take over another company https://www.unbiased.co.uk/life/small-business/acquisitions

https://www.linkedin.com/posts/abhinavasthana_postmans-series-d-funding-and-the-api-first-activity-6833747154650198016-0aML

You can let the CEO know here.

**Comment by x3ro** [comment]
+1

**Comment by gkizior** [comment]
+1

**Comment by kotx** [comment]
+1

**Comment by kotx** [comment]
> We have a high confidence that we will get this done this year. If not, we will update the tracker here.

@a85 Any update?

**Comment by ivnnv** [comment]
wow, almost 10 years and still no HAR importer, this is what fast iterating looks like 😆

**Comment by DylanDelobel** [comment]
I would love to see HAR support 👀

**Comment by dissolved** [comment]
I mean, this is why I don't pay for a subscription. It is absurd that this wasn't a feature years ago.

**Comment by arlemi** [comment]
Hey everyone! 

From Postman v9.6 you can now import HAR files directly into Postman, you also have the options to import responses/cookies when generating the collection:
![import_har](https://user-images.githubusercontent.com/5029719/146942294-72dc1d12-5a55-404b-8d1f-c2261e68aec1.gif)

**Comment by jxh150535011** [comment]
+10086
