### ISSUE TITLE
Encoded unicode character.

### ISSUE THREAD

**Issue by louisnguyen1012** [postmanlabs/postman-app-support#3676]
## App Details:

```
Postman for Chrome
Version 5.3.1
win / x86-64
Chrome 62.0.3202.62
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Try to post with body: {"expression":"'\u0027 + @@version + \u0027'"}
 2. Expected behaviour:
It should similar with Chrome did. The Chrome transferred that body to  {"expression":"'\\\u0027 + @@version + \\\u0027'"}

**Comment by louisnguyen1012** [comment]
It also occur with display response: if the response is {"expression":"'\\u0027 + @@Version + \\u0027'"}.
The Chrome showns: {"expression":"'\u0027 + @@Version + \u0027'"}
But the Postman shows: {"expression":"'\\u0027 + @@Version + \\u0027'"}

**Comment by prashantagarwal** [comment]
@louisnguyen1012 Thanks for reporting this.

**Comment by SamvelRaja** [comment]
@louisnguyen1012  I can see the latest 6.1.4 native app sent the request as expected like chrome.

![screenshot 5](https://user-images.githubusercontent.com/5114052/42088864-b1103a7c-7bb8-11e8-965e-76656a8fee10.png)
