### ISSUE TITLE
Feature request: Ability to customize file save path

### ISSUE THREAD

**Issue by mwmitchell** [postmanlabs/postman-app-support#383]
If POSTMan allowed you to set the directory where files are saved, a user could set this path to point to a Git (for example) repository. This would make it possible version your collection and share with other developers very easily. It would also make it possible to keep sharing private, depending on the repository settings etc..

I'd be happy to take a crack at this if someone could point me in the right direction.
- Matt

**Comment by jmisur** [comment]
May I ask for status of this Git-based sync? Is it completely disregarded in favour of money-making Team Sync feature?

**Comment by dmg3** [comment]
+1 for this feature.  Teams these days require this sort of information to be kept in an scm tool.

**Comment by thibaultlaurens** [comment]
+1

**Comment by rodgeve** [comment]
This is a deal breaker.  I am championing the Postman tool to my company and we're ready to go prime-time on it but not being able to use SCM effectively on Postman collections will look really bad and be very painful to work-around.

I've tried the Team Collaboration tool and there seems to be no way of doing code-review on changes to Collections.  If a collection is shared then anyone can update it and my collection is synced without having a change-review process.

Regarding the HTML5 limitation, if such a limitation still exists, then working off a collection definition from a file on something like Google Drive may be acceptable, as I can push my SCM based resources to remote storage if necessary through scripted automation.

**Comment by miked0004** [comment]
+1, interested in progress on this. Since I am able to use the Postman app for Mac, it would have easy read/write to the file system and the data dir could be preserved in SCM.

Any updates? Good product, just needs this capability. Would be even better if it was built into the app like SoapUI.

**Comment by Stevoisiak** [comment]
There are many valid reasons for wanting to dictate Postman's save directory.

_For example_: I am currently working with a private API which includes confidential company data. All sensitive data must be saved locally to a secure drive, meaning Postman's built-in data synchronization is simply not an option for me.

**Comment by johnmckay-reward** [comment]
+1 I would find this really useful! Thanks!

**Comment by a85** [comment]
There are currently no plans for this feature now or in the near future.
