### ISSUE TITLE
Support OAuth 2 helper through localhost

### ISSUE THREAD

**Issue by adambarber** [postmanlabs/postman-app-support#410]
I'm having trouble getting OAuth 2 authentication to work.

My local API is a rails app, using [doorkeeper](https://github.com/applicake/doorkeeper) to handle authentication. The request seems to make it as far as the getpostman.com callback and returns a 500 error, with the message **Undefined index: oauth2_request_id**

Here's the actual error - https://www.getpostman.com/oauth2/callback?code=407aae8472fbc2420ee1baf4fc769392767f6c9ef2227e590500e6fc7088a9f&state=2567

**Comment by ngbrown** [comment]
If the `https://www.getpostman.com/oauth2/callback` service echo'd back the code and state to the Postman client, then the client could finish the transaction using the information.  This way localhost servers would be supported.

**Comment by FoxxMD** [comment]
:+1: to what @ngbrown said. How are we supposed to test local instances that use oauth?

**Comment by CaptainCodeman** [comment]
Using https://ngrok.com/ works great

**Comment by joshperry** [comment]
This should be closed with the "Request access token locally" feature.

**Comment by abhijitkane** [comment]
@FoxxMD @ngbrown The latest version of Postman - 3.0.8 supports non internet-facing OAuth2.0 providers.
