### ISSUE TITLE
How do I send multi-line POST variable?

### ISSUE THREAD

**Issue by jitbit** [postmanlabs/postman-app-support#448]

**Comment by r-barnes** [comment]
A literal `\n` is sent for me as well.

**Comment by PavloPoliakov** [comment]
@a85 

that's true, \n doesn't work. How can we send the multiline variable?

**Comment by joostfarla** [comment]
Having the same problem. @a85, can this be reopened?

**Comment by a7744hsc** [comment]
Hi, seems this bug is still there? Is there a alternative method for me to send a multi-line POST by now?

**Comment by gligoran** [comment]
+1

**Comment by prakhar-singh** [comment]
When can we expect this issue to get closed?

**Comment by huysentruitw** [comment]
This should be very simple to solve. I just did a multi-line POST by inspecting the `<input type="text" class="keyvalueeditor-value keyvalueeditor-value-text" ...>` to a `<textarea ... >` and it worked.

**Comment by praburaja** [comment]
+1

**Comment by IsCaster** [comment]
+1

**Comment by abhijitkane** [comment]
@numaanashraf The issue here is that entering "a\nb" in the input field gives a string "a\nb", which is correct. One solution would be to offer a "multiline" mode, similar to text and file, that replaces the value `<input type="text">` with a textarea.

**Comment by huysentruitw** [comment]
Indeed, with the previous version of Postman, I could use dev-tools to replace the text input with a textarea and everything went smoothly. Shouldn't be that hard to implement.

**Comment by detarmstrong** [comment]
I'm trying to send CSV data with Postman and this is really a silly limitation. Is there any known workaround?

**Comment by samwalshnz** [comment]
+1

**Comment by alessandrorodi** [comment]
+1

**Comment by ay18** [comment]
+1

**Comment by MichaelJGW** [comment]
+1

**Comment by nsitbon** [comment]
:+1:

**Comment by somsub** [comment]
+1

**Comment by nsitbon** [comment]
One possible workaround is to export your collection (containing the POST field) to a JSON file then replace the content of the variable inside that JSON file (JSON supports multiline strings with \n) and then import the JSON file back into postman. Tedious but it works!

**Comment by MeLlamoPablo** [comment]
Hey folks, as much as I want this issue fixed, commenting `+1` isn't gonna deliver it earlier. Please use the thumbs up icon to show agreement instead.

**Comment by 2dvisio** [comment]
I have successfully sent my new line just by using the x-www-form-urlencoded option and via bulk edit.

Just add a newline (not the character, just a real new line)

**Comment by vkaegis** [comment]
Hey guys, quick update, we're working on a key-value editor which supports multi-line variable values. Will let y'all know as soon as it's out on Canary, so stay tuned!

**Comment by krizka** [comment]
Hi all! Have any updates on this?) how to do it with "Bulk Edit" editor??

**Comment by bhawna2109** [comment]
Hey guys, we now have support for this in our new data editor which is out in canary and will hit production soon. Check out the blog to know what you can do with this new editor and get the canary links - http://blog.getpostman.com/2017/02/28/introducing-the-new-data-editor/

**Pressing 'Enter' in a key or value field expands it and takes the cursor to a new line.**

Along with this, the canary build also includes variable highlighting, autocomplete and tooltips on hover. Variables are now detected and highlighted as you type. More details are here - http://blog.getpostman.com/2017/03/07/autocomplete-and-tooltips-for-variables-are-here/

Do let us know your feedback on these features! :)

**Comment by deyhle** [comment]
Thank you for that information.
However, when pasting some multi-line text into the canary version's editor, it still removes the newlines. Had to add them manually afterwards again.

**Comment by bhawna2109** [comment]
@deyhle this feature is out in production now - can you recheck once and let us know if you're still facing the issue?

**Comment by deyhle** [comment]
@bhawna2109 it works, thank you! This issue can probably be closed.

**Comment by tyronedougherty** [comment]
I'm running Postman v5.1.3 and am trying to `POST` a JSON multiline string like so:

```
{
	"publicKey": "-----BEGIN CERTIFICATE-----
	xxxxxxxxxx
	xxxxxxxxxx
	xxxxxxxxxx
	....
	-----END CERTIFICATE-----"
}
```

Nothing I do seems to work as Postman is not working with the multiple lines. Nothing I do seems to be working, using `\n` at the end of every line doesn't work, trying to insert newline unicode characters doesn't work, pasting the certificate into a JS console with the backtick character (\`) on either end and then copying the result doesn't work, etc.

Any suggestions? Or is this simply just not working in Postman at the moment?

**Comment by sdnts** [comment]
@tyronedougherty Does the data editor not allow you to paste multiple lines?
Pressing `Enter` in a value field should take you to a new line.

**Comment by marco-brandizi** [comment]
It doesn't work for me. Just downloaded 6.2.4. I still can't believe that this app was ever released without such a basic feature.

**Comment by numaanashraf** [comment]
@marco-brandizi Can you provide more details regarding the issue, specifically the steps you have followed and your expectations? As far as I see, this issue is resolved as it is possible to enter new lines in form-data or form-urlencoded fields, by just typing `Enter` in the value field.

<img width="680" alt="screen shot 2018-08-14 at 2 49 31 pm" src="https://user-images.githubusercontent.com/3295568/44083530-d6cd335e-9fd1-11e8-92a7-4cc02f9f2b10.png">
<img width="652" alt="screen shot 2018-08-14 at 2 48 58 pm" src="https://user-images.githubusercontent.com/3295568/44083531-d6fbccbe-9fd1-11e8-961a-08fee7ee1a24.png">

**Comment by marco-brandizi** [comment]
@numaanashraf, thank you for your prompt reply. Now I get it: When I click 'Params' next to the URL, i.e., parameters to be added to the URL for a GET request, I cannot use multi-line params in the corresponding table. That's not clear at all and it's a limit, because \n can be URL-encoded and appended to the URL just like any other character. Not a big deal in my case, where both GET and POST requests are supported, but it might be a problem if a service did support GET only.

**Comment by numaanashraf** [comment]
@marco-brandizi Thanks for the clarification. This should be possible and I've created a new feature request for the same at #5026.

**Comment by JoshanTandukar** [comment]
just put %0D%0A where you need the new line

**Comment by NanoNulla** [comment]
> just put %0D%0A where you need the new line

It worked for me.

**Comment by abhi-824** [comment]
> 
> 
> just put %0D%0A where you need the new line

Too much hardwork for me... I am making a markdown compiler and I need to send the text in form of a string..

**Comment by AlexanderZheka** [comment]
extra option - you can copy the curl command by clicking `code snippet` icon _(to the right from main working area - see image below)_ and then place \n in curl string directly. After it copy curl and execute it in terminal.  

<img width="154" alt="Screenshot 2022-01-20 at 10 52 35" src="https://user-images.githubusercontent.com/64766323/150315463-2acb81c1-1467-4a8e-a05a-4eb821e868cb.png">

**Comment by Luc45** [comment]
I have a string that is exploded by `\n`, but I can't send it on Postman because it expects ↵ as line break
