### ISSUE TITLE
Possibility to choose which token to use

### ISSUE THREAD

**Issue by jmezach** [postmanlabs/postman-app-support#492]
I'm trying to use Postman to test a REST service that is protected using JWT tokens retrieved from Auth0 (developer.auth0.com). If I enter the details for Auth0 into Postman and get an access token I get back the following access token data:

result → success
access_token → t2YBYE...
id_token →  eyJ0eX...
token_type → bearer#_=_

To access the service I want to test I need to send the id_token value in a header. However, by default Postman will use the access_token value and there's no possibility to choose otherwise.

It would be nice if it was possible to choose the token you want to use to sent in the authorization header somehow.

**Comment by gastonaguilera** [comment]
any new on this feature?
is a way to call oauth2 from prescript ?

**Comment by sarikav1986** [comment]
I am having same problem. I need to pass id_token to another call to get JWT token back. Can you let us know if I can read and store id_token value in a global/environment variable?

**Comment by ligol** [comment]
Any news on this issue? I got the same problem, I need to send the id_token return by auth0 not the access_token

**Comment by Hamitamaru** [comment]
Any update on this, this is a problem for AWS Cognito authorized API Gateway calls as mentioned here : https://github.com/postmanlabs/postman-app-support/issues/1854

**Comment by mannharleen** [comment]
Any update on this ?

**Comment by zzFluke** [comment]
I wonder what is the timeline for getting this implemented and released?

**Comment by PedroOrtegaEarnest** [comment]
Any updates on the timeline for this?

**Comment by BartusZak** [comment]
Any update?

**Comment by gentarooka** [comment]
Any update?
This issue blocks my manager's decision to upgrade to Postman Pro...

**Comment by llamasoft** [comment]
Just a heads up, this issue prevents us from accessing _any_ services running behind a [Google Identity Aware Proxy](https://cloud.google.com/iap/).  We can manually copy the `id_token` field, but the expiration is only one hour, so this results in a lot of frustrating downtime.

As for "how could this be added", I think adding a textbox or dropdown to the "Get New Access Token" window would be sufficient.  Maybe something like this?  https://i.imgur.com/WmCmSmV.png

**Comment by kdrapala** [comment]
Any update?

**Comment by davidepedranz** [comment]
Any update on this issue? This feature would be amazing for organizations running services on Google Cloud Platform and using [Identity Aware Proxy](https://cloud.google.com/iap/) to protect internal  services 🤔

**Comment by timothybowers** [comment]
Can we access the id-token via {{managedTokens.id_token}} ?

**Comment by tinkermakar** [comment]
+1

**Comment by giridharvc7** [comment]
You can now select between `ID Token` and `access token` (depending on the OAuth response) in your requests in the latest version of Posmtan. Please give this a try and let us know what you think. 
You can read more about this [here](https://blog.postman.com/oauth-2-0-token-refresh-and-id-token-support/)

**Comment by ejfasting** [comment]
Any plans to make the id_token available as a variable in a pre-request script and/or test? Not replacing what the authorization method uses, but make the id_token available so that you can get the claims from it.

**Comment by SamCosta1** [comment]
+1 on @ejfasting 's comment, it would be really helpful to be able to access the authorization properties from within a pre-request script.
