### ISSUE TITLE
Executing concurrent requests

### ISSUE THREAD

**Issue by givan** [postmanlabs/postman-app-support#493]
Hello,

I want to be able to execute X number of concurrent requests to the API. I'm not able to do that with the current UI. Am I missing something or it's a future item?

Thanks,
- George

**Comment by chandramohan-lakshminarayanan** [comment]
Hello, 

Given that now POSTMAN is also available as a standalone (not relying on Chrome anymore) , can we get to know when will the POSTMAN get the Async HTTP client feature to run concurrent requests? 

Thanks, 
Chandra

**Comment by MetaiR** [comment]
any update on this?

**Comment by amatlock930** [comment]
any update on this? Would like to see this scheduled...

**Comment by bmcdaniels** [comment]
^  Thirded, this would be very helpful

**Comment by dietermijle** [comment]
+1

**Comment by vgosai86** [comment]
+1

**Comment by ledzep3012** [comment]
+1

**Comment by zainbnv** [comment]
any update on this? its 2019 already.

**Comment by GF-Huang** [comment]
+10086

**Comment by eugenehoza** [comment]
pleeeease, do this!

**Comment by 090media** [comment]
+1!

**Comment by ARM-Source** [comment]
+1

**Comment by yunkuangao** [comment]
+1

**Comment by malvikach** [comment]
Hi folks,

We are looking at building this capability in Postman. Therefore, I want to understand your suggestion better.

You are looking to simulate parallel threads which can send the requests so you can load-test your endpoints. Can you elaborate more on what kind of load you want to simulate (a couple of hundred of parallel threads vs thousands?). What kind of output metrics are you interested to look at (Response times/ error rates, anything else etc.) What would you like the visualizations to capture?

I would love to discuss your use case in more detail. 

If anyone here is interested, I would request you to block some time with me to talk about this. You can use [this calendly link](https://calendly.com/malvika-chaudhary/v10-feedback?month=2023-03) to send me an invite.

Looking forward to your feedback.

Regards,
Malvika

**Comment by malvikach** [comment]
Hi All,

Glad to update that in the latest Postman release (version 10.15.1), we have released API Performance Testing feature. You can now use Postman to simulate real world traffic and observe your API Performance Metrics. 

Read more about this on our blog [here](https://blog.postman.com/postman-api-performance-testing/). 

We look forward to your feedback. 

Cheers!
Malvika
