### ISSUE TITLE
[Oauth2] Use response_type token instead of code

### ISSUE THREAD

**Issue by mtparet** [postmanlabs/postman-app-support#494]
Instead of asking a code and doing an another API call with a client_id/secret to get a token, just ask a token directly. 
https://developers.google.com/accounts/docs/OAuth2UserAgent

This will permit  
- a better security by avoiding to leak `client_secret`
- oauth2 to work in a local environment (not facing internet)
- avoid some bugs

**Comment by abhijitkane** [comment]
@mtparet The latest version of Postman - 3.0.8 supports OAuth2.0 providers that are not internet facing. There's a "request access token locally" option which you need to enable.

**Comment by mtparet** [comment]
Awesome, I will try it.

**Comment by rawler** [comment]
+1

**Comment by shamasis** [comment]
@abhijitkane can this be closed?
