### ISSUE TITLE
Custom http codes

### ISSUE THREAD

**Issue by sgeef** [postmanlabs/postman-app-support#505]
I'm missing the implementation of the following:

quote from RFC 2616:
"HTTP status codes are extensible. HTTP applications are not required to understand the meaning of all registered status codes, though such understanding is obviously desirable. However, applications MUST understand the class of any status code, as indicated by the first digit, and treat any unrecognized response as being equivalent to the x00 status code of that class, with the exception that an unrecognized response MUST NOT be cached. For example, if an unrecognized status code of 431 is received by the client, it can safely assume that there was something wrong with its request and treat the response as if it had received a 400 status code."

I made a REST api that returns a custom code. But the post repsonse sais 442 - OK. Shouldn't this be 442 - Error?

**Comment by a85** [comment]
HTTP Status codes return descriptions sent by the server.
