### ISSUE TITLE
XMLTree configuration options

### ISSUE THREAD

**Issue by maedox** [postmanlabs/postman-app-support#508]
I would like to get some settings to configure the look and feel of the "Pretty" view, at least for XML which I use the most. 

1. Configurable amount of levels to expand by default. (@a85 told me in an email the other day that they'd expand all levels in a future release.)
2. The text size is a bit too large for my liking.
3. Text wrapping is weird, especially with the "Outline" view collapsed. The XML view is not expanded to fill the available space.

![scrsht_025](https://f.cloud.github.com/assets/246270/2332131/f6507e22-a452-11e3-81fc-9d2486bc4525.png)

**Comment by a85** [comment]
XMLTree is not present in the new app. We have switched to Ace Editor.
