### ISSUE TITLE
Tablularized view for JSON or XML Output

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#519]
I'd like to see ability to show the output of repeating JSON or XML structures in a tabular view.  This is related to Issue #357 but the solution implemented for #357 did not meet my need :(

I'm hoping to hear from others to know if folks in general would like this functionality.  Please add your comments if so.

Goal: View repeated JSON or XML data sets in tabular format.  I use our REST APIs to troubleshoot issues often.  We return things like media file lists of 100 or more entries.  Or maybe a list of devices and entitlements inside a user JSON doc.  Its sometimes extremely helpful to view this data in tabular format (one column for each property, one row for each new JSON document).

The ideal solution is exactly what is offered by [JSON Prettifier](https://chrome.google.com/webstore/detail/kccpfgilgmgbipamhohknpokhibinhhj) for JSON.  Maybe [XML2HTML](http://www.codeproject.com/Tips/512500/Converting-XML-string-to-HTML-Table) for XML.

The awesome thing about JSON Prettifier is that it does not need to know anything about your JSON structure.  It creates a table from the 1st level and you can recursively expand cells into tables to any nested level if your JSON contains nested structures inside each element.  You really have to see it in action to appreciate it.

**Comment by jungle-boogie** [comment]
After this was created nearly a year ago, hopefully we'll see an update to postman with this feature!

**Comment by ray-qu** [comment]
Would like to know if this feature is in place. If yes, could you please shed light on enabling it as it doesn't seem to appear in standard view?

In case its still being considered, would suggest to refer Grid view in Altova XML spy for JSON or XML content, which is somewhat similar to the original request, but need with direct edit capability as well. There seems to be many links to this feature request, which makes it to be great demand.

http://manual.altova.com/xmlspy/spyenterprise/xseditingviews_gridview_tables.htm
or, http://valentin.dasdeck.com/lingo/dml/screenshots/xmlspy_grid_view.png

**Comment by johnoscott** [comment]
I would very much like a feature to display JSON records as a table.

**Comment by prmichaelsen** [comment]
Still hoping for this feature. It would also be nice to be able to input json data in a tabularized view

**Comment by abdelaliz** [comment]
this feature would be a killer. please please please

**Comment by andrewtuplin** [comment]
It's been almost 5 years. I think there are still a lot of people that would like to be able to format a JSON response as a table. Is this going to happen?

**Comment by johnoscott** [comment]
I agree. (cough! console.table cough!)

**Comment by frankbret** [comment]
I don't know if its the right place to suggest this, but it seems complementary...
I would like to see my data in **tree view** like notepad++ (or vs code) "json viewer" do it :
![tree view](https://user-images.githubusercontent.com/403073/59285105-6cede580-8c3b-11e9-8d54-2ed367f5938c.png)
Maybe the Response body "Preview" mode could do this...

**Comment by johnoscott** [comment]
Yes I agree. When can we have such a view in Postman ?

**Comment by kyunussov** [comment]
looking fwd to it!

**Comment by codenirvana** [comment]
Hello Everyone 👋
It took us a while but we've added support for **Visualizers** in the lastest Postman app v7.7.

<img width="1552" alt="visualizer_table" src="https://user-images.githubusercontent.com/4865836/65037474-68884580-d96b-11e9-9a3b-b0d43e21bfd6.png">

Learn more about visualizers here: https://learning.getpostman.com/docs/postman/sending_api_requests/visualizer/

Here's a similar Postman template to visualize CSV response as a table: https://explore.postman.com/templates/3769

**Comment by imtrobin** [comment]
hmm, is there a way to do it like json2table.com ? I don't really need to write specific visualizers with json2table

**Comment by sivcan** [comment]
@imtrobin I published a template that should help you out - https://explore.postman.com/templates/3769

You can import it in the app and run it to visualize any JSON / CSV response.
