### ISSUE TITLE
Collection runner - exception in test code

### ISSUE THREAD

**Issue by ariscris** [postmanlabs/postman-app-support#530]
I can see errors in the Chrome console while running my Collection.  I can't figure out which test is producing the error.  I think that these should be reported beside the failing test instead of the red notification boxes that go away quickly and don't report which test is failing.  In addition, I think that there should be a try-catch in the test runner so that bugs in the test don't cause later tests to silently fail or not run anymore.  Thanks.

```
ReferenceError
message: "Invalid left-hand side in assignment"
stack: "ReferenceError: Invalid left-hand side in assignment↵    at eval (eval at <anonymous> (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:62:24), <anonymous>:5:1)↵    at eval (eval at <anonymous> (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:62:24), <anonymous>:5:139)↵    at chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/tester/Evaluator.js:62:19"
__proto__: Error
constructor: function ReferenceError() { [native code] }
name: "ReferenceError"
stack: undefined
__proto__: d
```

**Comment by sdnts** [comment]
@ariscris We addressed this feature request in the redesign of our runner. You can download the Canary release [here](https://dl.pstmn.io/download/channel/canary/osx_64).
I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
@ariscris The redesigned Runner is out now with the latest release (4.9) on our native apps. You should be able to view which test is causing errors more clearly now.
