### ISSUE TITLE
Integration of dev tools like Clockwork to POSTMan

### ISSUE THREAD

**Issue by sameer1001** [postmanlabs/postman-app-support#532]
Was wondering how cool will it be, if we can see the number of database queries and other performance related information in the POSTMan itself in a separate panel.

For PHP development there is tool called Clockwork. With a chrome extension this tool provides a new panel with all kinds of useful debugging and profiling information, including db queries, session data, and much more.

Link: https://github.com/itsgoingd/clockwork-chrome

**Comment by RachelScodes** [comment]
_bumping this thread_ 

Now that the postman chrome extension no longer works, it would be nice to be able to use clockwork in the standalone app.

**Comment by a85** [comment]
We'll be working on APIs on the client side for our native apps soon that should help with integration of other tools into your workflow. Closing this feature request for now. Will open new requests and share more details as the roadmap on this becomes more concrete.
