### ISSUE TITLE
A way to retry the current request in test code

### ISSUE THREAD

**Issue by underyx** [postmanlabs/postman-app-support#533]
I'm testing an API that has asynchronous calls: a POST request to http://localhost/example will respond to the first request with a HTTP 202 status code, and the same URL will respond with the results when called 10-40 seconds later.

I basically would like to write something like this in my test code:

``` javascript
if (responseCode.code === 202) {
  setTimeout(request.retry, 5000);
}

// actual test code goes here
```

**Comment by a85** [comment]
@shamasis Can you please track all these issues that are related to the collection runner flow?

**Comment by troyschneringer** [comment]
+1

**Comment by johanntang** [comment]
+1  This would be great.

**Comment by rharmaning** [comment]
+1 agreed, very valuable feature

**Comment by thedrewbisset** [comment]
+1

**Comment by troyschneringer** [comment]
What's the status on this?  Are there plan to implement this feature?

**Comment by deardooley** [comment]
+1

**Comment by eyalstein** [comment]
+1

**Comment by sobtiankit** [comment]
Asynchronous testing is making its way into the app soon. However, in case anyone is looking to retry the current request (without the async timeout), you can checkout: medium.com/@sobtiankit/conditional-workflows-in-postman-f79c05306671. Docs here: https://www.getpostman.com/docs/workflows

**Comment by eyalstein** [comment]
Thanks @sobtiankit !
I implemented your solution using setNextRequest and it works for now.
Waiting to hear when it will be added to the app.

**Comment by shamasis** [comment]
The original use case posted in issue, seems a bit misaligned with how things can be done. Async script will causing a request retry does not fit in. Instead, we need to explore alternatives such as delay in requesting or other such workarounds.

The solution https://www.getpostman.com/docs/workflows solves most part of it though
