### ISSUE TITLE
Add ability to halt test and/or collection using code within the test

### ISSUE THREAD

**Issue by mbakaitis** [postmanlabs/postman-app-support#542]
Add a `postman.break` and `postman.continue` option for testing.

When `break` is called, the current test **and** collection is immediately ended.

When `continue` is called, the current test is immediately ended but if a collection is running, the next request/test in the collection is started normally.

There are a few reasons I can imagine for this, but the main one for us is when test data on the server wasn't uploaded before we run a collection against it.  

Writing a few tests at the start of a collection that verify test data was loaded can save QA some hassle as the tests could be written to bail with a clear reason so they could take steps to repair/configure for a run.  We're working around this with some globals, for the moment, but it would be nice to have options to bail out of a test or collection.

**Comment by cain004** [comment]
+1

**Comment by shamasis** [comment]
cc @czardoz

**Comment by shamasis** [comment]
Hello, this is a fairly old issue, but with the features added to Postman sandbox over time, this can be achieved and this issue can be closed. 

1. pm.sendRequest can send requests from inside scripts
2. setTimeout of JavaScript pauses a script until the timeout is complete or cleared
3. postman.setNextRequest(null) stops a run
4. pm.test(function (done) {}) - the “done” parameter can be used to make tests wait. 

Also, keeping a note here that the need to control flow explicitly using code and to control flow from outside using UI are tracked in other issues already.
