### ISSUE TITLE
Crashing when POSTing a multipart file of 300MB

### ISSUE THREAD

**Issue by caio1982** [postmanlabs/postman-app-support#555]
Hi, I've noticed that it's not currently possible to post both a JSON request and a multipart file at the same time when trying to simply post a random file. I'm working with large ones, around 300MB. It seems Postman don't like these as it crashes every time running the latest stable 64bits Chrome and Postman available for Linux. I've tried with smaller files (well as small as it gets, i.e. 4K) and it didn't crash. Here's the only interesting lines I could get from gdb at the moment of the crash:

[New Thread 0x7fff390e1700 (LWP 10668)]
[New Thread 0x7fff388e0700 (LWP 10669)]
[New Thread 0x7fff1ffff700 (LWP 10670)]
[New Thread 0x7fff1f7fe700 (LWP 10671)]
[New Thread 0x7fff1effd700 (LWP 10672)]
[New Thread 0x7fff1e7fc700 (LWP 10673)]
[Thread 0x7fff1e7fc700 (LWP 10673) exited]
[Thread 0x7fff388e0700 (LWP 10669) exited]
[Thread 0x7fff1effd700 (LWP 10672) exited]
[Thread 0x7fff1ffff700 (LWP 10670) exited]
V8 error: Allocation failed - process out of memory (CALL_AND_RETRY).  Current memory usage: 1784 MB
1   0x7f8f327a3090
2   0x7f8f3295a6e9
3   0x7f8f3295aba7
4   0x7f8f3295b4a1
5   0x7f8f3295c01f
6   0x7f8f329ac7df
7   0x7f8f328b1b24
8   0x35d98cb06ace
[New Thread 0x7fff1ffff700 (LWP 10680)]
[Thread 0x7fff1ffff700 (LWP 10680) exited]
[Thread 0x7fff1f7fe700 (LWP 10671) exited]

Please let me know how could I debug it further so I'm able to provide more details on this issue!

**Comment by travismcchesney** [comment]
Any update on this? I'm seeing the same thing in, what I guess, is version 3.0.2.

**Comment by coryallegory** [comment]
any progress, or more info required?

**Comment by abhijitkane** [comment]
We're not processing the file once it's selected from the 'Choose Files' selector. Probably some limitation of the Chrome app platform. Will continue investigating.

**Comment by nturnley** [comment]
I am still seeing this as well but with a file size of 50 MB

**Comment by LorandLorincz** [comment]
+1

**Comment by Bubelbub** [comment]
Still having the issue on files larger than ~ 30 MB.

**Comment by shamasis** [comment]
@Bubelbub - seems like in Postman v4.5+ the app does not crash when uploading large files in form-data mode. The binary mode is still crashing though. @numaanashraf @czardoz

**Comment by bhbabu** [comment]
I have postman 3.8.1 and still seeing this issue with 204MB file.

**Comment by sdnts** [comment]
@bhbabu Postman 3.8.1 is a very old version, which is no longer maintained. Could you try the same with the latest version? (4.8.1)

**Comment by bhbabu** [comment]
sorry for my typo earlier. I do have 4.8.1 and this problem is noticed with a 204MB file.

**Comment by ravibisht** [comment]
r

**Comment by ravibisht** [comment]
ravi
