### ISSUE TITLE
Setup app.getpostman.com server on local machine

### ISSUE THREAD

**Issue by leiguorui** [postmanlabs/postman-app-support#5559]
**Is your feature request related to a problem? Please describe.**
I do not want to share postman collections on the public internet.

**Describe the solution you'd like**
I can setup a app.getpostman.com server on my local machine.

**Comment by numaanashraf** [comment]
@leiguorui Thanks for writing in. I'm afraid this wouldn't be possible for the time being as you are asking to run Postman's entire cloud infrastructure locally. Could you let us know why you'ld want this?
