### ISSUE TITLE
Collection testing options. Iterate, link, parallel testing.

### ISSUE THREAD

**Issue by toriacht** [postmanlabs/postman-app-support#571]
Hi Abhinav,

Some product suggestions:
- Iterate a single request within a collection
- Link Collections...e.g. when Collection 1 finished start collection 2
- Parallel testing .. e.g. Start 5 concurrent instances of same collection from collection runner

/

**Comment by wcandillon** [comment]
I have started to build a newman test runner that runs requests in parallel at https://github.com/wcandillon/courrier

**Comment by GabbyChangSH** [comment]
@a85 Does postman support parallel testing now?

**Comment by IsmiKin** [comment]
:+1:

**Comment by sdnts** [comment]
Guys, Feature 1 is possible now using postman.setNextRequest. Docs are [here](https://www.getpostman.com/docs/workflows)
Feature 2 is not in our immediate or long-term roadmap as of now.
Feature 3 is also possible in the redesign of our runner, which is on our Canary channel. You can download the Canary release [here](https://dl.pstmn.io/download/channel/canary/osx_64).
I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
Guys, the new Runner is out with our latest release (4.9) on our native apps. Concurrent runs are now possible :)

**Comment by rest17** [comment]
@madebysid 

I am using currently Postman for Mac version 4.9.3. Does this version runs has concurrent run support.  If collection has an iteration of 10 will all ten request will run concurrently or sequentially.

**Comment by sdnts** [comment]
@rest17 Ah you're talking about concurrent iterations, that isn't possible (yet). By concurrent runs, I meant you can have multiple runs running at the same time.
At this time, iterations are sequential. Hopefully this clears up your doubt.

**Comment by ColinSquint** [comment]
This would be a lovely feature to have in the interface (concurrent/parallel interations of the same run) .. as I understand it, it would have to be native

For the meantime I am using newman and something like ;
for(var i = 0; i < 5; i++)
newman.run()

```
var newman = require('newman');

var stats = []
var timings = []
var promises = []

for(var i = 0; i < 2; i++)
promises.push(new Promise(function(resolve, reject) {
  newman.run({
    collection: require('./postman_collection.json'),
    environment: require('./postman_environment.json'),
    reporters: 'cli',
    delayRequest: 100
  }).on('start', function (err, args) { // on start of run, log to console
      console.log('running a collection...');
  }).on('done', function (err, summary) {
      if (err || summary.error) {
          console.error('collection run encountered an error.');
          reject()
      }
      else {
          resolve(summary.run)
          console.log('collection run completed.');
      }
  })
}).then(function(response) {
  stats.push(response.stats)
  timings.push(response.timings)
}))

Promise.all(promises).then(function() {
  console.log("All concurrent tests completed")
  console.log(stats)
  console.log(timings)
})
```


It keeps playing leapfrog in the console but the final output is quite easy to digest

**Comment by chillosu** [comment]
Any chance parallel execution made it onto the roadmap?
