### ISSUE TITLE
Install Chrome Packaged App from source code

### ISSUE THREAD

**Issue by paragbaxi** [postmanlabs/postman-app-support#574]
I'm leveraging POSTMAN to enable folks [to more easily leverage our API](https://community.qualys.com/docs/DOC-4523#Web_browser_Chrome_Postman).

I want to distribute the app on a VM. Installing from the Chrome app store requires a Google account, which I want to avoid. When I install from this repository, POSTMAN is installed as an extension.

Where can I download POSTMAN Packaged app to install from a zip, avoiding the Google login?

**Comment by WhyNotHugo** [comment]
> We'd be releasing the source code hopefully soon. Currently the Jetpacks upgrade is tied closely with the code.

Any ETA on this? There only seem to be binaries available currently.

**Comment by a85** [comment]
Closing this issue for now as the Chrome app platform itself has been deprecated. We have open-sourced several libraries that are part of the new Electron app: https://github.com/postmanlabs. We still need to refactor large parts of the codebase and work through data layers. Will hopefully have more to share in 2018.
