### ISSUE TITLE
Hawk Authentication Support

### ISSUE THREAD

**Issue by Zi0P4tch0** [postmanlabs/postman-app-support#586]
Please add support for **Hawk Authentication**.

Details here: https://github.com/hueniverse/hawk

**Comment by ghuntley** [comment]
:shipit:

**Comment by fbaiodias** [comment]
:+1: 

Any news on this?

**Comment by lukefrake** [comment]
:+1: Merge this in pleasseeee!

**Comment by StarpTech** [comment]
+1

**Comment by benrolfe** [comment]
Has the HAWK feature been implemented yet?

**Comment by wilsonwc** [comment]
@benrolfe on my fork it has been implemented and submitted as a pull request, but you can pull it down and load it as a developer extension locally if you don't want to wait for it to be merged https://github.com/wilsonwc/POSTMan-Chrome-Extension

**Comment by JGAntunes** [comment]
:+1: This merge would be awesome!

**Comment by czardoz** [comment]
Hey everyone, we've released Hawk Auth support with the latest Chrome app (v3.2.2): https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

Thanks for your patience! It feels nice to finally release this :D

**Comment by yankeeinlondon** [comment]
Can I ask which version of Hawk you’re supporting? Is it 4.x?

**Comment by czardoz** [comment]
3.X

4.X uses ES6 features that need transpilation

**Comment by yankeeinlondon** [comment]
Ok but if in using Node 5 with Hawk 4 it should still interoperate, right?

Ken
ken@ken.net

On Sat, Feb 20, 2016 at 8:08 PM -0800, "Aniket Panse" notifications@github.com wrote:

3.X

4.X uses ES6 features that need transpilation

**Comment by czardoz** [comment]
Yes. The Postman app uses the browser though. And for Newman, we support Node v0.12+
