### ISSUE TITLE
support HTTP-signatures auth mechanism

### ISSUE THREAD

**Issue by ryancnelson** [postmanlabs/postman-app-support#588]
For API's that use HTTP-Signatures:
( http://tools.ietf.org/html/draft-cavage-http-signatures-00 )

... it would be awesome to be able to use that as a authentication mechanism, rather than just Basic: 

Specific API that i'd like to use this against is the Joyent Manta storage API: 
http://apidocs.joyent.com/manta/api.html

... it'd also be acceptible for my wishlist if there was any functionality to generate headers using an external script callout mechanism of some kind.
Which is to say, if I could generate headers with bash , i could follow this:
http://apidocs.joyent.com/manta/api.html#interacting-with-the-joyent-manta-storage-service-from-the-shell-bash

.... and then happily use POSTMan

**Comment by sdnts** [comment]
@ryancnelson Closing this as Pre-request scripts should serve your use-case. Feel free to reopen if they don't.
