### ISSUE TITLE
Optionally show unescaped output in prettified JSON view

### ISSUE THREAD

**Issue by iansltx** [postmanlabs/postman-app-support#619]
Others may want the slashes, but they get distracting when using a HAL-based API or similar. Not sure how to best implement turning this on or off in the UI (setting? another view mode to the left of Pretty? a check box near to view modes?).

**Comment by a85** [comment]
Closing this as we haven't seen traction on this request. We are working on modularizing Postman to support plug-ins using which custom renderers could be built supporting this feature and others. :)
