### ISSUE TITLE
Email Unsubscribe not protected

### ISSUE THREAD

**Issue by drexpp** [postmanlabs/postman-app-support#6211]
**Describe the bug**
You can unsubscribe people who did not want to be unsubscribed.

**To Reproduce**
1. Go to 'https://pages.getpostman.com/UnsubscribePage.html'
2. Write down some email or just make a bot who requests.

**Expected behavior**
A message indicating that you cannot unsubscribe other people but yourself.

Block that undesired people unsubscribe you to newsletters.

**Screenshots**
![img](https://i.gyazo.com/2770f1bf9021910d31630a0562ebc567.png)
![img](https://i.gyazo.com/d66c7b5400cdf49dda2e364a00618e04.png)

**Comment by shamasis** [comment]
@drexpp - security issues are best emailed to security@getpostman.com. Assuming that you will get this notification in your email and deleting the same.
