### ISSUE TITLE
Save responses inside history and collections

### ISSUE THREAD

**Issue by ncheltsov** [postmanlabs/postman-app-support#622]
Thank you for the nice extension!

I have the following issue. I stored in collections several REST calls. But they are quite dependent. I extract data from the first call and I click in the second call in the collection and populate with data from the first one.

Sadly, when I click back to the first call in the collection everything in the request body is reset to the old state and the response body is empty.

I have at least 5 REST calls in my collection and they are all dependent. I need to switch between them quite often. Every call requires data from some other. But if on every click in collection menu every REST call is reset and cleaned I need to store values in text document, populate again the calls execute them again to get the data I need. This is quire inconvenient!

Example.
Call 1 - I use login token in the request to get data for Call 2 and Call 3
Call 2 - I use data from Call 1 response
Call 1 - back to Call 1 to collect data for Call 3. But the response is lost. I try to execute Call 1 again. Sadly the token in the body is reset to some old one, when I first added the call to the collection. So I go again to retrieve the token. So double inconvenience - lost response and old token in the body.

I hope you understand what I mean.
My suggestion is to keep every call in the collection in the last state and to keep the last response, because event in history tab it is not kept and this is frustrating.

Does this sound logical?

Thanks in advance,
Nikolay Cheltsov

**Comment by aames** [comment]
Sweet tool - currently evaluating it and the lack of response history irritated me a lot. 

+1 for the option to save ALL (or at least the last response) - doing this manually from a collection is a cumbersome approach.

I'd pay extra for this feature because it's that important to me.

**Comment by chs8788** [comment]
+1 it would also help me a lot

**Comment by pkokoshnikov** [comment]
+1. It will be cool.

**Comment by jaggerwang** [comment]
+1. Is there any plan to do this? This feature is very useful, and implemented in other tools, like "DHC Rest Client", which I used before.

**Comment by bohdaq** [comment]
+1

**Comment by a85** [comment]
Saving responses inside collections is possible already. Saving responses in history is on our roadmap.

**Comment by bohdaq** [comment]
@a85 awesome

**Comment by prashantbhate** [comment]
+1
This would be a very useful feature.
With this one can add assertions/tests quickly before a re-running collection.

**Comment by silviucotilici** [comment]
+1
This would be a very useful feature.

**Comment by CodeInDreams** [comment]
+1

**Comment by zlatkoc** [comment]
+1

**Comment by silviucotilici** [comment]
+1

**Comment by davobutt** [comment]
+1

**Comment by Dekorg** [comment]
+1, afterall fiddler does it ...
but I guess it is related to https://github.com/postmanlabs/postman-app-support/issues/146

**Comment by fipppi** [comment]
+1

**Comment by a85** [comment]
Everyone: this is going to be out in 6.5 soon releasing over the next 2 weeks!

**Comment by kamalaknn** [comment]
Hey everyone,

This feature is now available for early access on our canary channel - [link to download](https://www.getpostman.com/canary).

Do try it out and let us know. We would appreciate feedback on this.

**Comment by a85** [comment]
This feature is out in production now with 6.5+

**Comment by SpaceRoger777** [comment]
is this feature still available on postman? I cant find any way to automatically save response on the app
