### ISSUE TITLE
Feature Request: Create POSTMAN collection from listening to Chrome API calls

### ISSUE THREAD

**Issue by intellix** [postmanlabs/postman-app-support#630]
So I have a site using an API that I'd like to run tests with POSTMAN. The thing is I need to manually create each individual request (create a CRUD per resource).

Using Postman interceptor I think it would be awesome if you could automatically create a POSTMAN Collection by listening to the requests to a particular URL on a Chrome tab.
So I would go through the site, use it and POSTMAN would add each of the API calls to a collection along with the headers and parameters sent.

This would make business sense for POSTMAN because it makes it easier for developers to integrate with it.

**Comment by a85** [comment]
Workaround available through Proxy and Interceptor. The Interceptor will be out soon for the desktop apps.
