### ISSUE TITLE
Feature Request: Support Oauth2.0 Hmac without callback requirement

### ISSUE THREAD

**Issue by bfosberry** [postmanlabs/postman-app-support#632]

**Comment by czardoz** [comment]
This involves directly accepting the user's credentials to fetch the access token from a server: https://tools.ietf.org/html/rfc6749#section-4.3

**Comment by vikiCoder** [comment]
The latest version of Postman native app (v7.3.4) has support for `password` grant type in OAuth2. Below is a screenshot showing the same:

<img width="619" alt="Screenshot 2019-07-30 at 12 25 05 PM" src="https://user-images.githubusercontent.com/16588032/62107604-9505d680-b2c5-11e9-9161-a2142eb16ab1.png">
