### ISSUE TITLE
OAuth 1.0 signature changing with encode method

### ISSUE THREAD

**Issue by oravecz** [postmanlabs/postman-app-support#642]
I have verified that the OAuth 1.0 HMAC-SHA1 signature is correct when I specify my parameters use form-data encoding. However, one is supposed to use x-www-form-urlencoded encoding according to the specification. When I change to this, the signature changes for some reason, and the request fails.

Why does the signature change when the parameters remain the same and only the encoding changes?

**Comment by abhijitkane** [comment]
@SulivanDotEu @andrew-hochstetler-blackboard Are you still facing this issue with the latest version of the app?
