### ISSUE TITLE
OAuth2 Code Flow - Doesnt work due to Postman not authenticating 

### ISSUE THREAD

**Issue by dendle** [postmanlabs/postman-app-support#650]
Hello All,

I love postman, and the JetPacks stuff - all great! Thank you!

However, I cannot get my Postman client working with OAuth2.

I have traced the problem to the fact that Postman does not appear to be authenticating as a client when trying to exchange the code for an access token at the token endpoint.

Is this supposed to happen?

Postman asks for a ClientID and the ClientSecret - these are supposed to be used as the clients credentials aren't they?

I have read other issues regaring this problem, but they appear to be due to using localhost (which is unsupported) or there is mention of the AuthorisationServer not being compliant with the spec.

Looking at the spec (http://tools.ietf.org/html/rfc6749) it appears as though postman should be attempting to authenticate when obtaining the token (see 3.2.1.  Client Authentication)

Am I missing something?

Cheers All,
Matt

**Comment by gregory-chapman** [comment]
The spec says also: 

```
"Including the client credentials in the request-body using the two
   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
   to directly utilize the HTTP Basic authentication scheme"
```

According to @a85 the implementation of OAuth2 in Postman was to suit big company implementations: https://github.com/postmanlabs/postman-app-support/issues/1614#issuecomment-165597128

I'm not sure why they went off spec but it is prevalent in the web:
http://oauthbible.com/#oauth-2-three-legged
https://aaronparecki.com/2012/07/29/2/oauth2-simplified

It would be nice if Postman had an option to specify which version of client details would be used.

**Comment by abhijitkane** [comment]
@gregory-chapman Are you still seeing this with the latest version of the app?

**Comment by dendle** [comment]
Its working fine for me now :)
