### ISSUE TITLE
Using cookie data

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/postman-app-support#664]
Justin Hooks • 20 hours ago
------
I’ve been using Postman and Newman to great success recently,
but have come upon a big stumbling block. I'm on a software QA team in Houston,
Texas, and I really need to set a website session ID, stored in a cookie, as an
environment variable for a collection of GET requests I'm working with. I’ve
downloaded the Interceptor plugin and I thought it would accomplish what I
need, but I’m having some difficulty. I need the environment variable from the
cookie to be used in my Postman Auth headers when I run the collection. Is it
possible to capture the session ID from the cookie like this? I'd appreciate
any help. thanks!

**Comment by mverma-va** [comment]
Can someone please update the best solution here??

**Comment by abhijitkane** [comment]
@ejohnson-spritz @mverma-va With the Interceptor on, you should have access to the cookies in the test script - postman.getResponseCookie(cookieName). Check https://www.getpostman.com/docs/jetpacks_sandbox and http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/.
