### ISSUE TITLE
wrong bigint values parsed in Test editor

### ISSUE THREAD

**Issue by iyagi15** [postmanlabs/postman-app-support#666]
![postman1](https://cloud.githubusercontent.com/assets/5225958/3761542/a23ab7fa-188b-11e4-948f-633af4f8922c.PNG)

![postman2](https://cloud.githubusercontent.com/assets/5225958/3761543/a23d9984-188b-11e4-987d-ab3a70c54e79.PNG)

![postman3](https://cloud.githubusercontent.com/assets/5225958/3761541/a23a30aa-188b-11e4-95bb-c294697dbee4.PNG)

**Comment by anyone-can-test** [comment]
Is this issue fixed?
