### ISSUE TITLE
Proxy installation description isn't complete.

### ISSUE THREAD

**Issue by ToastedJelly** [postmanlabs/postman-app-support#672]
I'm on Vista 64bit.

I follwed http://github.com/a85/POSTMan-Chrome-Extension/wiki/Postman-Proxy, but I got an error on start

I might have done too many steps, to fix the problem, but a more experienced python dev probably sees what the problem was.

I had to manually install easy_setup, zope.interface, Pillow

and replace the line "from ImageFile import Parser" with "from PIL.ImageFile import Parser"

**Comment by tmack8001** [comment]
I'm running into this same problem myself, but even more than that I can't "enable" the proxy/interceptor in the UI either

**Comment by abhijitkane** [comment]
@tmack8001 What do you see when you try to enable the Interceptor? You'll need to install the Interceptor from https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en if you're using the main Postman application before you enable it.

**Comment by tmack8001** [comment]
@abhijitkane I'm using the Mac Client (ver 0.0.4) and also have the chrome extension installed as well (though not sure if those relate to each other). But when I click to enable the interceptor I get "Proxy Settings", but upon clicking that to set it up I don't get anything.

**Comment by abhijitkane** [comment]
@tmack8001 For the mac app, the Interceptor isn't required. Once the proxy says 'Connected', you can set your local proxy to localhost:5050 (or whatever port number you entered), and requests should start streaming in to the history. There might be some issues with https sites, though.

**Comment by tmack8001** [comment]
Yeah I figured the Interceptor wasn't required based on my conversations with the development team. Though my application upon clicking on "Proxy Settings" or the proxy icon I never get a 'Connected' message or even a way to set the proxy configurations. Thus my issues ATM.

**Comment by a85** [comment]
The proxy has been deprecated. Postman's native apps have an in-built proxy now: https://www.getpostman.com/docs/capture_native
