### ISSUE TITLE
Rearrange folders

### ISSUE THREAD

**Issue by dudo** [postmanlabs/postman-app-support#682]
You can drag and drop `requests` around... any plans for allowing drag and drop organization of `folders`? Can I manually edit the json?

**Comment by joanrodriguez** [comment]
+1

**Comment by sunshineo** [comment]
+1

**Comment by kevinjalbert** [comment]
+1

**Comment by mryhmln** [comment]
+1

**Comment by scottalanweber** [comment]
+1

**Comment by jonners99** [comment]
+1

**Comment by kajo123** [comment]
+1 Any update on if/when this might appear? Would love this - would be so helpful! :)

**Comment by iivannov** [comment]
+1

**Comment by srbangre** [comment]
+1. 
when is it going to be implemented? this is the basic feature.

**Comment by oldboyxx** [comment]
+1
I'm building a restful api and really missing reorder :disappointed: 

Otherwise an awesome product :+1:

**Comment by ghost** [comment]
+1

**Comment by randomInteger** [comment]
I just want to say that I love Postman and I'm using it (happily) for rest api test automation, and having the ability to reorder folders in a collection (specifically so the folder order can drive test run order in the Runner) is something that would make my life a lot easier.  I tried manually reordering the collection JSON but that did not reflect in the order when I re-imported that collection.

Postman devs:  Your tool is amazing and I know you are probably swamped, but this is one of those "little things" that would make a huge difference for this product as a test automation tool. 

Thanks!

**Comment by cosbor11** [comment]
+1

**Comment by joelfogue** [comment]
I found a temporary fix for this while the Postman team implements this much needed feature.
I noticed that the folders order themselves alpha-numerically so just append a 0,1,2,3 to the beginning of your folders or rename them alphabetically, a,b,c,d like below: 

Numerically: 
0-firstFolder; 1-secondFolder; 2-thirdFolder 

OR alphabetically: 
a-firstFolder; b-secondFolder; c-thirdFolder

This should force the order on your collection folders for now; hope that helps someone

**Comment by midrissi** [comment]
👍

**Comment by udaraliyanage** [comment]
+1 for this feature

**Comment by Topener** [comment]
Oh wow, still not there? I needed to re-order because my first call needs to be an authorization. Guess I'll go with the numeric-hack

**Comment by jamesdraper5** [comment]
+1 for this

**Comment by gwongz** [comment]
+1

**Comment by Hetkoekje** [comment]
+1

**Comment by fuadhamidan** [comment]
+1

**Comment by sffetlio** [comment]
This feature is required for automated testing. The numeric-naming workaround is not a solution.

**Comment by sdnts** [comment]
This is in the works, I'll update you guys here when we have an ETA.

**Comment by tomkerswill** [comment]
Wow, can't believe this isn't in! It wouldn't be an issue, but the collection runner uses this order to decide what order to execute in, so it is really vital

**Comment by xmeng1** [comment]
I think, currently, we can only use the name to order the folder...  :)

**Comment by tmack8001** [comment]
Would really like this to become a thing.

**Comment by hsteele-sonovate** [comment]
Throwing my support in for being able to order folders without having to change the name. Given the fact that the test-runner enforces execution by order, being able to set that order without workarounds is essential.

**Comment by m-philipp** [comment]
+1

**Comment by hughescr** [comment]
+1

**Comment by dyihoon90** [comment]
+1

**Comment by Gyunikuchan** [comment]
+1

**Comment by RatanShreshtha** [comment]
+1

**Comment by wscherfel** [comment]
+1

**Comment by simonwilbert** [comment]
+1. numerical pre-fixing is not a maintainable solution. considering switching to SOAPUI purely because of this issue which would be sad

**Comment by asidarovich** [comment]
+1

**Comment by mikhail-amurov** [comment]
+1

**Comment by sureshdollu** [comment]
+1

**Comment by Topener** [comment]
Can everyone stop doing `+1` on this ticket and just Thumbs-up the ticket instead?

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by StephenOTT** [comment]
+1

**Comment by sudharsan81** [comment]
+1

**Comment by rkraneis** [comment]
+1

**Comment by Dahlhaus** [comment]
+1

**Comment by prashantbhate** [comment]
+1

**Comment by KeynesYouDigIt** [comment]
+1 let us know when it ships, its holding up a process of ours

**Comment by katzbo** [comment]
+1

**Comment by danbrotherston** [comment]
+1

**Comment by a85** [comment]
The feature is out in 5.1! Get it here: www.getpostman.com/apps

**Comment by jasekiw** [comment]
Rearranging and publishing docs seems to be broken. One of my folders is stuck inside another in docs even though I moved it back to the top level.

**Comment by SamvelRaja** [comment]
@jasekiw can you provide me the app version you are in? If you are in 5.1.2 (the latest version) can you send us a email to help[at]getpostman.com from your registered email address.

**Comment by jasekiw** [comment]
Version 5.1.2. 

It is weird After moving the folder around multiple times I was able to get the docs to follow but it was definitely bugging out there for a little bit. If I run into it again I will send an email but I do want people to be aware that can happen.

**Comment by KeynesYouDigIt** [comment]
I am now working with multi level folders (thanks!!) but cannot reorder tests by anything but created date. Is there any way to resequence tests in a way that is obvious to my whole team? (ie, without using NextRequest())

**Comment by KeynesYouDigIt** [comment]
Anyone around? I can reorder tests in the gui if I move them really quickly.... but if I hold on for around 1 second the tests jump out of the folder into the parent folder instead of reordering as needed, is this the intended functionality?

update - This was occurring for first level folders in a collection, but click and drag reordering seems to be working OK for sub folders

**Comment by elementsrtyte** [comment]
To people having issues with the new dragging requests into folders, try deleting your folder and recreating.  Worked for me as a temp fix.
