### ISSUE TITLE
Management of collections - usability issues

### ISSUE THREAD

**Issue by wabiloo** [postmanlabs/postman-app-support#689]
I work across 3 computers on a regular basis: 1 at home, 1 for travels, 1 in the office.
I need to be able to synchronise my collections to ensure that wherever I work has the latest one.
I was under the impression that there was a way to "auto-synchronise" my collections. Clearly there isn't.  So, here's the feature request:
1) add an auto-upload/download (=auto-synchronisation) to collections
2) if not, put a visual indicator on collections that have been modified since last time they were downloaded, to remind me to upload them before I move to another computer.

**Comment by aditikul** [comment]
Hi,

The latest version of the app allows you to sync your collections for free as long as you are signed in to your Postman account. In the free version you can upload a collection and access the shared collection through collection links. The paid Postman cloud plan allows collections to be synced across the teams API Library. 

Thanks.
