### ISSUE TITLE
Share common API definition across several collections

### ISSUE THREAD

**Issue by AlexMoffat** [postmanlabs/postman-app-support#704]
If I have an API definition for a call that is common to several test use cases I'd like to be able to include a single definition of the call in multiple collections so that if I need to make changes I only have to do it in one place. "Add to Collection" creates a copy of the API, I'd like something like "Add reference to Collection". 

Thanks

**Comment by ebelanger** [comment]
+1 this feature.  From my understanding, it would allow the creation of collections of commonly used requests that would be called inside other collections that act like scenarios.  Instead of duplicating the common cases in each scenario, you would only have to point to an already defined one.

**Comment by a85** [comment]
We will be handling this through composition/schema support in Postman. There are no plans to support inheritance/templating models for reusability at a global level. They will exist at a collection level though.
