### ISSUE TITLE
Postman does not send any requests [bug]

### ISSUE THREAD

**Issue by lawrence-dol** [postmanlabs/postman-app-support#712]
Having not used Postman for about 6 months, I found yesterday that it no longer sends requests. I have a number of environments and API collections set up, which where all working last time I used them, and none of them do anything at all when I click "Send".

I tried resetting all experiment flags back to default, though there were none set that I could see.

I am on:

    Windows 7, 64 bit
    Chrome Version 37.0.2062.103 m
    Postman Version 0.10.4.3 (packaged)
    Postman OS: win
    Postman Architecture: x86-32
    Postman Native client architecture: x86-64

**Comment by cornelius-dol** [comment]
No, that was the first thing I checked. It's almost as if nothing's registered for click events on the button. I don't suppose Chrome has anyway to log UI events?

**Comment by cornelius-dol** [comment]
Same thing; though it failed attempting to import an existing collection -- It installed as a separate app and loaded none of my environments or collections. I just tried a simple `http://localhost/api/test` URL and clicked `Send` and nothing at all happens.

```
Initialized theme settings requester.js:17078
Initialized ThemeManager requester.js:18190
Open latest DB requester.js:15416
Upgrade DB requester.js:15341
window.onbeforeunload is not available in packaged apps.
Initialize interceptor requester.js:688
```

**Comment by cornelius-dol** [comment]
> 1. Are your collections loaded inside Postman?

With the current version yes; with the new version you had me try, no.

> 1. Does the state of the "Send" button change?

Yes; it goes a darker blue with a depressed look.

> 1. Do any of the modal windows show up? (For ex. on creating a new collection)

As far as I can tell all UI elements function as expected, including all popups, tabs and folding lists. Likewise I can find no broken function except sending a request.

It's very strange; I don't use Chrome as my primary browser, pretty much only for Postman and cross-checking functionality of web apps, so it's a almost vanilla install with few extensions and I've tried disabling all extensions except Postman.

**Comment by cornelius-dol** [comment]
I have no proxy set up; never have. Double checked just in case something was amiss there. It doesn't make any difference where I send the request, whether locahost, VPN or WAN.

**Comment by cornelius-dol** [comment]
I'm not comfortable with allowing unknown persons access to my computer. I don't mind installing canary as long as it can be done side-by-side with the stable version and cleanly removed when we get to the bottom of this.

**Comment by robob4him** [comment]
I am also having this issue, though I'm not going to erase all my sync data.

One thing to note, though, is that `$('submit-request').click(function () { pm.request.send("text"); }` (rebinding the event) returns functionality to the button. Most components which would presumably have a listener do not function normally. For instance, when changing the target url to something different the request is still made for the original url, not the new one.

Is there possibly a race condition in which some of the UI has not fully loaded before pm attempts binding events?

**Comment by abhijitkane** [comment]
That's weird - all the event handlers are attached inside a $(document).ready().

Does this issue occur every time you open the app, or is it intermittent?

**Comment by robob4him** [comment]
Every time. And with a bit more research I see that pm.request's areListenersAdded attribute is false.

There is a large difference between master and the extension version. What tag correlates to extension version 1.0.3? I can do more digging knowing the un-minified version of the code. 

There looks to be a lot of work to make modules out of components; when will a new extension version be out which includes these changes? They look like they would greatly simplify debugging.

**Comment by abhijitkane** [comment]
The current packaged app (v1.0.3) is not open source. The repository
corresponds to the in-Chrome extension (which is at version 0.9). It's
really only used as a bug tracker.

Are there any other errors you see in the console?

**Comment by robob4him** [comment]
Fascinating. I also have the in-Chrome extension which has always worked just fine.

The console is clean except for some debugging messages:

> Initialized ThemeManager
> Open latest DB
> window.onbeforeunload is not available in packaged apps. (emitted by Chrome for jQuery)
> Checking for update notifications...
> Initialize interceptor
> ThemeSettingsTab: Purchase is not available
> Stored version: 1.0.3, currentVersion: 1.0.3
> Pretty codemirror not found
> Add tooltips

In contrast, "Preview", "Add to collection", and "Reset" all work as expected.

Previously I had reset browser settings and uninstalled/reinstalled the extension to no avail. Are there no additional debugging helps for more information?

**Comment by bahamut1221** [comment]
I also have the problem.

It's really disturbing to have the apps not working and the in-chrome working without problem :(

**Comment by abhijitkane** [comment]
@bahamut1221 , @robob4him
Can you enable the console (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/), and check what this statement returns - 
`$._data(document.getElementById("submit-request"), "events" ).click[0].handler`

**Comment by robob4him** [comment]
function (){c.trigger("send","text")}

**Comment by abhijitkane** [comment]
If the event handler is registered, I'm not sure why it's not firing.
@a85 any thoughts?

**Comment by NielsRak** [comment]
Same problem here, @robob4him 's rebinding fix works too (yay!). Don't know if it's relevant, but I got this error on restart:

![image](https://cloud.githubusercontent.com/assets/10673501/5879060/e3cd051a-a323-11e4-8995-05c6757b5c5b.png)

**Comment by abhijitkane** [comment]
What version are you on? In v1.0.5, we pushed a change that reattaches the 'send request' listener after a while. Do you a see a "Submit request event handler already registered" message in the log?

**Comment by NielsRak** [comment]
1.0.6, says Extensions page. Yes, I do get that 'already registered' message.

**Comment by abhijitkane** [comment]
Weird. We'll work on this and keep you posted.

**Comment by NielsRak** [comment]
Thanks, and good luck. Yell if you want any info. Great app otherwise!

**Comment by abhijitkane** [comment]
Do you have any other error messages in your console? Check the console after you press 'Send' and nothing happens.

**Comment by NielsRak** [comment]
AFK until Monday now, but quite sure there is nothing logged in the console.

Will double check next week.

Niels.

On 23 Jan 2015 18:23, Abhijit Kane <notifications@github.com> wrote:
Do you have any other error messages in your console? Check the console after you press 'Send' and nothing happens.

---

**Comment by lawrence-dol** [comment]
Why has this not be reopened?

**Comment by NielsRak** [comment]
Without the fix Send puts nothing to the console. Below's the full console from launch, select request, and mash Send a few times.

Not sure how the 'Stored version' message is working - browser reckons I'm on 1.7 now, I'll try a relaunch in case it was updated in the meantime. Will update this thread if I see any different behaviour.

![image](https://cloud.githubusercontent.com/assets/10673501/5898079/9785ecae-a543-11e4-97bf-fda1917c1afc.png)

**Comment by IanDominey** [comment]
I'm getting the same problem.  Here is the error that appears when the app loads:

![screenshot 2015-02-10 14 22 53](https://cloud.githubusercontent.com/assets/4990954/6128750/89c1af10-b130-11e4-9f48-c8233c6a5935.png)

**Comment by abhijitkane** [comment]
@IanDominey Is the interceptor on?

The onbeforeunload error is unrelated. If there are no errors in the console after you hit 'Send', I'm not sure why this is happening.

@shamasis

**Comment by IanDominey** [comment]
The interceptor was on.  I turned it off but it didn't seem to make any difference (except a chunk of those errors disappeared).

I have taken a screen recording which you can view here: 
![bug](https://cloud.githubusercontent.com/assets/4990954/6129710/516e37e8-b138-11e4-8095-485c11e42cc6.gif)

**Comment by IanDominey** [comment]
Solved!  On a hunch, I checked my Chrome settings.  I'd forgotten that I had set the Javascript settings to  "Do not allow any site to run JavaScript".  Changing that setting solved the problem.

![screenshot](https://cloud.githubusercontent.com/assets/4990954/6313402/4c7dfe92-b9a0-11e4-83cb-d682c37beece.png)

The question is, if I want to disable JavaScript for untrusted sites, what exception do I need to add for the packaged app to run?

**Comment by robob4him** [comment]
Wow. That does it. It can be closed from my perspective.

Note that you can also just set an exception for "chrome-extension://*/" to permit all extensions.

Thanks guys for the work. Hate to have had it be so simple of a fix.

**Comment by IanDominey** [comment]
I think it would be a good idea to update the README before closing this not-actually-a-bug bug.

**Comment by abhijitkane** [comment]
Still not completely sure that this is the only cause of the issue. Faced this on Chromium sometime back, when Javascript wasn't disabled.

**Comment by NielsRak** [comment]
Works for me too. Thanks @IanDominey!

**Comment by fracture-point** [comment]
FYI the syntax here has changed.  I am running Version 48.0.2564.109 (64-bit) on OSX 10.11.3 and the exception needs to be formatted as....
chrome-extension://postman_extension_id/
...or else it will not work (notice extension is singular)

I also left this comment on the commit.

This all-together was a waste of about 3 hours of frustration just to get the extension to work.  I highly, highly recommend adding a check on the app homescreen for java...if it's not enabled, let the user know what they need to do.  Silent failure is the worst to troubleshoot.

**Comment by cornelius-dol** [comment]
@fracture-point : It's kind of ridiculous for Chrome to require exceptions for running scripts in extensions that you've approved on install. However, this doesn't seem to be the case anymore, as I don't have an exception for the above URI and mine is working fine.

**Comment by fracture-point** [comment]
@lawrence-dol I definitely agree that JS should be implicitly allowed on installed extensions.  Not sure what you mean though by "you don't have an exception for the URI"?  

This is an issue in my case (and I assume with most others) because I have javascript disabled by default.  All sites need to be manually java-approved to run client-side java.

**Comment by cornelius-dol** [comment]
@fracture-point : I meant that I have JavaScript disabled for all sites and don't have an exception, as described above, to allow JavaScript to run but Postman is working just fine for me. So I thought the issue that caused this has been fixed in Chrome.

But I was in fact wrong; I have an exception for all extensions, though I'm not sure if I added it myself... in fact, I quite sure I didn't.

```
chrome-extension://*/              Allow
```

**Comment by a85** [comment]
Closing this issue. Haven't seen any reports where Postman is not sending requests.

**Comment by stupid-genius** [comment]
@abhijitkane I am also seeing this in Chromium (45) even with the JS exception added.

**Comment by samupl** [comment]
I'm also experiencing this on 51.0.2704.106 on Fedora. I don't have, however, any errors in the developers console. The last message I have in the console window is 'watchdog checking connection health', the request then hangs indefinitely and the request never hits my application.

**Comment by samupl** [comment]
Postman info:

```
4.4.1
linux / x86-64
Chrome 51.0.2704.106
```

**Comment by abhijitkane** [comment]
@samupl Is this for all URLs? Can you try making a GET request to echo.getpostman.com/get ?

**Comment by samupl** [comment]
@abhijitkane For all URLS, my local ones and echo.getpostman.com.

**Comment by GeeWizWow** [comment]
Had this same issue. Turns out interceptor was enabled but the chrome extension was not installed. Hope this helps others

**Comment by anandbibek** [comment]
> Had this same issue. Turns out interceptor was enabled but the chrome extension was not installed. Hope this helps others

**Comment by adnan-i** [comment]
Worked for me after removing and installing postman again.
