### ISSUE TITLE
Option to autosave all HTTP request/responses to a collection

### ISSUE THREAD

**Issue by sudheendrach** [postmanlabs/postman-app-support#717]
Option to auto save all captured requests (like Postman interceptor) to a Postman's collection. Something like this chrome extension - https://chrome.google.com/webstore/detail/http-trace-capture/mepoamdlmipfblemapenfhkpdeklfoin?hl=en

**Comment by dkordik** [comment]
Looks like Postman currently lets you save individual History items from Interceptor to a collection... but it would be awesome if I could just save my entire History to a collection in one shot! Then all I'd have to do is get my Postman Interceptor mask right, and I could browse around my site and generate a nice API map.

**Comment by abhijitkane** [comment]
Postman's native apps (https://www.getpostman.com/apps) allow you to configure a proxy, and save all captured requests to a collection. 

Docs: https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests
