### ISSUE TITLE
Show count of matches in "Find"

### ISSUE THREAD

**Issue by dorth** [postmanlabs/postman-app-support#718]
The old version of Postman (apparently) used Chrome's built in "Find" which allowed type-down (nice) and also showed the number of matches (critical).  So when I query my Cloud vender to look at the number of instances I'm easily able to search for "name:" and find that I have 438 instances.  However, the new version of Postman no longer shows a count of matches.  This is a really critical piece of functionality when dealing with large json responses and has blocked us from migrating to the new version.

**Comment by HonzaMac** [comment]
How it's going? I really appreciate this feature!

**Comment by a85** [comment]
Postman now uses AceEditor's "Find" features. We might augment this with search counts but should work pretty well for now.

**Comment by abhijitkane** [comment]
Added in the latest versions.

**Comment by dorth** [comment]
Wow, a long time coming, but much appreciated!
