### ISSUE TITLE
Allow remotely loaded json schemas

### ISSUE THREAD

**Issue by jimthedev** [postmanlabs/postman-app-support#719]
EDIT: Please ignore this post. See my next post instead.  As it turns out, implementing remote schema loading by any means in the current version of POSTman is impossible. There will need to be some changes which I describe below in order for tv4 users to load remote schemas.

First off, love the extension and jetpacks. 

As far as I know, there is currently no way with tv4 inside of POSTman to refer to json-schemas defined outside of the current test editor.  To circumvent this, it would be useful to be able to host my schema on a remote server (for example: http://schema.mydomain.com).  I have a pretty large api so manually loading all of my schemas every single test editor is repetitive.  The following script actually lets us to accomplish this: 

https://gist.github.com/geraintluff/30f838e68ad1d3e4a591

It uses jQuery's getJSON to load the schema, then uses addSchema to actually add the schemas to the tv4 instance. Currently I have to copy it into each of my test editors. It would be really useful it this was bundled into postman to allow for remote loading of json schemas.

**Comment by petalvlad** [comment]
Are there any news regarding this issue?

**Comment by sjapps** [comment]
Any updates on this?

**Comment by buehler** [comment]
I'd :+1: this :) I'm currently writing tests for an API we developed and it would be an awesome feature to use remotely hosted json schematas

**Comment by krutkowski86** [comment]
@buehler @SJApps @jimthedev @abhijitkane @petalvlad 
It's possible to use remote schema. Just make your schema available to get from your API then send a request for it (which should be your first step before other requests) and save responseBody to postman global variables 

postman.setGlobalVariable("schema", responseBody);

Afterwards if you would like to use it in postman tests
var schema = JSON.parse(postman.getGlobalVariable("schema"));

**Comment by shamasis** [comment]
For remote schema, what @irhabi suggested seems the best way to go. Nevertheless, we are also looking into scope of bundling local schemas with Collection itself. It is though a long-term prospect.

**Comment by O11o1** [comment]
thank you, @irhabi, that solution is pretty useful for an API I'm working on. It would be nice to be able to read in JSON Schemas from a file, but for now being able to plug it into the test script of an initial "setup" test should be sufficient for now. It's better than copying it all over the place, at any rate!

**Comment by laduran** [comment]
What is the current state of this on Postman Desktop v5.0? I am calling the tv4 API getSchema('http://localhost:63423/availableservicesresponse.json'); on a remote JSON URL and it is not working for me.

I can retrieve the JSON file representing my schema from the shown URL fine. However calling the getSchema API above in the Postman API test context does not work. I get a null object back every time. I'm not sure if this is a limitation of the Sandbox environment but it does make schema validation more difficult.

**Comment by a85** [comment]
The workaround mentioned in this thread should help making remotely loaded JSON schemas possible. Postman will have first-class support for schemas in general in the coming versions soon. Closing this ticket for now.
