### ISSUE TITLE
API Directory TLC

### ISSUE THREAD

**Issue by matt-usurp** [postmanlabs/postman-app-support#720]
The API Directory is looking really dead and could be a really powerful tool, but lacks all the functionality to make it usable. Imagine how nice it would be if you have to implement this well known providers API and you could just go to the API Directory and find the example requests to play with. I have this case today where I am probably going to be creating a collection for a popular UK shipping provider and would love to share this although I know that its going to get lost in the murky depths that is the current API Directory ..

So could the following functionality be looked at; (_I have marked the more important entries in bold_)
- **Search**
- **Better Pagination**
- Categories (for enhanced searching, e.g "shipping" or "blog")
- Country origin (essentially filtering out foreign API although not seen this issue yet)
- Sorting (popularity/downloads, endpoints or alphabetical)
- **List view** (instead of boxes as its not easy to read the flow)

The bold entries I think would be a great first step to getting this feature usable and off the ground!

Should I find the time I would try implementing most of this functionality as a PR, but would like the know the initial ideas and concepts for this area.

**Comment by Jeff-Lewis** [comment]
Is the Public API Directory gone in v2.0? I'm having trouble find a link to it...

**Comment by abhijitkane** [comment]
We're revamping the API directory, and have taken it down for now. Without a search feature, it wasn't very helpful.

**Comment by itajaja** [comment]
Is it possible to know when you are putting the new version of the API directory back up? I think it's a killer feature for postman!

**Comment by vasujain** [comment]
Is it going to come back soon ?

**Comment by aminemat** [comment]
Any updates on this ?

**Comment by vasujain** [comment]
@a85 @abhijitkane

**Comment by a85** [comment]
We don't have a full fledged directory yet but we have introduced a "Run in Postman" button and we are listing down companies who offer public APIs. https://www.getpostman.com/integrations/run-button

If you are interested in being listed there, let us know here!

**Comment by vasujain** [comment]
@a85 One of our team is working on it. Will contact you once we are done with the integration. :)

**Comment by a85** [comment]
The API Network is rolling out with 5.5. More details to follow soon in a press release.

![screenshot 2017-12-06 15 52 44](https://user-images.githubusercontent.com/653409/33816329-1eed8d36-de5e-11e7-834b-02a08d359a2b.png)
