### ISSUE TITLE
Check for Empty responseBody

### ISSUE THREAD

**Issue by asanghi** [postmanlabs/postman-app-support#723]
How do I test for empty responseBody in tests? I have a HEAD 200 response that I want to validate for. In addition to ensuring that the status code is 200, i also want to validate that the body is empty.

**Comment by rajpushpa1** [comment]
if response body is empty it will give response.getBody() '{}' how to check it, if you do responseBody.length==0 if give 2 length and its not an empty string also.

**Comment by pareshsji** [comment]
Try checking this:

pm.test("Check JSON  Response body is empty", function() {
    var jsonData = JSON.parse(responseBody)
    pm.expect(jsonData.lenght).to.eql(undefined)      
})

**Comment by ramchandravgr** [comment]
@pareshsji , instead of undefined,  '0' is giving correct result

pm.test("Check JSON Response body is empty", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData.length).to.eql(0);
});

**Comment by teampurpledev** [comment]
If it replies with an empty array or object use the above solutions, but if there is _no_ body returned, use: 

```
pm.test("There is no response body", function () {
    var res = (_.isEmpty(responseBody));
    pm.expect(res).to.be.true
})

```

**Comment by kuzmaka** [comment]
For response without body better use 
```
pm.test("response should be empty", function () {
    pm.response.to.not.be.withBody;
});
```
