### ISSUE TITLE
Nested structures in JSON data file

### ISSUE THREAD

**Issue by xtalker** [postmanlabs/postman-app-support#727]
When testing APIs that use more complex data schemas, it would be a very useful if the JSON data file supported nested data structures.  The work around for this is to give each variable a unique name which quickly become very cumbersome on larger data structures.

**Comment by a85** [comment]
@xtalker Right now we are limited to key/value pairs. Our app needs some refactoring to enable this but we'll have it on our roadmap.

**Comment by bennetone** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by veglos** [comment]
Any plans yet for this feature?

**Comment by RichardForshaw** [comment]
+1

This would be ideal, or some doco on being able to serialize a JSON structure as one of the key-value values.

**Comment by postema** [comment]
on the roadmap at oct2015 and still no solution???

**Comment by slavenantic** [comment]
Any news regarding this?

**Comment by cactail** [comment]
Is there any news regarding this?

**Comment by a85** [comment]
You can now render your own custom response for the specific data format that you are working with. We will continue supporting the most popular data formats as first-class citizens but for other formats the Visualizer will help: https://learning.getpostman.com/docs/postman/sending-api-requests/visualizer/. The docs talk about rendering charts/graphs but you can use the same process for rendering data like the way the pretty editor in Postman works.
