### ISSUE TITLE
Environment variable scopes

### ISSUE THREAD

**Issue by jkleckner** [postmanlabs/postman-app-support#729]
Please consider scopes for environment variables.

Imagine it works the following way by example:
- When you first begin, all you have is an empty "Global Scope"
- I can add multiple sets of variables within the global scope and select among them.  Only one set is active at a time.
- I can then "add scope" which is to the left of the pre-existing "Global Scope" and give it a name say, "Web Server".
- Again, I can add multiple sets of variables to "Web Server", say ("local", "dev", "prod") and select one of them to be in force.
- The variables in Web Server dominate over any corresponding in "Global Scope" which fills in missing ones if it has them.
- I can then add another scope which is to the left of the pre-existing "Web Server" and give it a name say, "Database Server".
- Again, I can add multiple sets of variables to "Database Server", say ("local", "dev", "prod") and select one of them to be in force.

In this way, I can organize my variables by services along dimensions of stack name (configuration axes).  For example, I can mix and match a dev database with a local web server and production authentication service.

**Comment by drgrieve** [comment]
I also am wanting this feature, so it it easier to switch between local, dev and staging (usually all the same except url) and production for all my projects. Currently I need to create 4 environments for each project and I work on 10+ projects. Would be nice to consolidate this.

**Comment by Aidenir** [comment]
Just cheking in on this issue, is it still being worked on?

**Comment by abhijitkane** [comment]
@Aidenir Not directly, but we're working on a new collection format which should help with this use-case to a certain extent.

**Comment by Aidenir** [comment]
@abhijitkane ok cool. Is there any rough ETA for this? are we talking weeks, months, years?

**Comment by jkleckner** [comment]
@abhijitkane Would you describe the new collection format?  Does it solve the use case in a different way?  Similar to @drgrieve, I have a huge number of environments.

Often, I just give up and grab a route and paste over the variable with a specific value from a log which effectively bypasses the value provided by environments.

Or I dump everything into the global scope and manually add/remove a suffix to switch between variants.

Re-reading the original description makes me long for it...

**Comment by shamasis** [comment]
The new format makes a number of things extensible and repeatable. It makes your original use case of making readable collections a reality. The idea of environments becoming a two dimensional stack is not directly part of the format, but the new format does add another layer of variables within the collection itself and that can lead to many innovative use cases. 

http://blog.getpostman.com/2015/06/05/travelogue-of-postman-collection-format-v2/

We would begin by chiselling out the rough edges of this format and internally start modelling our complements around it before moving to export import in this format.

**Comment by jkleckner** [comment]
@shamasis, thank you for the link.  It is hard to know from the presentation how environment variables would work.

They appear to be moved into the collection itself which, if true, would be a retreat from the current 2-level scoping of global/local.  My suggestion above is basically asking for more than 2 levels of scope or sets of related variables that can be selected together.

There is a statement in the presentation slide 33: "These variables can be re-used throughout the collection.  They are scoped around the requests of its sibling item and downward."

I don't understand the meaning of this and if or how I can select multiple sets of variables.

**Comment by a85** [comment]
Collection variables are available now in Postman to provide one more level. We will look at the need for additional scopes in the future. For now I am closing this issue.
