### ISSUE TITLE
Git-friendly option to save/export collections and environments as separate files

### ISSUE THREAD

**Issue by jkleckner** [postmanlabs/postman-app-support#730]
In order to make it easy to use git to share and manage postman configurations, please consider saving collections and environments to separate files.  See Issue #729 for environment scopes and consider saving each set of environment variables into a file named with the scope.  Save each collection to a file named by the collection.  Then export/save/import/load the files from a directory.

**Comment by a85** [comment]
We recommend sharing through the new Team Sync feature. Alternatively, the ability to download Postman Collections and environments as separate files is already available. This feature will not be part of our roadmap for the near future at least.
