### ISSUE TITLE
Feature Request: OAuth2 'password' and other grant types

### ISSUE THREAD

**Issue by intellix** [postmanlabs/postman-app-support#739]
I'm using the `password` and `refresh_token` oauth2 grant types as I'm a first-party consumer of my API. Users login through the website. Right now I'm just making the password oauth call manually and copying the `access_token` and `refresh_token` provided into my global variables and then manually setting the Authorization header.

Just figured I can have `Instant Dialog Boxes` which improves things a little... perhaps even a link to the Global variables next to the Environment specific ones would help :)

**Comment by darrynten** [comment]
+1

**Comment by darrynten** [comment]
I managed to perform a `password` grant type login with a pre-request script and environment variables.

```js
// Use backbone to login
Login = Backbone.Collection.extend({
    url: environment.url + '/oauth/token'
});

var login = new Login();

login.fetch({
    beforeSend: function(xhr) {
        xhr.setRequestHeader('Content-Type', 'application/json');
    },
    type: 'POST',
    data: JSON.stringify({
        "grant_type": "password",
        "client_id": environment.api_client_id,
        "client_secret": environment.api_client_secret,
        "username": environment.api_username,
        "password": environment.api_password
    }),
    success: function(data, array) {
        postman.setEnvironmentVariable('access_token', array.data.access_token); 
    }
});
```

The only thing I haven't been able to achieve is running this script before all requests in a collection.

This can also be modified to use the `refresh` grant type quite easily.

**Comment by claym** [comment]
I would love to see this implemented as well.

**Comment by bandtank** [comment]
I can't believe this program doesn't support more grant types. I bought it for automated API testing and I can't do that because it doesn't support grant_type=password. This issue is over 9 months old and still hasn't been addressed...

**Comment by darrynten** [comment]
My pre-request script 2 comments back easily takes care of your issue. I'm easily able to run automated tests with it.

**Comment by bandtank** [comment]
You said directly in your comment that you haven't been able to get that to work in a collection. If that's still the case, then it doesn't solve my problem.

**Comment by darrynten** [comment]
I just did it per request in a collection, not a bad work around

**Comment by bandtank** [comment]
Unfortunately, I need all subsequent requests to use the same token, so it won't work for me. I appreciate your effort and that you shared your workaround, though.

**Comment by intellix** [comment]
I created a POST OAuth request like so:

URL: {{apiEndpoint}}/oauth

``` json
{
  "grant_type": "password",
  "client_id": "web-app",
  "username": "{{emailAddress}}",
  "password": "{{password}}"
}
```

Test (put the accessToken and refreshToken into your variables):

``` js
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("accessToken", data.access_token);
postman.setEnvironmentVariable("refreshToken", data.refresh_token);
```

And then later requests you can send your accessToken with each requests: `Authorization: Bearer {{accessToken}}`

This all works well with the test runner as well because I test the whole system in order:
 1) POST /user (with pre-request creating random email/password and set it as a var)
 2) POST /oauth (with password grantType)
 3) POST /oauth (with refresh_token grantType)
 3) GET /user (using accessToken)

**Comment by bandtank** [comment]
When I try the above solutions in the pre-request script, I get this error:

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500.`

I can't get it to work regardless of what I add to the header block.

**Comment by bandtank** [comment]
For anyone else struggling with CORS problems, this worked for me:

```
$.ajax({
  type: 'POST',
  url: environment.api_url + "/oauth/token",
  data: {
      grant_type: "password",
      username: environment.api_username,
      password: environment.api_password,
      client_id: environment.api_client_id,
      client_secret: environment.api_client_secret
  },
  async: false
}).done(function(data) {
  postman.setEnvironmentVariable("access_token", data.access_token);
});
```

**Comment by dhiva** [comment]
Could we also please get client crediential grant type implemented?

**Comment by reinholdB** [comment]
I would love to see grant_type=password supported as well.

**Comment by ghost** [comment]
:+1:

**Comment by oflannabhra** [comment]
`grant_type = password` is pretty important for any first party consumption of an API. Would be great to automate this

**Comment by granthbr** [comment]
+1 on the grant type for password

**Comment by granthbr** [comment]
Nice script by the way @intellix . Works great for me but this would be great as a feature of the UI.

**Comment by akabab** [comment]
+10 on the grant type for password

**Comment by dominikhajduk** [comment]
+1 for the grant type for password

**Comment by shark0der** [comment]
I'd really like to have this functionality implemented. Right now I'm manually updating environment variables using the post-request scripts.

**Comment by Kenblair1226** [comment]
+1, need grant type = password. And maybe make it collection scope so other tests can reuse the same token.

**Comment by tfrydrychewicz** [comment]
+1 for grant_type=password

**Comment by kkrawczy** [comment]
+1

**Comment by crittelmeyer** [comment]
+1!

**Comment by jwardle** [comment]
+1

**Comment by sheluchin** [comment]
+1

**Comment by gagichce** [comment]
+1

**Comment by uherberg** [comment]
+1

**Comment by enderim** [comment]
+1. So what is the latest situation on this implementation ?

**Comment by burithetech** [comment]
+1, we build our app on grant_type password and we need test our api effectively through oauth 2.0 with grant_type password. So needed. :)

**Comment by jasonpranevicius** [comment]
+1

**Comment by j8edev** [comment]
+1

**Comment by johnraythomas** [comment]
+1

**Comment by james-flume** [comment]
+1

**Comment by pdesjardins90** [comment]
+1

**Comment by jghankins** [comment]
+1

**Comment by ollyzpalace** [comment]
+1

**Comment by Art-B** [comment]
+1

**Comment by SyedSulaimanM** [comment]
+1 for grant_type=password

**Comment by flookami** [comment]
+1

**Comment by stephen-talari** [comment]
For most of the apps use `password_grant`,  it is very much needed for developers
+1

**Comment by BancuTheKind** [comment]
We just paid the annual fee. If I was paying attention to see that that password grant type is not there I wouldn't have renewed. This request is 2 years old. I'm guessing that nobody is paying attention anymore.

**Comment by ghost** [comment]
+1

**Comment by PhanVanLinh** [comment]
+1 for grant_type password, it very important

**Comment by jitbug** [comment]
+1 !

**Comment by pencildrummer** [comment]
+1

**Comment by a85** [comment]
Everyone, this is in the works. We'll have an update soon.

**Comment by ghost** [comment]
@a85 Thanks for the update!

**Comment by jordyvandomselaar** [comment]
BUMP!

**Comment by alanwcorley** [comment]
We could greatly benefit from the oAuth v2 grant_type password feature too!

**Comment by erdemkeren** [comment]
+1

**Comment by ghost** [comment]
@a85 what's up with the assignment removal?

**Comment by sdnts** [comment]
Guys, we're planning on having a more generalized authorization helper, will take this up as a part of that :)

**Comment by VictorPascualV** [comment]
+1

**Comment by andrefigueira** [comment]
+1

**Comment by kitguy** [comment]
+1

**Comment by solvingj** [comment]
+1

**Comment by solvingj** [comment]
@a85 Sorry to bother, but can you provide any update?

**Comment by pschmidt88** [comment]
+1

**Comment by gjsduarte** [comment]
+1

**Comment by Structed** [comment]
+1

**Comment by sabby62** [comment]
+1

**Comment by sebastian-serfe** [comment]
+1

**Comment by zrod** [comment]
Hi, any updates on this? Thanks!

**Comment by kentoj** [comment]
+1

**Comment by Structed** [comment]
Wow, more than two years later this was added to the OAuth2 TODO list! awesome! I really do hope it won't stick there forever... Would love to properly use postman at last!

**Comment by IchordeDionysos** [comment]
I would like to have grant_type `service_account` :D

**Comment by eagoo** [comment]
I would like to have grant_type service_account :D

**Comment by rossjcooper** [comment]
+1

**Comment by mirszy** [comment]
+1

**Comment by stevenhurth** [comment]
I'd definitely appreciate the password grant type as well.

For a simple use case workaround, I was able to put the type and credentials right in the query string when making the request for an access token. I just left the selected grant type in Postman as 'Client Credentials'.

Obviously, I'm not sure if everyone's implementation supports this, and I do not recommend using this approach in production. This was just my approach for a very simple use case.

`{{apiUrl}}/oauth/token?grant_type=password&username={{authUser}}&password={{authPassword}}`

**Comment by shark0der** [comment]
Also beware that in the solution proposed by @stevenhurth the webserver
will keep logs with plaintext credentials which is definitely not a good
idea.

**Comment by stevenhurth** [comment]
Right on @shark0der - know your infrastructure if you plan to use that approach.

I was only dealing with local development, running only an application server. No web servers, load balancers, etc in between.

**Comment by michaelsogos** [comment]
Dear,

Do you have plan to add password grant_type for OAuth 2.0?

**Comment by georgesamy** [comment]
This issue is 3 years old, can anyone suggest an alternative to postman for performing grant_type password?

**Comment by Structed** [comment]
@georgesamy no - but it's easy to get it with the [solution](https://github.com/postmanlabs/postman-app-support/issues/739#issuecomment-82885634) from @darrynten above

**Comment by Structed** [comment]
It's easy to get it:

* create a login request in Postman
  * ![image](https://user-images.githubusercontent.com/29922/30250693-34cb6af4-9653-11e7-853e-0d3fadad6e07.png)
  * ![image](https://user-images.githubusercontent.com/29922/30250680-0d0e6b88-9653-11e7-9e76-caf997b7df17.png)
  * Add this test script:
  ```
  var jsonData = JSON.parse(responseBody);
  postman.setEnvironmentVariable("token", jsonData.access_token);
  ```

This sets a token parameter. You can use it in subsequent requests like this:

![image](https://user-images.githubusercontent.com/29922/30250712-7d498aae-9653-11e7-8956-48a53d9444cd.png)

**Comment by Jasonlhy** [comment]
+1

**Comment by a85** [comment]
This should be available in the latest versions of Postman:

<img width="652" alt="screenshot 2017-12-23 10 40 27" src="https://user-images.githubusercontent.com/653409/34321885-b6b794a4-e7cd-11e7-8036-8fe78dbfa84f.png">

Login requests like the one that @Structed suggested can be written at the collection level now inside a pre-request script.

**Comment by a85** [comment]
@harryi3t @kamalaknn @shamasis Can this be closed?

**Comment by harryi3t** [comment]
@a85 yes, we support all the 4 grant types.

**Comment by voltechs** [comment]
Sending ClientID and SecretID when empty is breaking some things (like `Doorkeeper`). Could we just omit those from the payload if they're `null`?
