### ISSUE TITLE
Greetings. Avast Free Antivirus was installed by this version of Postman: "https://drive.google.com/open?id=1sAZWnJZ08FZH30PY19oLNw0Vi6ft3DrN". This was done without asking my consent before. I'd like to know why and if this had happened to other people before. I'd also want to tell that, because of this unlucky event, i had to format my pc to make it work fastly as previously. Regards

### ISSUE THREAD

**Issue by argex18** [postmanlabs/postman-app-support#7456]
**Notice**  

If you've found a vulnerability in our service or website, or want additional information regarding how we manage security, please send an email to security@getpostman.com. We will review it and respond to you within 24 hours. Please use our [PGP public key](https://assets.getpostman.com/getpostman/documents/publickey.txt) to encrypt your communications with us.

If you are a security researcher, please go through the following points for reporting security issues.

- Mail to security@getpostman.com and express interest along with a short summary of the nature of issue you want to report.
- We will triage and add your email address to our internal security tracker.
- Subsequently you can report your security issues directly using the tracker.

Read our [security reporting guidelines and policy](https://www.getpostman.com/vulnerability-reporting) for more details.

**Comment by shamasis** [comment]
Hi,

It is unlikely that official distributions of Postman would exhibit any such behaviour. Our distributions are strongly tested and goes through a number of audits before being released. Additionally, I wouldn’t like to retain a public link to any file on GitHub if it is suspected. Please email us at help@getpostman.com

I’m deleting this thread.
