### ISSUE TITLE
DELETE Sends Two Requests

### ISSUE THREAD

**Issue by philostler** [postmanlabs/postman-app-support#746]
I've a DELETE route specified on my API that I'm testing with the following sig...

```
# URL
{{server}}/people/gareth-emery?index=1
{{server}} is http://localhost:5000
```

```
# Preview
DELETE /people/gareth-emery?index=1 HTTP/1.1
Host: localhost:5000
Accept: image/jpeg
Cache-Control: no-cache
```

```
# Curl
curl -X DELETE -H "Accept:image/jpeg" -H "Cache-Control:no-cache" -d '' http://localhost:5000/people/gareth-emery?index=1
```

I was trying to work out in my code why I was getting my route hit twice and it appears that it's Postman doing this.

Doing a little debugging, this happens when I set the `Accept` header to `image/jpeg`. Changing the `Accept` header to `application/json` results in only a single request being sent.

Postman should only be send a single request whatever the `Accept` header value

**Comment by philostler** [comment]
Any update on this?

**Comment by abhijitkane** [comment]
I sent a DELETE request to httpbin.org/delete, with Accept and Content-Type, both set to image/jpeg, and the request was only sent once - http://puu.sh/fMCUd.png. Are you seeing two requests sent for the same setup?

**Comment by philostler** [comment]
I've check this hopefully over the weekend and get back to you

**Comment by skradel** [comment]
This is still a problem on Postman 2.1.6 (packaged) -- a POST request with Accept: application/pdf fires twice, but changing to something like application/json fires only once as expected.  Seriously confused me to see my API executing again after finishing a somewhat involved process.

**Comment by a85** [comment]
@abhijitkane Can you look into this again?

**Comment by abhijitkane** [comment]
If a request returns a pdf file, Postman needs to make the request again, with xhr.responseType="arraybuffer". This gets the response as an ArrayBuffer, which can be saved to disk as a PDF file.

Possible workarounds - 
1. give a setting to set the expected value as pdf before sending
2. set responseType to arraybuffer if the Content-Type header is set to application/pdf
3. retain the current flow

The problem with 1 and 2 is that setting Content-Type: application/pdf doesn't guarantee a PDF file as a response.

Will spend some time on this tomorrow.

**Comment by cpanato** [comment]
i saw a post request using multipart and if you hit enter instead of click on the send button, the postman send two requests.

**Comment by ariponce** [comment]
I'm also having the problem @ctadeu describes.

**Comment by a85** [comment]
This should be fixed in 4.0+

**Comment by kranthikiranbandaru** [comment]
Could you please let me know when the version 4.0+ is being released? I have the same issue when I try to get a pdf from WSO2 ESB.

**Comment by abhijitkane** [comment]
@kranthikiranbandaru What version are you on? You can update by going to chrome://extensions, enabling 'Developer Mode', and clicking 'Update extensions now'.

**Comment by kranthikiranbandaru** [comment]
Hello Support team,

I'm using the 4.1.2 version. Yet i see that the request is issued twice if
the return response is a pdf.

[image: Inline image 1]

Best Wishes
   _Kranthi Bandaru_:-)
   Mobile : 248 495 7091

**Comment by fedebaier** [comment]
I'm having this same issue now, with version 5.5.0.

I'm making just a simple DELETE request and Postman makes it twice, no matter what Accept header value I set, or no Accept header at all.

```
DELETE /api/accounts/5a44a6116cb902e696e13be6 HTTP/1.1
Host: localhost:3100
ClientToken: GUbyyIy7sQCtsJUAenRpYGq2sPmaRufv
Authorization: dknrf81BcbB1MvYkk4bNSERdJQJb3vdE6HUa46ZRo6cHUI1ntLGN4SiG96x27DrI
Cache-Control: no-cache
```
