### ISSUE TITLE
unchecked url-params and form-data fields are not saved

### ISSUE THREAD

**Issue by yehosef** [postmanlabs/postman-app-support#747]
I have a request with url-params or form data and I want to save all the options so in the future I don't have to look for them.  But most request I don't need most/any of them.  I want to save them as unselected so each time I use the request I don't have to uncheck all the possible options. The problem is that if an option is unchecked (w/ strike though) and I save the request, those options are forgotten.

**Comment by abhijitkane** [comment]
@yehosef Can you confirm the fix in v3.0.4?
