### ISSUE TITLE
Cancel doesn't work with interceptor

### ISSUE THREAD

**Issue by nathan-osman** [postmanlabs/postman-app-support#748]
When the interceptor is enabled, long requests cannot be canceled. Clicking the "cancel request" button has no effect (Postman continues to read from the socket) and the "Send" button remains disabled.

**Comment by abhijitkane** [comment]
@nathan-osman Can you confirm the fix in v3.0.4?

**Comment by nathan-osman** [comment]
Sorry for the delay. Yes, I can confirm that cancel now works with the interceptor enabled on v3.0.5. (The socket still isn't closed but the "Send" button can be used again.)
