### ISSUE TITLE
Creating Buttons or Links to invoke POSTman with request settings

### ISSUE THREAD

**Issue by MiErnst** [postmanlabs/postman-app-support#751]
While developing REST APIs we always facing the problem how to document them and how to provide sample requests in the documentation. When doing so, we always describe the request, the request method, the content type, the authentication type and so on and please the reader to copy and paste the information into their prefered REST client. I think it would be nice to invoke POSTman right from the documentation with the requiered settings. 
Yes, it would also be possible to provide a collection with all samples, but when you have to handle more than hundred samples, I think for a reader he won't like to map from the current documentation content to the right sample in the collection.
As I could not find such an feature in the documentation, I think it would be really nice to provide a link or button similar to a plunker link but which invokes the browser extension and sets the given values into the right fields.

**Comment by aditikul** [comment]
@MiErnst @abhijitkane Hi there, closing this issue since the latest updates have solved this to varying degrees. We also have the Postman Documenter which allows people to view sample responses in a better/more readable view. Let me know if you've tried any of the latest features.
