### ISSUE TITLE
Encoding of redirect_uri in OAuth 2.0 access token request

### ISSUE THREAD

**Issue by encaf** [postmanlabs/postman-app-support#752]
When requesting an OAuth 2.0 access token Postman is generating this:

`GET /authorize?client_id=sme9u5k&scope=default&state=84000&redirect_uri=https://www.getpostman.com/oauth2/callback&response_type=code HTTP/1.1`

The redirect_uri can not be altered in the interface and according to the specification the parameters should be in urlencoded format which does not seem to be the case.

**Comment by gaslitbytech** [comment]
@eli-b I have the same issue, have you found a solution?

**Comment by eli-b** [comment]
@darwindave, there's a new Postman version which fixes this issue, but has another problem so OAuth 2.0 still isn't usable for me.
EDIT: I have no idea what I was talking about. The callback URL is still bad.

**Comment by eli-b** [comment]
This issue is still a blocker for using Postman with OAuth 2.0 for me. @a85, I'd send a PR if I could, I imagine resolving this shouldn't be too difficult.

**Comment by DimitriGilbert** [comment]
I have this issue too with my implementation of oauth2 (using http://oauth2.thephpleague.com/ ) if i comment lines checking the redirect_uri when issuing the token, no problem (this is not really a solution though).

**Comment by abhijitkane** [comment]
@DimitriGilbert @encaf @eli-b Can you confirm this fixed in the latest version of the app?

**Comment by encaf** [comment]
@abhijitkane I haven't been working on the OAuth project for a while but I tested the scenario today with the latest version (4.1.3) and the URI looks good:

> GET /authorize?client_id=gpU0vnGwv7a1Pg1KLXtC&scope=default&state=3852093&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code

The subsequent authorization and fetching of the token also works fine.
