### ISSUE TITLE
Simplified Copy and Pasting

### ISSUE THREAD

**Issue by patimen** [postmanlabs/postman-app-support#755]
What I really want is copy paste the way I get it in every other editor:
Select a call, or a folder, or a collection. Press Ctrl (or Cmd)-C.
Select a different call, folder or collection. Press Ctrl - V.
Bam! There's my copy. The current implementation is not much fun, clicking the "copy" button and then dragging over to where I want it, particularly if I have a lot of copying to do.

For bonus points, copy it into the clipboard as JSON text. That way I could paste it into an email or IM, send it to someone, they could copy the JSON and then paste it into their Postman. 

For super duper bonus points, multiple selections (select a sequence of calls, folders or collections). :)

**Comment by giridharvc7** [comment]
We've introduced bulk copy-paste along with keyboard interactions recently, let us know what you think about the sidebar interactions now. You can read more about it [here](https://blog.postman.com/introducing-sidebar-bulk-actions/)

![sidebar](https://github.com/postmanlabs/postman-app-support/assets/1040583/55a10917-e2de-432b-9891-5f9d24cd484f)
