### ISSUE TITLE
Add markdown table support to request description

### ISSUE THREAD

**Issue by Dinoshauer** [postmanlabs/postman-app-support#757]
It would be really nice to have as it would be prettier to document parameters etc in a table instead of lists :)

Example:

| Name  | Required | Type |
|-------|----------|------|
| start | false    | int  |
| end   | false    | int  |

**Comment by Ligator** [comment]
Like

**Comment by benjaminjones** [comment]
+1

**Comment by leonardothibes** [comment]
+1

**Comment by whyyk7** [comment]
+1

**Comment by polds** [comment]
+1

**Comment by deepredsky** [comment]
+1

**Comment by sahin** [comment]
+1

**Comment by lgmworks** [comment]
I also want this

**Comment by lgmworks** [comment]
+1

**Comment by aat-antoine** [comment]
+1

**Comment by ngleav** [comment]
+1, how is this not a thing when it says that comments support markdown?

**Comment by jamesholcomb** [comment]
+1, particularly since html and Bootstrap 3 css no longer works

**Comment by aldodfm** [comment]
+1

**Comment by ktyacke** [comment]
+1

**Comment by abtiddle** [comment]
+1

**Comment by ebekker** [comment]
+1

**Comment by onebit0fme** [comment]
+1

**Comment by abhijitkane** [comment]
We've added this in the latest Postman version - 3.2.10.
<img width="284" alt="screen shot 2016-01-20 at 01 33 24" src="https://cloud.githubusercontent.com/assets/681190/12430479/d5840486-bf15-11e5-80f3-7c97b664857d.png">
