### ISSUE TITLE
Quick edit variables

### ISSUE THREAD

**Issue by PrinceNebulon** [postmanlabs/postman-app-support#763]
It would be very helpful to have a window in the main UI to allow quick editing of environment and global variables. My use case is that many of my saved requests in collections require data from other requests to be sent in the request header/body. Currently, I must edit the environment/global variables using the menu. It's at least 5 clicks to do that each time I want to change something. Having the window always available in the UI would make this super easy.

Personally, I'd like to see the variables window placed at the bottom of the History/Collections panel on the left. It might make sense to move the entire environment menu there to keep the environment pieces all in the same place. I'd like the variables UI to be visible all the time, but I can see why others might not want that, so the ability to collapse the variables window would be a prudent feature to add. 

Here's a quick mockup of what this might look like (sensitive project information blurred):
![postman](https://cloud.githubusercontent.com/assets/1349974/4667792/0ef6f7c6-5560-11e4-8a22-6b8dd278cdfe.png)

**Comment by lemuelf** [comment]
@a85 Any updates on this feature request?  We would love to see this as well.

**Comment by bhawna2109** [comment]
Hi guys, we are working on a few concepts around this, but there's no ETA for this just yet. One of the concepts is to actually bring all the variables which you've used in your current request at one place, show them in the context of the request, and allow for quick editing from there.

We'll update this thread when we have a prototype out to test. Thanks much for your patience! :)

**Comment by sankalp0o** [comment]
Hi @PrinceNebulon , @timlewis-promedica , @douglasknudsen , @lemuelf ,
I know this issue has been pending for a long time but better late than never. We are going to have (current) environment and globals directly editable from the quicklook menu dropdown which can be accessed in just a click. This will go out soon in one of the upcoming app releases.

I know this would still require one click to view and edit the values but we realised that this is most optimal way (as of now) without taking up more screen space and hindering other work flows. Will keep on working to make this flow better.

**Comment by vkaegis** [comment]
Hey guys, closing this issue. Feel free to open another if you have more feedback around this.
