### ISSUE TITLE
OAuth Headers tab fails to stay open between requests.

### ISSUE THREAD

**Issue by rbnzdave** [postmanlabs/postman-app-support#766]
Ive seen similar issues which get marked as closed before they are actually fixed, so here is the issue specifically, and this ticket can just stay open until it is actually fixed.

When a collection has 2 requests in it. The Oauth 1.0 helper tab needs to be opened every time you run a request ( it will close and return to "normal" when changing between requests ) in order for it to refresh and provide oauth data. Saving the request does not save the state of the helper tab. As i see it, the only way to identify a request as needing oAuth is to have the tab open.

Additionally, this tab retains the information across all requests. this is hard to categorise as a bug or a feature, on the one hand, several requests would benefit from having the same oauth information, such as using an application token to get various member data or whatnot. The other hand requires this information to only apply to specific requests, as is the case when initiating communication and requesting tokens and verifiers needs these values to change each time. 

The stand alone client (packaged) has tests which you can use variables to populate for each new stage, but again, without having the ability to have the helper open and thus the information retained, this data is not being used and the requests fail, rendering the jetpack collection runner useless for anything with oauth.

Its broken.

**Comment by a85** [comment]
Available in the latest version I believe.

**Comment by abhijitkane** [comment]
@rbnzdave Can you confirm? (The latest version is 3.0.4)
