### ISSUE TITLE
Large numbers in CSV files get rounded

### ISSUE THREAD

**Issue by msubel** [postmanlabs/postman-app-support#769]
Hi all,

Before I get to the issue, I want to say that I absolutely love Postman and it made my life so much easier. 

## Issue ##
I tried using a CSV file to provide variables for a collection run and it turned out that large numbers are getting rounded. It's probably due to how javascript is handling large numbers, but perhaps there's a workaround to keep them as string, to avoid the rounding. Surrounding the number by quotes seems to solve the problem, but it's not very intuitive/obvious.

### Steps to reproduce ###
1. Start Collection runner
2. For the Data file, choose a CSV file with contents as below
    ```
    id
    11234567800033596096
    ```

3. Click Preview Data

### Expected result ###
Data preview shows `11234567800033596096` as the value of `id` in the first iteration.

### Actual result ###
Data preview shows `11234567800033595000` as the value of `id` in the first iteration.

The issue described above does not affect only the Data preview. The values used in the collection runs are also rounded. Please see the screenshot illustrating the problem

![postman_rounding_issue](https://cloud.githubusercontent.com/assets/3251958/4762556/6026f1a2-5b03-11e4-90cf-f4f7ab3fd16f.png)

**Comment by a85** [comment]
JS limitation right now.
