### ISSUE TITLE
Expand text textfields

### ISSUE THREAD

**Issue by jorgegarciamule** [postmanlabs/postman-app-support#773]
Some textfields, like url ones, are too short.

![screen shot 2014-10-24 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/7658927/4773974/8cbfa01a-5ba8-11e4-8e95-2faa8260cf9e.png)

**Comment by aditikul** [comment]
We're working on an update to fix this. Thanks for your patience!

**Comment by numaanashraf** [comment]
@jorgegarciamule @ksatirli This has been addressed in Postman 4.0.
