### ISSUE TITLE
Confirm sending a delete request

### ISSUE THREAD

**Issue by micjaesc** [postmanlabs/postman-app-support#777]
Hi,
There was request #183 unfortunately it was fixed only for collection.
DELETE request is painful sometimes, and it would great to have some popup or even configuration to block it.

We have scenarios, when users switch between resources, and sometimes forget to switch method(GET<>DELETE)

PUT POST force users to edit BODY, so it is more difficult to make troubles. DELETE just needs URL. 
BR
Michal

**Comment by rprince** [comment]
Ditto for environments.

**Comment by a85** [comment]
This is very specific to the API call and unfortunately we don't have plans to support this.

**Comment by RJLuckey** [comment]
It is a very common problem for everyone using Elasticsearch!
