### ISSUE TITLE
HTTP Response Code "OK" comes with every unknown code

### ISSUE THREAD

**Issue by itsrob** [postmanlabs/postman-app-support#778]
As it seems, Postman just adds a "OK" after every HTTP Response code it does not know. For the user it looks like the server has sent this "OK" message, but it did not.
![postman1](https://cloud.githubusercontent.com/assets/4151393/4828430/11b1f310-5f80-11e4-94e4-f4c6666228b5.png)

Whereas the Firefox web console shows that in this example it should be just "377" - see below:
![postman3](https://cloud.githubusercontent.com/assets/4151393/4828603/5b1d8cd4-5f81-11e4-9924-2eb59c0aaca5.png)

I am using Version 0.10.5.2 (packaged) with Win7 64bit

**Comment by abhijitkane** [comment]
@itsrob Unknown codes show 'Unknown' in the latest version.
