### ISSUE TITLE
Add raw body support with OAuth 1.0 and oauth_body_hash field

### ISSUE THREAD

**Issue by frickenate** [postmanlabs/postman-app-support#783]
I have written an API that uses JSON request bodies, as well as OAuth 1.0a authentication. The OAuth isn't as secure if the request body isn't factored into the hash signature. There is an additional OAuth parameter [oauth_body_hash](https://oauth.googlecode.com/svn/spec/ext/body_hash/1.0/oauth-bodyhash.html) that can be included with the request to add the request body to the signature.

For integration within POSTMan, the specification simply requires calculating the hash (sha1 or sha256, no hmac) of request bodies. application/x-www-form-urlencoded request bodies are exempted since those values are already accounted for in the signature. So for multipart/form-data, raw and binary options, the request body - or empty string for an empty body - is hashed and an oauth_body_hash argument is added with that hash value.

All we'd need is a checkbox under OAuth 1.0 for "Use body hash", and adding the oauth_body_hash field to the request arguments. POSTMan is great, but I really need this option and will donate generously if it can be implemented and released very quickly.

**Comment by aesopwolf** [comment]
+1 on this

**Comment by aesopwolf** [comment]
@a85 would you be open to accepting a pull request if this feature was added? I just want to get your feedback before I start working on it. Thanks!

**Comment by reevesy** [comment]
+1 for this too. I need to include the oauth_body_hash

**Comment by starlight54** [comment]
+1 Would find this very useful too

**Comment by markdemich** [comment]
+1 without this, it's impossible to test my API.

**Comment by SirPyros** [comment]
+1 I need this for my project

**Comment by Arieg419** [comment]
+1 would love to see this added.

**Comment by sdickson-macmillan** [comment]
+1

**Comment by mohitranka** [comment]
This has released in the latest Postman app v7.27. Please upgrade and give it a go !
