### ISSUE TITLE
Oauth2 callback handler crashes with 500 

### ISSUE THREAD

**Issue by alebly** [postmanlabs/postman-app-support#786]
Below info to repro.
Could you add some error details to the error response when handler is unable to redeem code to get access token?

GET https://www.getpostman.com/oauth2/callback?code=AAABAAAAL4bR_7sxM0SlcAsIeKfQhaSGnNcJc3wqvlc1cnxNRRydA184nUhnayJ76lByEigQloVBsUUV6yydHzwyRRMbkVUOVGuofS65HnnpmVAd5T43wVoLMMyBNUoE3RAS1zuUJCeWZF7rmBuTR3P3RH9y89kqniqAcHEnCaEYTScok7Phn_R0tS2TtgJJ7S_uj7AXmqhnuoGq52UO5kpJbGkjtUc8Ogq6iUm9v68c4uy3iHfEB15oX2ES_mVurChIKN-cM-vUOSvndZg1QyvojCTd7ANNdlWMASD-uEJ5YEPfBnK6Pc2wvpn9-FI1dlPttLcPE6R-H9AsbLBR6zutDxEO4Xj10qu6-RO3hHgnTUx5yH8v1oXsotpRLK8x9rPhEuEtdbSwQ7nanrEOySjpwLp2u78XlPaDWDtsasBBu2j4vmi8X27Sv1YszLSsB7H7TCjfeKSX3nBszR7H81J8kz-LjvW4SUCR9HqB7FrS3ReJA2hWT0ooMC4eoMKFw7qLStpCbKXBvYp60DxHxma_7m8WB1Eh-Q2f3ggsX_huaCgj-xeeSkjispofmZ25U3IWgQs7GQBAqiAvmcE7EgKUkODAqnSRHXWvBQq7CGUQzv_ncawgAA&state=114603&session_state=28968e3e-29c5-4304-97ff-341eb663d34f HTTP/1.1

HTTP/1.1 500 Internal Server Error
Server: nginx/1.1.19
Date: Mon, 03 Nov 2014 21:45:12 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: oauth2_key=a%3A2%3A%7Bs%3A17%3A%22oauth2_request_id%22%3Bs%3A6%3A%22114603%22%3Bs%3A10%3A%22slim.flash%22%3Ba%3A0%3A%7B%7D%7D; path=/; expires=Wed, 05-Nov-2014 07:05:11 UTC

192
<html><head><title>Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Error</h1><p>A website error has occurred. The website administrator has been notified of the issue. Sorry for the temporary inconvenience.</p></body></html>
0

**Comment by sdnts** [comment]
This shouldn't be an issue with the latest version of the app. Do let us know if it still persists.
