### ISSUE TITLE
'Copy' button does not do anything when response is too large for pretty mode

### ISSUE THREAD

**Issue by aaron-trout** [postmanlabs/postman-app-support#791]
Chrome Version 38.0.2125.111 (64-bit)
Xubuntu 14.04 fully up to date as of 7th Nov 2014 ~ 9AM
Packaged app version of Postman

'Copy' button does not do anything when response is too large for pretty mode. Could we just have it be greyed out / copy the un-prettified version instead in this case?

I initially thought it didn't work at all, but it was that the message about the response being too big didn't display for nearly long enough - I'll raise a seperate issue for that :-)

**Comment by collinpeters** [comment]
Maybe this is the problem I am having with the copy button. Where do you see a message about the response being too big? My response is quite small: 100 lines, 5000 characters.

**Comment by abhijitkane** [comment]
@collinpeters What version of Postman are you on? You can check by opening the Settings modal (wrench icon on the top-right -> About)

**Comment by vishgupta92** [comment]
I faced a problem while copying/writing a '#' char ( hash character ) in input params.
