### ISSUE TITLE
Error reply from OAuth2 authorization server doesn't display

### ISSUE THREAD

**Issue by oauthtest1c** [postmanlabs/postman-app-support#792]
Steps to repro:
1. Register Client on OAuth2 authorization server with ClientId, Secret, CallbackUri
2. Call OAuth2 authorization server with incorrect ClientId or CallbackUri etc (OAuth 2.0 -> "Get access token")
3. Server return JSON error reply according to RFC6749 https://tools.ietf.org/html/rfc6749#page-45
4. POSTMan show nothing

Expected:
POSTMan display error info

**Comment by sdnts** [comment]
This shouldn't be an issue with the latest version of the app (4.8). Closing.
