### ISSUE TITLE
Can't get access token (oauth2) from github

### ISSUE THREAD

**Issue by gvaduha** [postmanlabs/postman-app-support#797]
Steps to reproduce:

1. Register app @github https://github.com/settings/applications and get client id and secret
2. In POSTMan select OAuth 2.0 Get token with parameters defined in github manual https://developer.github.com/v3/oauth/
 - Authorization URL: https://github.com/login/oauth/authorize
 - Access Token URL: https://github.com/login/oauth/access_token
 - Your client ID and secret
 - Scope (Optional): profile
3. After logging in and authorize application to access profile POSTMan says "Could not initiate OAuth2 workflow"

Desired result:
POSTMan receive access token from Github or display error code and text returned by Github OAuth2 server

Comments:
I've checked google server and process works just fine.
When using proprietary server on http://localhost:port POSTMan callback returning 500 (as mentioned in https://github.com/a85/POSTMan-Chrome-Extension/issues/786) to any request containing "code" parameter. If "code" parameter doesn't present server allways return 200 with empty response. Request to google server is nearly the same but works correct. Is there any issue with http scheme or port?

**Comment by sdnts** [comment]
GitHub OAuth2 should work properly with the latest version (4.8) of the app. Closing.
