### ISSUE TITLE
read local file in tests in postman

### ISSUE THREAD

**Issue by hanyghazal** [postmanlabs/postman-app-support#798]
I want to read a local file and parse it in tests in postman and I can't able to do this

**Comment by xiaobeiying** [comment]
@abhijitkane Looking forward to the NEW version.

**Comment by garunski** [comment]
+1

**Comment by bennetone** [comment]
+1

**Comment by barnesm999** [comment]
Any progress on this? Would really like the ability to load some complex data from files during Pre/Test Script. For example, I would like to load a JSON file which contains the expected response JSON schema. This would allow me to externalize the schema from the script and re-use it across multiple collections while only maintaining a single copy. 

Currently I am stuck duplicating these schema definitions across many collections (or I need to set a global variable before running which is not desired). If the schema changes I will have to update dozens of collections that use it.

**Comment by ji50180** [comment]
Would be very interested in using that in our postman-sheme, too.
Our API calls are expensive, and we would have several dozen tests per call, which we now have to fill in per hand. One Test per call would take hours in our system.

Using a csv for that would be so much more effective.

**Comment by saschawiener** [comment]
Would be cool to have somthing like this! We're doing JSON validation via tv4 in Jenkins/newman. The json-schema gets generated dynamically by a pre-executed server script. Loading this file would be much easier than deploying it somewhere and calling it via HTTP.

**Comment by leonelgalan** [comment]
I'm interested in this feature too. I want to reuse JSON schema files I have, in both, RSpec and Postman/newman, the current solution is to write the schema into every Postman test.

**Comment by Rachit1980** [comment]
Need a way to read a txt/CSV file in tests and compare values to JSON element values

**Comment by abhijitkane** [comment]
A workaround for now is to start a local server (https://www.npmjs.com/package/simplehttpserver), and use a Postman request and test script to load the response into an environment variable.

Since we need to support collections in the cloud as well, this isn't on the immediate roadmap.

**Comment by prashant7090** [comment]
@barnesm999 Hey did you get any solution to externalize the JSON response schema files?

**Comment by Kal6** [comment]
Is there any new developments on this feature? It would be nice if we have it to handle the data from outside of the scripts.

Thank you!

**Comment by christianbaumann** [comment]
+1

**Comment by tinghf** [comment]
just wonder is there any update on this? like timeline?

**Comment by RickHough** [comment]
One solution might be to have your developers load the data to the application under test from csv, then expose that data via an end point. You can then load that as Global Variables using an initialisation script. Not pretty of course but it works.

**Comment by nileshy112** [comment]
Instead of copy and paste the JSON in body of the request, I would like to read it from JSON file (external source) and then replace all dynamic variables from JSON file.
e.g. Below is my JSON file which I want to read it from my hard disk and replace all variables with valid values before sending it.
{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "age": {{age}},
  "correlationIds": [
    {
      "id": "{{id}}",
      "source": "{{source}}"
    },
    {
      "id": "{{id2}}",
      "source": "{{source2}}"
    }
  ]
}

**Comment by trastle** [comment]
This is sorely needed for short lived tokens etc. 
Manually copy pasting a token into postman every time my tokens expire is nuts.

Even something simple like use a JSON file for the environment of a folder would be a huge improvement.

**Comment by ADaniel-dev** [comment]
i need postman read my large of test cases from csv, the csv filles contains URL, header, body and expeccted responses to assertion.  i hope pm can make it.

**Comment by junaidq57** [comment]
> I want to read a local file and parse it in tests in postman and I can't able to do this

check this out 
The pre-request and test script sections of the Postman app rely on JavaScript (not text). Therefore, you can use Postman’s pm.* API, like the pm.iterationData.get(“variable-name”) method, to access the values loaded from the data file.

https://blog.getpostman.com/2018/04/11/looping-through-a-data-file-in-the-postman-collection-runner/

**Comment by AshirwadVyawahare** [comment]
I'm unable to read the values in pre-requisite scripts when I read the data file from server in the pre-requisite script.  Is this feature not available in Postman?

**Comment by SHI-ZP** [comment]
Well, I suppose RickHough's solution would be the only approach.

**Comment by rcmonitor** [comment]
Still looking for ability to load local file into string variable in pre-request script

**Comment by VigneshOK10** [comment]
any updates on provision for getting local files in tests?

**Comment by arlemi** [comment]
This is not something we're working on at the moment, for any updates regarding this please follow #7210.

(closing to avoid more unwanted notifications from participants in this thread. 🙂)
