### ISSUE TITLE
Responses with content-type containing the word "image" always render as images

### ISSUE THREAD

**Issue by davvves** [postmanlabs/postman-app-support#802]
If a response from a POST request is text or JSON, but the media type name in the content-type field of the response contains the word "image" Postman will try to render the response as an image.

**Comment by a85** [comment]
@davvves Is this still happening for you?

**Comment by davvves** [comment]
Yes, I just tested with the media type "dummy/image-whatever" and Postman tried to render the response as an image.

**Comment by abhijitkane** [comment]
@davves Hm..not sure how better to auto-detect the content type. Apart from hard-coding the hundreds of image mime-types, i.e.

**Comment by davvves** [comment]
@abhijitkane  Perhaps matching the string "image/" instead of "image" would be more appropriate, since image mime types have that prefix. Otherwise any custom content type, like "myapplication/image-metadata" even if it's JSON or other text, will render as an image.

**Comment by abhijitkane** [comment]
Agree. We'll push a fix for this in the next release.

**Comment by abhijitkane** [comment]
@davvves Can you confirm this fixed in the latest version of the app?

**Comment by davvves** [comment]
@abhijitkane Confirmed, just tested.
