### ISSUE TITLE
folder in folder support

### ISSUE THREAD

**Issue by dn2k-dev** [postmanlabs/postman-app-support#804]
Hi,

Does it possible to add folder in folder support? 
We updating a huge collection with more than 150 APIs and currently we have 40 folders.
It will be better to arrange it in folders structure.

**Comment by sunshineo** [comment]
+1

**Comment by kevinjalbert** [comment]
+1

**Comment by kajo123** [comment]
+1

**Comment by josephnoall** [comment]
+1

**Comment by srbangre** [comment]
+1

**Comment by rick-nu** [comment]
+1

**Comment by seslav** [comment]
+1

**Comment by a85** [comment]
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/907. This is coming to Postman soon within a few weeks.

**Comment by rick-nu** [comment]
![](https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif)
