### ISSUE TITLE
"Pretty" response border issue - v1.0.1

### ISSUE THREAD

**Issue by cnanney** [postmanlabs/postman-app-support#806]
This element has an inline height set: `<div class="CodeMirror CodeMirror-wrap" style="height: 581px; display: block;">` causing the bottom border to scroll into view on longer responses:

![image](https://cloud.githubusercontent.com/assets/195134/5021356/3be23eb8-6a9a-11e4-8b44-5d88e3f1fe97.png)

Removing the inline height fixes it for me.

Version 1.0.1 (packaged)

**Comment by abhijitkane** [comment]
@cnanney Can you confirm this fixed in v3.0.4?

**Comment by cnanney** [comment]
I have not seen this issue in v3.0.4.
