### ISSUE TITLE
digest auth doesn't retry with the nonce from the server

### ISSUE THREAD

**Issue by grimmy** [postmanlabs/postman-app-support#808]
I'm working on a node app using express and passport-http for digest auth.  In the logs, as well as the packet dump, I can see that postman is only sending a single request without the nonce.  My app is responding with a 401 with the nonce, but postman doesn't use it and resend like it should.

It seems like the only way to make this work is to manually enter the nonce and go from there, but that's just not feasible.

Any thoughts?  I can provide a simple example app if necessary.

**Comment by hoppy-kamper** [comment]
Hi,

I was having the same issue. I had to use Advanced Rest Client because it handles the nonce automatically through Chrome. Hopefully this is worked out with Postman. I like Postman!

Thanks!

**Comment by simonemazzoni** [comment]
Same issue here. I had to switch to another client. Please fix it.

**Comment by fawix** [comment]
same issue here. 

I also noticed something really odd with postman echo digest .... even if I replace the value value of `{{echo_digest_nonce}}` with blah it gets authenticated against the postman echo (not a good test). The same is not true for `http://httpbin.org/digest-auth/auth/u1/p1` which returns an `401` instead (better test)

![digest_echo_postman](https://cloud.githubusercontent.com/assets/735399/21077477/8763e338-bf1a-11e6-8b60-e325536940cb.PNG)
![digest_echo_httpbin](https://cloud.githubusercontent.com/assets/735399/21077478/87684b58-bf1a-11e6-8e20-d3978c6411b1.PNG)

**Comment by shamasis** [comment]
This should tackled by making auth to async send requests. need to formulate async authorise function @czardoz with the ability to *replay original request on auth failure*.

**Comment by a85** [comment]
@harryi3t Is this fixed for good?

**Comment by harryi3t** [comment]
@a85 yes! 
Unless the user has provided a nonce value input (in advance options), Postman will always use the one provided by the server.
