### ISSUE TITLE
Confirm unsaved edits before closing request name/description editor

### ISSUE THREAD

**Issue by kskumar** [postmanlabs/postman-app-support#810]
When editing a request's name and description, the `Esc` key closes the dialog window without any confirmation.  This is particularly problematic when using the backtick character in markdown syntax to document the request in its description.  It's all too easy to accidentally hit the `Esc` key instead of the backtick key, thus losing edits.  I think it would be desirable to add a confirmation dialog in the event that there are unsaved changes to the name or description:

"You have unsaved changes to the request name/description.  What would you like to do? [Save] [Cancel] [Exit Without Saving]" or something to that effect.

**Comment by komape** [comment]
Same for folder editing dialog window. Just edited test scripts for about half an hour and unthoughtfully hit the `Esc` button. Now everything is gone. Is there any chance to get it back? As a User I would at least expect a quit dialog about unsaved changes or autosave the changes.

@a85 You wrote on 5 Dec 2014 this will be part of a new version soon. When is this "soon"? Not losing data is so important for a not-frustrating workflow.

**Comment by sorenhansen-dk** [comment]
This is still an issue in the Windows app.

Please look into is, since it's a pain to lose data.

Thanks

**Comment by davepile** [comment]
+1 So annoying. Working on folder Pre Request scripts and have lost my work about five times today

**Comment by vkaegis** [comment]
This should be fixed in Version 7.13.0. Closing this issue for now, feel free to open another if you have any feedback on this

**Comment by vkaegis** [comment]
@davepile Looks like there's a bit of confusion regarding this issue. The OPs original issue was around dismissing inline editing of request name/description within the tab itself. A fix for this is in the works, but not ETA just yet.

Your issue should be with dismissing the Edit Collection / Folder modal. This should be fixed in Version 7.13.0.

**Comment by kamalaknn** [comment]
Pressing escape when inline editing request descriptions should now show a warning before removing the changes.
