### ISSUE TITLE
Allow parallel request execution through the Interceptor - Packaged postman client cannot send two requests simultaneously

### ISSUE THREAD

**Issue by T-Boss** [postmanlabs/postman-app-support#811]
# Problem

When multiple postman windows are open, only one request can be sent at a time (across all windows). Trying to send simultaneous requests from different windows results in all but the first becoming hung.
# Steps to reproduce
1. In postman window A, make a request to any service that takes time to return (I tested with GET http://httpbin.org/delay/20)
2. While the response is pending for window A, send any request in window B.
# Observed result

The request from window A (the long processing time request) returns as expected. The request from window B is never recieved by the server and the postman window just waits for a response; clicking cancel has no effect and the send button is stuck in the "Fetching data..." state.
# Expected result

The request in window B should be executed and handled irrespective of the status or state of any other postman windows. Multiple postman windows should be able to execute requests simultaneously.

**Comment by abhijitkane** [comment]
@T-Boss Can you confirm this fixed in v3.0.4 of the app?

**Comment by PrinceNebulon** [comment]
Kind of. The second request doesn't fail or get stuck anymore, but it appears that Postman is queuing them to execute sequentially when interceptor is on. If I turn interceptor off, they both execute in parallel in the expected amount of time. 

Screenshot below. The upper/back window is the request sent first. The lower/front window is the second request that was sent immediately following the first. The first took ~10 seconds to execute, as expected. The second took just under 20, but should have only taken ~10 also.

![image](https://cloud.githubusercontent.com/assets/1349974/8729620/735d0ac8-2ba9-11e5-87f9-870c49fbf6aa.png)

**Comment by abhijitkane** [comment]
That's a current limitation of the Interceptor - we'll fix that in a later release.

**Comment by pnowy** [comment]
Hi, do you have a timeline for that fix?

**Comment by sdnts** [comment]
@pnowy Unfortunately, Chrome has decided to phase out packaged apps, so there is no ETA on this as of now.
I'd suggest shifting to our native apps (https://getpostman.com/apps), which do support concurrent requests.

**Comment by pnowy** [comment]
Thanks for info!
