### ISSUE TITLE
FEATURE REQUEST:  Ability to add a file when executing Collection Runner

### ISSUE THREAD

**Issue by mmathe03** [postmanlabs/postman-app-support#812]
I am able to add a file within the form data area through Postman but I cannot use the same test within Collection Runner.  It would be nice to be able to choose a file prior to executing Collection Runner, or any other kind of scenario so that I can test my adding a document API with the automated API tests.  As far as I know, I have not seen anything that shows this can be done.

**Comment by jasekiw** [comment]
Why was this issue closed? This is still a feature that should be apart of the core. 
One possible way to implement this is to upload the file to a an accessible web address. The test runner can download these files when the tests run for persistence. 

PostMan could offer a premium storage service that uses user authentication to protect the test files.

**Comment by rafaelkarst** [comment]
I agree, it has been 4 years and this still not available, i agree with the solution for a public url to hold files, that should be enough to test with runner.

**Comment by thegoldenmule** [comment]
Bump-- any update? The workaround for this bug is another bug (#2392) that needs yet another workaround.

**Comment by ShruthiMukunda** [comment]
I need this feature for executing the tests from CI tools. Can you please prioritize this feature implementation?

**Comment by saswatds** [comment]
Hi @mmathe03 @jasekiw @rafaelkarst @ShruthiMukunda @thegoldenmule We had added the support for file in the collection runner in our latest stable Postman app version `v7.1.1`. You should now be able to run request with form data and binary body within the collection runner.

Closing this issue now. Feel free to create a new issue if you happen to find any bugs
