### ISSUE TITLE
sending multipart/mixed

### ISSUE THREAD

**Issue by Postalmon** [postmanlabs/postman-app-support#814]
Hi just wondering if sending multipart/mixed is supported and how I would go about in structuring the call for sending the file.

**Comment by willsthompson** [comment]
Huh? `multipart/mixed` and `multipart/form-data` are not the same, and Postman defaults to the latter with no apparent way to toggle to `mixed`. If it's possible, please explain how to do it; otherwise, I think you should reopen this ticket.

**Comment by willsthompson** [comment]
FYI, if you give curl form data via `-F` _and_ specify mixed in the header with `-H "Content-Type: multipart/mixed"`, it will still add the boundary identifiers automatically, but it will also overwrite the content type to be mixed. Postman ideally would just emulate that behavior.

**Comment by raksja** [comment]
Why is this closed? OP's statement is true. There is no way we could find to do multipart/mixed with a payload(application/json) and a file with postman. For example this curl command, cant be achieved in postman.
curl -i -X POST -H "Content-Type: multipart/mixed" -F "somepayload={\"name\":\"mypayloadname\"};type=application/json" -F "uploadfile=@somevalid.zip" http://localhost:8080/url

**Comment by rjherman2011** [comment]
Is there any update on this? We've got a specific feature that is waiting on this functionality.

**Comment by a85** [comment]
@rjherman2011 Not yet. multipart/mixed is not currently available in the UI.

**Comment by timasjov** [comment]
Any ETA on the feature?

**Comment by a85** [comment]
Tracking here: https://github.com/postmanlabs/postman-app-support/issues/1104. Closing this issue as a duplicate.
