### ISSUE TITLE
Folder descriptions aren't visible

### ISSUE THREAD

**Issue by emersonf** [postmanlabs/postman-app-support#816]
I've created folders which group related requests, and put a description on the folder to describe the group. It reduces the conceptual weight of the collection and avoids repetition. You can see an example [here](https://www.getpostman.com/collections/18e6065476d59772c748).

Is this folder description actually *shown* anywhere in Postman? The only place I can see it is if I edit the folder, but I can't expect users to do that. It should be displayed somewhere (right pane?) when the folder is selected.

**Comment by a85** [comment]
Available in Postman 3.0!

**Comment by emersonf** [comment]
I still don't see the descriptions and I'm running 3.2.20. Can you point them out please?
