### ISSUE TITLE
Improve swagger Import

### ISSUE THREAD

**Issue by plessbd** [postmanlabs/postman-app-support#820]
when importing a swagger spec with named parameters it is nice that they go into the build section.
However, it might be better to have a choice to import them as regular arguments so that they can be used with environments.

Also, it would be useful if the enums were imported as well as part of a dropdown instead of just a text field.

**Comment by abhijitkane** [comment]
@plessbd We've made a few updates to the swagger importer. Variables now have the default value set to an environment variable. Does this make it more user-friendly?
