### ISSUE TITLE
OAuth2 auth code grant type does not work with non-public domains

### ISSUE THREAD

**Issue by Vadi** [postmanlabs/postman-app-support#828]
POSTMan always returns "Could not initiate OAuth2 flow" when used with local urls such as -

http://127.0.0.1:9000/apps/authorize/
http://127.0.0.1:9000/oauth2/access_token/

Not sure if this is addressed in commercial version POSTMan.

**Comment by BraisGabin** [comment]
A possible workaround: allow to use the grant type `password`.

**Comment by joshperry** [comment]
I believe this issue should be closed since the "Request access token locally" feature was added.
