### ISSUE TITLE
File upload sends empty file

### ISSUE THREAD

**Issue by ewaltman** [postmanlabs/postman-app-support#838]
I've always been able to include files in my form-data using the Chrome App, but today, I noticed my own code complaining about empty files - I looked in to this a bit to make sure it wasn't on my end, and found that Postman is not creating the tmp files it is passing to my application code. I am on OS X and I've verified that the old version of Postman - the Chrome extension - is handling files normally.

**Comment by jurajpetrik** [comment]
Still not fixed

**Comment by a85** [comment]
Works for me with the latest version. 3.1.1. Closing this for now.

**Comment by afollestad** [comment]
Doesn't work in the latest version. I need interceptor on for cookies, which makes file uploads not work,

**Comment by abhijitkane** [comment]
@afollestad What version are you on? In v4.1.3, I'm able to upload files with the Interceptor on.

**Comment by afollestad** [comment]
@abhijitkane hmm, 4.1.2. Is that recent release? I'd expect Chrome to auto update it.

**Comment by abhijitkane** [comment]
Chrome's update works in weird ways. chrome://extensions -> Enable 'developer mode' > Update extensions now.

Does your filename have a space? Filenames without spaces should work in 4.1.2 as well.

**Comment by afollestad** [comment]
`Update extensions now` got it, thanks!

Files with spaces still don't work, the file is uploaded but the `Content-Length` is 0. However it worked when I removed spaces from the name.

**Comment by redbeandev** [comment]
Filename is shown as empty when generate code for phpcurl for me even after adding files

**Comment by redbeandev** [comment]
filename=\"[object Object]\" appears

**Comment by sdnts** [comment]
This should be fixed in the latest native app (4.7).
Files with spaces in their names should also be handled now. Can you guys confirm?

@redbeandev We'll check out the Code Generation issue.
