### ISSUE TITLE
FEATURE REQUEST: JSON Browser

### ISSUE THREAD

**Issue by boliusandreas** [postmanlabs/postman-app-support#840]
Hi guys - excellent tool - lovin'it!
Just an idea.. perhaps it would be easy to incorporate a json browser like https://github.com/rapee/jsonfinder or something like it.. I could be nice if it was possible to collaps/expand nodes in the received json.
Thanks again! 
Best from Copenhagen

**Comment by sdnts** [comment]
A JSON browser has been in the maintained Chrome & native apps for quite some time now. Closing this :)
