### ISSUE TITLE
Add color to the Status label based on HTTP response code

### ISSUE THREAD

**Issue by moberemk** [postmanlabs/postman-app-support#844]
Just a thought, but it might be nice to add color to the Status label in the response depending on the response code. So a 200-series response could be green and others could be red, say? It'd be a nice convenience feature to have to make the response window more easily skimmed.

**Comment by a85** [comment]
@moberemk Noted. Will take this up as part of our next UX overhaul.

**Comment by a85** [comment]
Closing as we'll probably open up customizations through a style guide in the future.
