### ISSUE TITLE
Content-Length Mismatch gives ambiguous response

### ISSUE THREAD

**Issue by johnnadratowski** [postmanlabs/postman-app-support#849]
So I recently ran into a problem where some of my API endpoints were returning a "Cannot get a response" page in Postman.  I figured out that this was caused by a code bug in our application that was overwriting the Content-Length header with an incorrect value.

I was banging my head on the wall sometime about this, until I ran the same endpoint though curl and I saw that it would complete my request, but would also tell me it wasn't reading a certain number of bytes sent back in the response body.

It would be beneficial to have some better output when the Content-Length (or perhaps even content-type) doesn't match the body.  I understand if you don't want to actually take action on this ticket, depending on the complexity of the implementation, but I also wanted to be a good OSS citizen by documenting it here.

Love the product, we're actually kicking around using the exported collections as part-and-parcel with our API documentation... makes it super easy to explore and share with other developers.

Thanks!

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We're working on a major UI revamp, and will certainly take this into consideration.

**Comment by a85** [comment]
@johnnadratowski Postman defers to the Chrome XHR object for sending calls and might be hard to find out the exact cause if the XHR object doesn't return a proper failure message. We'll see if we can add it somehow.

**Comment by grimmwerks** [comment]
Was just curious if this was added as I'm sort of coming up with the same issue for a rails api I'm working on (Content-Length is sometimes coming through as -1 even though there IS content) and having some issues debugging.

**Comment by numaanashraf** [comment]
@kunagpal let's verify if this is addressed in our latest runtime and close if so.

**Comment by a85** [comment]
@numaanashraf @kunagpal Any update on this?

**Comment by kunagpal** [comment]
@a85 I haven't checked yet, will have to get back to you on this.
