### ISSUE TITLE
JSON pretty print response crashes packaged app

### ISSUE THREAD

**Issue by rscottfree** [postmanlabs/postman-app-support#850]
I have a 1.7 MB JSON response that displays for a split second before the app crashes. Displaying it as Raw or Preview works fine. Pretty printing the XML response of the same data works fine.

Possibly related to #286 

Windows 8.1
Chrome version: Version 39.0.2171.95

Version 1.0.3 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by stevemcmillen** [comment]
I've not run into crashes yet but I also have many requests that return large json result sets (i.e. return 100 or more media records).  In these cases, the pretty print can take a very long time to render.  I'm just now scrubbing the tickets to find if someone has submitted a feature request to offer the old style pretty print ( no dynamic expand collapse options ) as an alternative to the new pretty print.  Old Postman used to offer this.  Oh the good old days ;)

**Comment by rscottfree** [comment]
I would welcome a more basic version of the pretty printer in order to go back to using postman for testing these large API calls.

**Comment by ahsteele** [comment]
This issue seriously impacts Postman's utility. I have several endpoints which return 5 megabytes of data and Postman just crashes when interacting with them.

**Comment by ToshioMagic** [comment]
+1 having issues with postman's pretty viewer. It is crashing on requests only a couple KB even though they are properly formatted.

**Comment by abhijitkane** [comment]
@ToshioMagic What version of Postman are you using? And do you see some sort of error message, or does Postman stop responding altogether?

**Comment by ToshioMagic** [comment]
@abhijitkane https://github.com/postmanlabs/postman-app-support/issues/1153

**Comment by mastakhov** [comment]
Same for me. If request contains binary data (e.g. file attachments) JSON prettification dramatically slows down or even freeze application.
Switching to "raw" fixes the issue, but "prettify" is the default view, so I end up with slow performance anyway.

**Comment by sdnts** [comment]
Guys, is this still an issue?

**Comment by ahsteele** [comment]
At about 11 megs things slow down significantly, but the application no longer crashes. Far from ideal, but not broken as it was previously.
