### ISSUE TITLE
How does one set multiple guids in a single request?

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/postman-app-support#851]
Using the {{$guid}} variable returns the same id in a single request. I'd like multiple guids to be available in a single request. 

--From https://twitter.com/xeromal/status/544595062118563840

**Comment by cadwmaster** [comment]
+1

**Comment by dvankooijk** [comment]
+1

**Comment by davenewza** [comment]
+1.  This seems like obvious behaviour and would be a quick win.

**Comment by davenewza** [comment]
Issue also on Newman https://github.com/postmanlabs/newman/issues/399

**Comment by sdnts** [comment]
Closing as this should be fixed in the latest native & Chrome apps (4.8.3)
