### ISSUE TITLE
UI slow on 1.0.3 with "big" history

### ISSUE THREAD

**Issue by ToastedJelly** [postmanlabs/postman-app-support#852]
Windows 8.1, 24GB mem,
Chrome 39.0.2171.95 m

Not sure if this is related - I haven't used Postman a while and needed it again about two/three weeks ago, but it was hanging even on freshly started computer or after killing the process and restarting the extension, so it was unusable.

Today I tried again and it seems to work, but the UI is very slow.
I have only about 20 requests in two collection, but the mouseover-highlight takes 1-3secs and if I click, it again delays for 1-3secs before actually opening the request details on the right side.

Alright, found the problem. It was the history. I only had a few hundred entries, but apparently this slows everything down, even if you don't see the list.
I switched to the history tab, which took 10+ seconds, cleared it, which took 20+seconds and now it's fast again.

Something must have changed in the code since I last used Postman, because the UI wasn't that slow with the same history.
And the hidden history shouldn't slow the whole UI down if not shown, no matter how big.

**Comment by a85** [comment]
This should not happen in the latest versions of Postman (3.0+). We have made a ton of performance improvements and the interface consistently renders at 60fps+.

**Comment by Alex-Werner** [comment]
OMG ! Thank you @ToastedJelly for your issue. I had the same problem on my Postman v.4.7.2. 
When I do not use postman for a day or two, it's getting super-slow to enter just : "https://" in the adress, we talk about something like 200-300 seconds. 

After reading this, I seek the history, found it, and clicked : delete all.
This took something like eternity (900seconds ~) 
It need a restart of Postman, and now it's working again <3 

But it seems that the case might need to be open again.
(If i worth mentioning, I didn't have THAT much history, we talk of maybe 100-200 or 300 calls).

(Windows 10
i5-6500 @ 3.2GHz
8GB Mem, 
Chrome 53.0.27)
