### ISSUE TITLE
Allow for Sorting of Collection Items

### ISSUE THREAD

**Issue by aewhite** [postmanlabs/postman-app-support#853]
Collections can get big and finding a particular request can get tedious. If collections were sorted by name then it would be much easier to find the desired request and it would allow for "poor man grouping" where like requests could be prefixed with a common "tag"

**Comment by kevinjalbert** [comment]
+1

**Comment by neowulf** [comment]
+1

**Comment by djehring** [comment]
+1

**Comment by a85** [comment]
Available in Postman 3.0
