### ISSUE TITLE
[1.0.3] Collection Runner executes tests in wrong order

### ISSUE THREAD

**Issue by hlship** [postmanlabs/postman-app-support#854]
My tests must run in a particular order, as earlier tests set environment variables used by later tests.  However, the collection running is choosing some other order.

![postman](https://cloud.githubusercontent.com/assets/52660/5493190/38a2cb9a-869d-11e4-8ad9-406151390da5.png)

![collection_runner](https://cloud.githubusercontent.com/assets/52660/5493200/6125ea02-869d-11e4-8e86-d41bd6e6b198.png)

I've tried re-ordering the requests manually, but that did not seem to affect things.

**Comment by treo** [comment]
We are experiencing the same problem. It worked at first, but then started to run in the wrong order.
 Is there a workaround?

**Comment by a85** [comment]
Should be fixed in version 3.0+.

**Comment by VictorK** [comment]
Using v3.2.15 windows version, noticing the same as treo, the initial run is correct but when you click "New run" it doesn't start from the beginning but in my case it always starts from the 24th request out of 33.

**Comment by abhijitkane** [comment]
@VictorK Can you send the collection (or any collection that helps you reproduce the issue) in question to help@getpostman.com?

**Comment by ElonGated** [comment]
@abhijitkane I'm having the same issue using v4.1.0 on mac. Was there any resolution to this issue?

**Comment by VictorK** [comment]
In my case the call I was making was dependent on a previous call completing which took about 5-9sec, I put a "sleep" statement in the pre-request script area of the 2nd call and all is well, not the ideal solution but it works.

On Wed, Mar 30, 2016 at 2:09 PM -0700, "ElonGated" notifications@github.com wrote:

@abhijitkane I'm having the same issue using v4.1.0 on mac. Was there any resolution to this issue?

**Comment by abhijitkane** [comment]
@ElonGated If you have Sync enabled, can you try signing out, signing back in, and then trying?

**Comment by ElonGated** [comment]
@abhijitkane Thanks for the reply! That doesn't seem to have helped. What I have determined is that if the collection has a failure at any point, when I try to run again the Runner will pick up at that failed call. So if I have a collection that goes [1, 2, 3, ...] and call #5 fails, when I try to run the collection again (without restarting collection runner) it'll pick up again from #5. If I restart the collection runner it'll start with call #1 as expected. 

I hope that helps make some sense of things.
