### ISSUE TITLE
[1.0.3] Collection Runner should make failures visible

### ISSUE THREAD

**Issue by hlship** [postmanlabs/postman-app-support#855]
When I get a failure in a request in the Collection Runner, I have no way to proceed. For requests with failed tests, CR should be able to capture the request/response and present it to me for analysis. All I have access to currently in the status code.

**Comment by blowsie** [comment]
I was thinking It would be great if I could filter the results in the GUI to show only failed tests.

I have over 1000 tests, and when only a few fail, it's hard to pick them out.

**Comment by bradobro** [comment]
I'd like to see test script exceptions also show up as failures in the UI. Right now there is a momentary message box that there was a script problem and the test is ignored. You'll see 3/3 passing instead 3/4 passing if one has a logic or syntax error.

**Comment by srbh21** [comment]
Hi team, I am not able to open the console window on postman in windows........Can some on help me for the same.....i am using ctrl+alt+c

**Comment by sdnts** [comment]
@srbh21 Are you on the Chrome App? The Chrome App does not have the Console yet. Can you try it on the native Windows App? You can download it [here](http://getpostman.com/apps).

**Comment by a85** [comment]
Should be possible with the native apps and the new Runner. Closing this.

**Comment by nowucca** [comment]
I'm only seeing test script failures if I open the run summary.  This seems wrong.

**Comment by itsgauravjain22** [comment]
I am also interested to have some way to put causing failure in reporting part in postman.

I am doing schema validation for each json response. 

tests["Schema is valid"] = tv4.validate(parsedResponse, jsonSchema);
console.error("Validation failed: ", tv4.error);

It would be great if there's some way to put causing error message in report instead of putting in console logs
