### ISSUE TITLE
Recursive variable resolution doesn't work for a variable's name

### ISSUE THREAD

**Issue by kbhutchinson** [postmanlabs/postman-app-support#856]
Recursive variable resolution is working fine in the case where a variable resolves to the brace-enclosed name of another variable.

This works:

    a = {{b}}
    b = c

When the request speficies `{{a}}`, "c" will end up being sent. Great!

However, it does not seem to work when *part* of a variable's name is another variable.

This does not work:

    server.a = www.google.com
    server.b = www.yahoo.com
    which = a
    server = {{server.{{which}}}}

Trying to send a request with `{{server.{{which}}}}` will send exactly that string. Variable interpolation fails.

My use case is that I have a four different servers that I want to send the same requests to, but I have different request details for each one. So I want to create one endpoint definition that will work correctly depending on the value of one certain variable. For example:

    server.a = server.a.com
    server.b = server.b.com
    auth.a = some-token-for-a
    auth.b = some-token-for-b
    which.server = a
    server = {{server.{{which.server}}}}
    auth = {{auth.{{which.server}}}}

With this request definition:

    http://{{server}}/some/endpoint?auth={{auth}}

That would let me easily switch servers by only changing one variable (`which.server`), rather than having one variable per setting that needs to be changed like this:

    server.a = server.a.com
    server.b = server.b.com
    auth.a = some-token-for-a
    auth.b = some-token-for-b
    server = server.a
    auth = auth.a

In this case, I'd need to change both `server` and `auth` before my request would work.

This is a simple case, but in reality I have many more parameters than auth that I would like to save per-server and be able to switch between servers in all my request definitions at once.

**Comment by a85** [comment]
This will be fixed with collection-v2: https://github.com/postmanlabs/postman-collection

**Comment by a85** [comment]
@czardoz @shamasis  Still valid?

**Comment by sdnts** [comment]
@kbhutchinson This shouldn't be an issue in the latest Postman App (4.8).
Feel free to reopen if this still happens for you :)
