### ISSUE TITLE
[1.0.3] Remember last execution parameters in Collection Runner

### ISSUE THREAD

**Issue by hlship** [postmanlabs/postman-app-support#857]
I seem to have to keep selecting my collection and environment every time I run the CR, but it's pretty standard for a developer to keep running the same series of tests ad nauseum.

**Comment by veggiesaurus** [comment]
I find this very frustrating in 3.0. Hoping for a fix soon

**Comment by centur** [comment]
As an extra feature request - allow mark collections with something like 'Require environment' flag, so Runner will freak out if selected collection doesn't have any Environment. Right now it simply runs it and spinning wheel hangs indefinitely. Looks like a bug to me.
