### ISSUE TITLE
Feature Request : add encrypt / decrypt additional url

### ISSUE THREAD

**Issue by kerlw** [postmanlabs/postman-app-support#858]
Some API accept encryted data only, and response is encrypted. So it's hard to test these apis by using POSTMan.
I think POSTMan could add two input, in fact two url, one used to encrypt , one used to decrypt. And then, we could use POSTMan to encryt by querying the encrypt-url before post data, and decrypt response by querying the decrypt-url before show the response.

**Comment by abhijitkane** [comment]
You can use the collection runner for this. Check the docs at https://www.getpostman.com/docs/jetpacks_running_collections

You can have 3 requests in order - the one used to encrypt your data, the actual request, and one used to decrypt your data. You can use environment variables to persist data across requests.

**Comment by tristaneniyan** [comment]
how an request will encrypt the upcoming actual request. it'll execute any encryption mechanism or postman will do the encryption. if postman does the encryption can we change that encryption mechanism by using our own encryption mechanism.

**Comment by proflinksgh** [comment]
I'm wondering how I can encrypt and decrypt request in Postman

**Comment by Romerolweb** [comment]
I agree

**Comment by Romerolweb** [comment]
Have a nice day!. 
Postman is a excellent tool.
