### ISSUE TITLE
Improvement: Submit button at the top of environment edit window

### ISSUE THREAD

**Issue by yurik** [postmanlabs/postman-app-support#859]
I have tons of variables setup for my environments and some I have to update frequently. It's very inconvenient to scroll down for Save changes. Can you implement Submit button at the top of that window?
![submit button top](https://cloud.githubusercontent.com/assets/697951/5572137/b6e6dc8a-8f4e-11e4-9784-faf4c3fc89bf.png)

**Comment by abhijitkane** [comment]
We're working on a major UI overhaul, and saving environments will certainly be a lot easier. I'll keep this thread updated.

**Comment by aditikul** [comment]
@yurik @abhijitkane The latest updates ensure that the submit button is always visible and doesn't require a scroll to find. Closing this issue, thanks for reporting.
