### ISSUE TITLE
Ability to create request from Chrome dev tools Network tab 

### ISSUE THREAD

**Issue by gregmac** [postmanlabs/postman-app-support#86]
Would be nice to be able to create a request by eg, right-clicking a request in the Network tab and being able to open it in Postman. This would help with debugging AJAX requests and applications, and quickly being able to replicate (and then modify) a request generated by an AJAX application.

**Comment by epelc** [comment]
+1 I tried using the import curl command option but that didn't work. This would be 10x better though

**Comment by abhijitkane** [comment]
Can you give a specific example of a curl command that doesn't work?

**Comment by epelc** [comment]
@abhijitkane I just tried with the beta you mentioned above and it partly worked.

My api is on a subdomain(api.mysite.com) so I have CORS enabled. However only the options request worked when I tried to get it from chrome the post request wouldn't work. I kept getting `Error: zero or multiple optionless arguments`

Heres an example command(I removed some json/sitenames as this isnt public yet). But besides that I got everything from the copy request as cURL in chrome.
```
curl "http://api.dev.mysite.net/some/endpoint" -H "Origin: http://dev.mysite.net" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" -H "Pidtoken: secretTokenHere" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Referer: http://dev.mysite.net/some/page" -H "Connection: keep-alive" -H "DNT: 1" --data-binary "My json here" --compressed
```

**Comment by abhijitkane** [comment]
What version of Postman are you on?
I was able to import it w/o any problem - http://puu.sh/eyrJ1.png

**Comment by epelc** [comment]
Opps the command above seems to work for me too in 0.10.5.6 However if I dont remove my json it fails. I think it doesn't like my empty fields.

```
curl "http://api.dev.mysite.net/quotes" -H "Origin: http://dev.mysite.net" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" -H "Pidtoken: secretToken" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Referer: http://dev.mysite.net/quote/recent/estimate" -H "Connection: keep-alive" -H "DNT: 1" --data-binary "{""CurrentTeamId"":"""",""Origins"":[{""Id"":""5464bd277ff7c30dfc000004"",""Enabled"":true},{""Id"":""54665cb17ff7c32090000001"",""Enabled"":false},{""Id"":""546a23887ff7c303d0000005"",""Enabled"":false}],""Destination"":{""Country"":""CA"",""City"":""Perth"",""State"":""ON"",""Zipcode"":""K7H 0A1"",""Lat"":44.90488,""Lng"":-76.25936990000002},""Commodities"":[{""Id"":""549984f8003645669d000002"",""Units"":1,""Name"":""Wood"",""Class"":""55"",""Nmfc"":""112870"",""Sub"":""03"",""Weight"":2500,""Type"":""PLT""}],""Options"":{""PickupDate"":""2015-01-15T16:34:26.890Z""}}" --compressed
```

**Comment by abhijitkane** [comment]
Enclose your JSON with '...' instead of "..."
The double quotes in the JSON interfere with the double quotes of the curl arguments

Import-able curl command:
`curl "http://api.dev.mysite.net/quotes" -H "Origin: http://dev.mysite.net" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" -H "Pidtoken: secretToken" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Referer: http://dev.mysite.net/quote/recent/estimate" -H "Connection: keep-alive" -H "DNT: 1" --data-binary '{""CurrentTeamId"":"""",""Origins"":[{""Id"":""5464bd277ff7c30dfc000004"",""Enabled"":true},{""Id"":""54665cb17ff7c32090000001"",""Enabled"":false},{""Id"":""546a23887ff7c303d0000005"",""Enabled"":false}],""Destination"":{""Country"":""CA"",""City"":""Perth"",""State"":""ON"",""Zipcode"":""K7H 0A1"",""Lat"":44.90488,""Lng"":-76.25936990000002},""Commodities"":[{""Id"":""549984f8003645669d000002"",""Units"":1,""Name"":""Wood"",""Class"":""55"",""Nmfc"":""112870"",""Sub"":""03"",""Weight"":2500,""Type"":""PLT""}],""Options"":{""PickupDate"":""2015-01-15T16:34:26.890Z""}}' --compressed`

Also, why does you JSON have double double-quotes?

**Comment by epelc** [comment]
I don't know maybe it's because I'm using angular. But I just hit copy as curl command in chrome from one of my requests. Thanks for the info though.

**Comment by ilanbiala** [comment]
Will this use the same address and context of the tab we're working from?

**Comment by abhijitkane** [comment]
The import will create a chrome request that mimics copying and running the curl command from your terminal.

**Comment by ilanbiala** [comment]
Is there any way to get it to use the same address and context of the tab we're working from?

**Comment by abhijitkane** [comment]
AFAIK, that wouldn't really be curl. curl commands are self-contained, and must contain the complete URL.

**Comment by Jadro007** [comment]
would be really awesome, please implement it :)

**Comment by kkartch** [comment]
+1

**Comment by lucasrcosta** [comment]
+1

**Comment by clementdubois** [comment]
:+1:

**Comment by jarnaiz** [comment]
+1

**Comment by ValterSantosMatos** [comment]
+1000

**Comment by abhijitkane** [comment]
@ValterSantosMatos @jarnaiz @clementdubois @lucascosta @kkartch @Jadro007 You can export the request from the network tab as curl (right click on the request > Copy as Curl), and import the curl command in Postman (Click the "Import" link in the top bar > Paste raw text > Import)

**Comment by Elyahou** [comment]
+32

**Comment by in2lag** [comment]
+1

**Comment by raygig** [comment]
+1

**Comment by pacwoodson** [comment]
@abhijitkane This doesnt work for me.

Error: 

> "Zero or Multiple options-less arguments, only one is supported"

When I try to import a POST request with headers, body ...

**Comment by abhijitkane** [comment]
@pakokrew Can you post the curl command you're trying to import?

**Comment by pacwoodson** [comment]
Yes : 

```
curl 'https://sub.domain.com/service.svc/GetData' -H 'APP: 9' -H 'Origin: https://sub.domain.com.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Authorization: Token a' -H 'Accept: application/json, text/plain, */*' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36' -H 'Referer: https://sub.domain.com/Reports/' -H 'Cookie: xtan425423=15-554207; xtant42925=1; xtvrn=$34725429023$' -H 'Connection: keep-alive' -H 'Content-Type: application/json;charset=UTF-8' --data-binary $'{"Context":{"ApplicationId":13,"CacheMode":null,"Caller":9,"Interne":false,"Email":"hello","Token":"cLzdHZA==","UserId":53,"lang":1,"DocumentId":"9f","SiteId":564353},"Request":{"BoxData":{"Data":{"Url":"&coa=5&filter={views:{$gt:\'0\'}}&period={R:{D:{start:\'-366\',end:\'-1\'}}}&evo={D}"}}}}' --compressed
```

I had to change the data

**Comment by abhijitkane** [comment]
Try this:

```
curl 'https://sub.domain.com/service.svc/GetData' 
-H 'APP: 9' 
-H 'Origin: https://sub.domain.com.com' 
-H 'Accept-Encoding: gzip, deflate' 
-H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' 
-H 'Authorization: Token a' 
-H 'Accept: application/json, text/plain, */*' 
-H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36' 
-H 'Referer: https://sub.domain.com/Reports/' 
-H 'Cookie: xtan425423=15-554207; xtant42925=1; xtvrn=$34725429023$' 
-H 'Connection: keep-alive' 
-H 'Content-Type: application/json;charset=UTF-8' 
--data '{"Context":{"ApplicationId":13,"CacheMode":null,"Caller":9,"Interne":false,"Email":"hello","Token":"cLzdHZA==","UserId":53,"lang":1,"DocumentId":"9f","SiteId":564353},"Request":{"BoxData":{"Data":{"Url":"&coa=5&filter={views:{$gt:0}}&period={R:{D:{start:\'-366\',end:\'-1\'}}}&evo={D}"}}}}' 
--compressed
```

I had to change the `$gt:\'0\'` to `$gt:0`

**Comment by pacwoodson** [comment]
Ok thanks, but is it chrome that isn't creating correctly the curl, or postman that can't read it ? There are others escaped strings after that works:  `{start:\'-366\',end:\'-1\'}`

**Comment by abhijitkane** [comment]
This seems to be a limitation of Postman's curl importer. We'll work on this soon.

**Comment by overture8** [comment]
+1

**Comment by rosay** [comment]
+1

**Comment by Windfarer** [comment]
+1

**Comment by afaricamp** [comment]
+1

**Comment by coudron** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by draffensperger** [comment]
+1

**Comment by welcoMattic** [comment]
+1

**Comment by cjpetrus** [comment]
+1

**Comment by sobanieca** [comment]
+1

**Comment by DoctorQ** [comment]
+1

**Comment by Asarew** [comment]
+1

**Comment by kariudo** [comment]
This issue should be closed. This is already implemented. Just Copy as Curl and paste into the Import as text box.

**Comment by a85** [comment]
We recommend using the copy as curl feature now or the Interceptor. https://twitter.com/adrian_philipp/status/710438593936932864

No other way to do this.
