### ISSUE TITLE
Saving requests in a collection

### ISSUE THREAD

**Issue by miraculixx** [postmanlabs/postman-app-support#860]
When saving a request to a collection, Postman throws this JS error:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'order' in undefinedrequester.js:782 (anonymous function)requester.js:2711 cursorRequest.onsuccess
```

Once this happened, you can still use Postman to send requests, but none of them will be saved to the history, or to a collection (they appear to be but in fact are not) => Restarting Postman will have the history and collections without these requests.

This is on Linux with Google Chrome Version 39.0.2171.71 (64-bit) and Postman 0.8.4.11

**Comment by abhijitkane** [comment]
Are there any other errors in the console? 
This shouldn't happen with a new collection, and I'm not able to replicate the issue.
Reinstalling the app will clear your indexedDB, but you'll also lose all your data.

I would suggest exporting all your data (the 'Download all data' button is to the right of the Postman logo in the top-left), and using the packaged app (https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en) to import it.

**Comment by ewendel** [comment]
I am getting the exact same error. 

Chrome Version 39.0.2171.95
Windows 7
