### ISSUE TITLE
Oauth1.0 auto add parameters

### ISSUE THREAD

**Issue by pepinfarb** [postmanlabs/postman-app-support#871]
It seems the auto add parameters does not refresh the nonce/timestamp, etc as expected.
When I recall a saved query, I end up having to switch to another tab (away from oauth) and back in order for those to update) before sending the request. 
I am not sure if this is in the extension, but it is happening in the stand alone version

**Comment by abhijitkane** [comment]
What version are you using? You'll need to check the 'Save helper data to request' box and click 'Save' to save the OAuth inputs with the request. Then if you re-load the request from the collection sidebar and send it, the timestamp and nonce are renewed.

**Comment by therightstuff** [comment]
I have "save helper data to request" checked, and every time i switch to a different saved request (all running with the same parameters) the first call fails because the oauth_timestamp is not updated until a response is received (the subsequent calls work fine).
Is the timestamp only updated when the response is received?

**Comment by abhijitkane** [comment]
No, you don't even need to send the request. If a request r1 has the helper data saved, and r2 doesn't, r1's oAuth1 timestamp and nonce change as soon as you switch from r2 to r1.

When you send r2, the timestamp and nonce are updated again.

Import this collection - https://www.getpostman.com/collections/f585c83e6d768f4bb612, and try switching b/w r2 and r1. The OAuth timestamp and nonce should be updating every time you switch to r1.

**Comment by therightstuff** [comment]
You're absolutely right, if I switch to a request that has helper data saved from a request that doesn't, the timestamp is updated correctly. The moment I switch from a request that *also* has helper data saved, however, the timestamp no longer updates.

**Comment by abhijitkane** [comment]
Got it. We'll fix this in the next release.

**Comment by therightstuff** [comment]
Great! Thanks.

**Comment by frickenate** [comment]
As an aside, would it be possible to collapse the helper dialogs when auto-add is enabled? It's very annoying to have for example the OAuth information always visible, which requires us to scroll every time to click the "Send" button, and then scroll again to view the response. When auto-add is enabled, the window should look the same as when you have it disabled and click "Refresh request" - the OAuth information is hidden but the auth is enabled.

Then we can just click the send button over and over without the OAuth information taking up the full vertical space of the window. It's very frustrating to have something you don't need to see or modify taking up all screen space at all times.

**Comment by pepinfarb** [comment]
Glad I wasn't imagining the original issue.

Agreed on the annoying scroll issue.

When is the next release planned?

**Comment by abhijitkane** [comment]
We're working on a major UI revamp. The scrolling fix will be part of that. 

The next release (which will fix the OAuth params not changing) will be made in a few days.
