### ISSUE TITLE
Feature: Html preview with javascript support

### ISSUE THREAD

**Issue by LazyTarget** [postmanlabs/postman-app-support#872]
An Html preview with javascript support for able to running the javascript code that displays the json data returned

**Comment by zarembas** [comment]
This would be really nice +1

**Comment by viebel** [comment]
I'm also interested in this feature

**Comment by a85** [comment]
I don't think we will be able to run Javascript in preview mode any time soon. Introduces a whole host of data capture attacks. Will re-open in the future once we have more time.

**Comment by SteamWind** [comment]
That could be a button that accept Javascript after the request send?
User is then responsible for his use...
With this we can't even navigate [filp/whoops](https://github.com/filp/whoops)
