### ISSUE TITLE
POST form-data file sends even if GUI field is unchecked

### ISSUE THREAD

**Issue by ewaltman** [postmanlabs/postman-app-support#873]
I have a field in my form-data called "csv". If I upload a file as the value of "csv", then my request will include that file whether or not I deactivate the field via its checkbox. 

![screen shot 2015-01-12 at 3 47 44 pm](https://cloud.githubusercontent.com/assets/2886892/5710725/6d8decfc-9a72-11e4-9646-0d5533b8adf4.png)

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. Is this persisting across app restarts?

**Comment by ewaltman** [comment]
Yes - for me it's persisting across restarts. Here is what I'm running:

Version 1.0.4 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
@ewaltman Are you still seeing this in v3.0.4?
