### ISSUE TITLE
REST API with HMAC authentication

### ISSUE THREAD

**Issue by Aldekein** [postmanlabs/postman-app-support#874]
I am a developer and I am looking for some software to provide our QA for testing REST API that requires SHA1 HMAC authentication. Each request is signed using user's secret key using this algorithm - https://github.com/mgomes/api_auth#how-it-works

I could not set up request signing as required in Postman. Did I miss something or this cannot be done because it's not OAuth?

**Comment by abhijitkane** [comment]
It's not possible using the Auth Helpers. You could write your own script in the pre-request script section, and generate the Authorization header on-the-fly.

**Comment by esambo** [comment]
Perhaps try a combination of [pre-request script](http://sqa.stackexchange.com/questions/11777/testing-rest-api-with-sha1-hmac-authentication#answer-14046) and [httpie-api-auth](https://github.com/pd/httpie-api-auth/blob/master/httpie_api_auth.py)

**Comment by a85** [comment]
Custom auth can be written using pre-request scripts at the Collection level now.
