### ISSUE TITLE
Not able to specify HTTP Protocol Version in PostMan

### ISSUE THREAD

**Issue by zeeshanjan82** [postmanlabs/postman-app-support#876]
I am not able to specify protocol version for http in Postman like I can easily do in Fiddler.

Any Idea?

**Comment by abhijitkane** [comment]
As far as I know, it's not possible to specify the HTTP version when using the XHR object. The browser uses 1.1 be default.

**Comment by skytraveler** [comment]
The need of specifying HTTP Protocol Version is common,I think. Kindly please add it to Postman features.

**Comment by asarkar** [comment]
Opened https://github.com/postmanlabs/postman-app-support/issues/6242. Postman now has a desktop version, so what the browser does is irrelevant.
