### ISSUE TITLE
not able to use dynamic variables like {{$guid}} inside the pre-request script

### ISSUE THREAD

**Issue by ArunMonySpin** [postmanlabs/postman-app-support#886]
I tried the following in the pre-request script 

postman.setEnvironmentVariable("variable_key", {{$guid}} );

  but then the script just wont execute, when clicking on "send" nothing happens, no request is fired.

**Comment by abhijitkane** [comment]
$guid is already an environment variable.

You can use {{$guid}} directly in your URL/headers.

When there's an error in the pre-request script, it'll show up as a red cross in the editor (next to the line number). We'll add a proper notification in the coming release.

**Comment by ArunMonySpin** [comment]
hmm. I am not sure whether I agree with the statement that $guid is already an environment variable. from my understanding its a dynamic variable. Now are you saying that all dynamic variables are environment variables ? in that case , my question would be why not it be a global variable then ?? 

 for me a dynamic variable was something which I could place anywhere and when the section/script containing the same gets executed it will return a value (or replaced by a value based on what it stands for(its definition)), in this case a GUID. infact in a true sense one should not be even calling this as a variable, since a variable is something which you can refer to using a reference like a variable name, a variable typically has two parts right a name and a value right. 


 But the reason why I want to assign this dynamic variable to an environment variable is to get a handle to the same (i.e. the name part of the name-value pair of a variable), so that I could reuse it across other related calls. 


  I also wonder that if this is an environment variable then why does it not appear in the “manage settings popup” of the corresponding environment.  

 
   I think it might be better called as “dynamic value” than as “dynamic variables”, but for that you also need to allow the placing of the same in pre / post  scripts. 


Thanks
Arun Mony

**Comment by abhijitkane** [comment]
By "already an environment variable", I meant that it can be used as environment variables are used - you don't need to call `setEnvironmentVariable()` separately.

Otherwise, you're right - it's not part of any environments that are visible in the menu.

Currently, there is no way to save a guid to an environment. But, you can use something like this:

```
var guid = (function() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
               .toString(16)
               .substring(1);
  }
  return function() {
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
           s4() + '-' + s4() + s4() + s4();
  };
})();
postman.setEnvironmentVariable("variable_key",guid());
```

**Comment by ArunMonySpin** [comment]
I am not convinced with the solution provided. But I do agree that what you have provided is an alternative.  But Please do think about treating dynamic variables as sort of place-holders, which are replaced inline at run-time. 


Thanks
Arun Mony

**Comment by GianniBortoloBossini** [comment]
Reading the [issue 337](https://github.com/postmanlabs/newman/issues/377), it suggests that you can generate a guid into pre-request scripts using $guid dynamic variable if you put it into a string.

So: 
- if you need a the guid from your URL, header or body you can use `{{$guid}}`;
- if you need the guid into a pre-request script to set an environment variable to use it into your next tests, use `postman.setEnvironmentVariable("MY_GUID", "{{$guid}}");`.

**Comment by lsloan** [comment]
Since the `{{$guid}}` value isn't available as a variable, I'm unable to use its value in post-request tests.  Please allow something like `postman.setEnvironmentVariable('variable_key', '{{$guid}}' );`.  If the interpretation of `{{$guid}}` isn't possible here, then provide a function (e.g., `pm.getUuidV4()`) that provides a UUID value of the same kind that's used for that dynamic variable.  Then it could be used as, `postman.setEnvironmentVariable('variable_key', pm.getUuidV4());`

**Comment by lsloan** [comment]
I noticed some of Postman's internal JavaScript calls `uuid.v4()` to set a value for `{{$guid}}`.  I took a chance that `uuid` is a module that can be required and it worked.  So, I use this in my collection's pre-request script:

```js
var uuid = require('uuid');
pm.globals.set('eventId', 'urn:uuid:' + uuid.v4());
```

Then, in my request body, I can refer to it as:

```txt
{{eventId}}
```

And I can refer to it in the request's test script, too:

```js
var eventId = pm.globals.get('eventId');
```

Unfortunately, defining it in the collection pre-request script means that all references to `eventId` by each request in the same collection get the same value.

Ideally, Postman should (this is probably a different issue):

1. Let global variables refer to functions that get evaluated each time they're referenced.
    ```js
    var uuid = require('uuid');
    pm.globals.set('eventId', function() {return 'urn:uuid:' + uuid.v4();});
    ```
1. Let function definitions in a collection's pre-request script be called in a request's pre-request script.  That way, we wouldn't need to copy the same `pm.globals.set('eventId',…)` code into every every request's pre-request script.

**Comment by a85** [comment]
Closing the issue. We recommend the workaround + using pre-request scripts + collection variables to generate dynamic variables. Updating the Javascript sandbox to support a special syntax is something that we are not going to do. We are working on extending the sandbox to support external libraries #1180. This should help with more flexibility on the syntax.

**Comment by MuckT** [comment]
Instead of trying to assign the dynamic variables to environmental variables in the pre-request script, which fails, try saving the request.data to an environmental variable and comparing the response based off that.

Request body to 'https://postman-echo.com/post'
```
{
    "guid": "{{$guid}}",
    "timestamp": {
    	"nested": "{{$timestamp}}"
    }
}
```
Postman tests
```
pm.environment.set("requestData", request.data);
// Check the data
console.log(JSON.parse(pm.environment.get('requestData')).guid);
console.log(JSON.parse(pm.environment.get('requestData')).timestamp.nested);

pm.test('Test data from environment should match response body', function () {
    // Save the response body as JSON
    var jsonData = JSON.parse(responseBody);
    // Test vs environmental variables 
    pm.expect(JSON.parse(pm.environment.get('requestData')).guid).to.equal(jsonData.data.guid);
    pm.expect(JSON.parse(pm.environment.get('requestData')).timestamp.nested).to.equal(jsonData.data.timestamp.nested);
});
```

**Comment by moto83** [comment]
This is working for me just fine:
pm.environment.set('unitsName', pm.variables.replaceIn('{{$randomFirstName}}'));
