### ISSUE TITLE
Saving of Basic Authentication Header in Between Requests

### ISSUE THREAD

**Issue by benmalinowski** [postmanlabs/postman-app-support#893]
As a user I would like to be able to use the same authorization header to pass more than one request. I currently have to click on the Basic Auth tab each time I choose a new request from my collection and click "refresh headers." The previous version of Postman would allow me to click refresh headers once and remember it until I needed to make a change. Also I am no longer prompted to enter in my credentials If I don't create a header before hitting send. The non packaged version would ask me to enter in my credentials at that point and then add it to the authentication header. 

![basicauth](https://cloud.githubusercontent.com/assets/10727361/5921561/d5218e22-a612-11e4-83c7-5d24aea514c6.JPG)

**Comment by abhijitkane** [comment]
One workaround that you can try is saving the Authentication header value to your environment, say, authValue, and adding it to each of your requests (Header key: Authorization  value: {{authValue}} )

**Comment by a85** [comment]
This is available in Postman 3.0.
