### ISSUE TITLE
FEATURE REQUEST: Fold/collapse data of embedded base64 strings

### ISSUE THREAD

**Issue by Wilt** [postmanlabs/postman-app-support#895]
I am using POSTMan with an API that also returns images encoded as base64 strings. This leads to enormous long response in my window and makes it hard to debug and find the relevant objects. It would be really awesome to somehow collapse the data for base64 strings. It might be possible to find those with a regular expression, but otherwise a feature for hiding response objects with a length larger then X (where X can be a custom setting in the extension) would also work.
Otherwise an option would be to give a list of response keys I want to collapse.
So in this case I could set keys like 'image', 'avatar' and 'picture' to collapse.

The reponse could look like this where clicking on the [click to expand] button would unfold the collapsed base64 content.

```
{
    "image": "data:image/png;base64, [click to expand]...
    ... other properties ...
}
```

**Comment by sweetw0r** [comment]
+1

**Comment by a85** [comment]
Closing this as we don't expect to be able to do this any time soon.
