### ISSUE TITLE
Postman setting import of JetPacks javascript is converting new lines into actual new line

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#898]
I exported my settings and then imported.  This resulted in the new lines in the file being turned into actual new lines which created blocking errors in the javascript code.

For example.  Following line is in the exported Postman dump:
> console.log("\n\n\n\n");

When imported, the line is converted into this (which throws error in JetPacks:

> console.log('
> 
> 
> 
> ');

**Comment by abhijitkane** [comment]
What part of the dump is that line in? Is it part of a test or pre-request script?

**Comment by stevemcmillen** [comment]
In the "tests" section

**Comment by stevemcmillen** [comment]
I tried editing the postman dump file and escaping the new line again as follows:
> console.log("\\n");
But this imports as:
> console.log("
> ");
I also tired:
> console.log("\\\n");
But this imports as:
> console.log("\
> ");

I'll disable the new lines for now since it corrupts the script but they were pretty useful in the logging output to separate sessions.

**Comment by abhijitkane** [comment]
Right. We'll push a fix in the next release.

**Comment by stevemcmillen** [comment]
Thanks much!!

**Comment by abhijitkane** [comment]
@stevemcmillen Can you confirm this fixed in v3.0.4?

**Comment by stevemcmillen** [comment]
Fixed.  Thanks!
