### ISSUE TITLE
Bluk edit in evironment is not saving updates

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#899]
Seems the bulk edit option in the environment dialog is not saving.  This is the little button at the bottom right of the Environment edit dialog where you can click and edit all the env variables in a single text region.  

When I click this and edit, and then save all the edits, the window no longer pops back to the env edit dialog with changes showing.  Instead you see the main Environments list and the change does not get saved.  

This must have broken relatively recently.  Last time I used this was late December I think.

Seems that on a related issue, the Env edit dialog closes unexpectedly often w/o saving.  I just move the mouse to some area and the dialog closes suddenly.  

I also see that clicking the Add button on Env opens an existing environment.  

Since this is hard to explain, here is a picture:

First I click the bulk edit button:
![bulk edit button](https://cloud.githubusercontent.com/assets/2750330/5987269/fbc969da-a8d5-11e4-87a9-4745ac6f66f2.png)

This opens the bulk edit dialog as expected:
![bulk edit dialog](https://cloud.githubusercontent.com/assets/2750330/5987275/1414a93c-a8d6-11e4-9cda-942f5ba0aaab.png)

But now I move the mouse just a little bit and the background dialog pops back to main Env's list:
![bulk edit dialog with background dialog closed](https://cloud.githubusercontent.com/assets/2750330/5987277/205ef288-a8d6-11e4-8f45-807ecb10a94d.png)

So at this point, anything I save in the bulk edit dialog is lost.

So the problem seems to be that mouse moves close the dialog and this is triggering bad behavior.  I've tried this on 2 machines so far.  Both same behavior.  All on Mac OS so maybe a Mac OS / chrome thing.

**Comment by stevemcmillen** [comment]
I have more info.  Seems that any time the mouse cursor moves outside the region of the formost dialog then the dialog in the background closes and any save does not persist.

So in this case, I have 3 dialogs open
background: Environments dialog
1 level above that: Edit Env GUI mode
Topmost level: Batch Edit Env

If I move the mouse outside of the Batch Edit env dialog, it closes the "Edit Env GUI mode" dialog. This is probably related to the code that closes dialog when you click outside them.

**Comment by abhijitkane** [comment]
For some reason, the mouseout event of the bulk edit icon is triggering the modal close. We'll push a fix soon.

**Comment by stevemcmillen** [comment]
Thanks again.

**Comment by abhijitkane** [comment]
@stevemcmillen Can you confirm this fixed in v3.0.4?

**Comment by a85** [comment]
Seems to be working now.
