### ISSUE TITLE
Feature Request: Loading collections from filesystem

### ISSUE THREAD

**Issue by steffenbrand** [postmanlabs/postman-app-support#900]
It would be very helpful if POSTMan could load collections directly from the filesystem. So if I change my API and also my POSTMan collection, I can make it part of my project, commit it and everybody in my team is getting the new collection (new and/or changed functions) after pull request.

**Comment by nick-ta-mere** [comment]
a feature like that would be really great!

**Comment by drgrieve** [comment]
This is exactly what we need also. Sharing is such a pain at the moment.

**Comment by a85** [comment]
We recommend joining the Postman Sync beta that would provide seamless sharing. Details here: www.getpostman.com/beta. Sync to Github is also on it's way.
