### ISSUE TITLE
form urlencoded data only transmits first value when keys repeat

### ISSUE THREAD

**Issue by abadyan** [postmanlabs/postman-app-support#901]
Hi,
I'm using the latest version (0.2.8) and Postman (1.0.8) and trying to intercept data sent via form url encoding.
One of the keys is repeating because I need to send an array. The intercepted result is that only the first sent key was intercepted, the others ignored.

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We'll push a fix soon.

**Comment by abhijitkane** [comment]
@abadyan Can you confirm this fixed in Interceptor v0.2.10 and Postman v3.0.4?

**Comment by abadyan** [comment]
Looks like it works now, thanks (Y)
