### ISSUE TITLE
Reset button does not clear x-www-form-urlencoded parameters of POST

### ISSUE THREAD

**Issue by blievens** [postmanlabs/postman-app-support#902]
When you press the "Reset" button after you setup POST request with x-www-form-urlencoded parameter the form resets to default GET method, but when switching to POST you can see the  x-www-form-urlencoded are still filled in.

It looks like for POST only "form-data" gets cleared but not "x-www-form-urlencoded" and "raw" parts.
Same behaviour occurs when switching between requests in collection. When switching from POST with x-www-form-urlencoded parameters to other request the parameters are not cleared. 

Setup used : Mac OS X Yosemite v 10.10.1 with Chrome Version 40.0.2214.94 (64-bit) and Postman - REST Client 0.8.4.12 .

**Comment by a85** [comment]
Should be fixed in the latest version of Postman.
