### ISSUE TITLE
button to add a new empty endpoint

### ISSUE THREAD

**Issue by yehosef** [postmanlabs/postman-app-support#908]
Currently to create a new endpoint you need to either press <alt>-N or take an existing endpoint, modify it and add to collection. Even when I press <alt>-N I have a new empty endpoint not in any context. I then need to add to collection to add it to the right collection.

I think a better user experience would be to be able to click on a + on each folder/collection level to create a new endpoint directly in that folder or collection.  Ideally the title would be editable from the left panel and I could write the name there instead of dealing with the "add to collection dialog".  If you have several projects with many collections and folder, the process of finding the folder I want (over and over again for each new endpoint) is very tedious.

Also it would be nice is the <alt>-N would be context sensitive to add a new endpoint in the folder that is currently active.

**Comment by sankalp0o** [comment]
@yehosef We now have an option of creating a new endpoint directly in a collection/folder from the context menu in the sidebar. Though this is still one click more than your idea of a '+' icon, we didn't want to clutter the sidebar. Hope this makes your work easier.
