### ISSUE TITLE
variable should support multiple values

### ISSUE THREAD

**Issue by yehosef** [postmanlabs/postman-app-support#909]
Sometimes there are certain variables which have defined values and it would be nice if I could specify the possible values and then choose from them when using the variable.

![postman](https://cloud.githubusercontent.com/assets/149253/6058496/833d6c00-ad30-11e4-91db-105f7926fe48.png)

This would help a lot

**Comment by abhijitkane** [comment]
We're working on a major UI revamp, and will have an update on this soon.

**Comment by yehosef** [comment]
great - looking forward to it!

**Comment by a85** [comment]
I think what we need here are enums. That is on the long term roadmap for variable type support. For now, you can switch values in the following ways:

1. Switch environments completely
2. Switch variables themselves. All values now have autocomplete to let you switch between different pre-defined variables that works pretty much like enums.
