### ISSUE TITLE
different result of soap response xmlToJson(responseBody) in Postman vs Newman

### ISSUE THREAD

**Issue by j19sch** [postmanlabs/postman-app-support#912]
When parsing a soap response using in the Test editor:
```
var data = xmlToJson(responseBody);
```
The following test can be parsed by Postman, but not by Newman:
```
tests["DisplayName is correct"] = data.envelope.body.GetCompanyIfExistsResponse.Account.DisplayName.__cdata === "NewCompany";
```
with Newman giving the following error:
_EXCEPTION - TypeError: Cannot read property 'body' of undefined_

And the following test can be parsed by Newman, but not by Postman:
```
tests["DisplayName is correct"] = data['soap:Envelope']['soap:Body']['tns:GetOrCreateCompanyResponse']['Account']['DisplayName'] === "NewCompany";
```
In this case Postman does suggest to use dot notation for the non-namespaced xml-tags. i.e.
```
tests["DisplayName is correct"] = data['soap:Envelope']['soap:Body']['tns:GetOrCreateCompanyResponse'].Account.DisplayName === "NewCompany";
```
In both cases with Postman giving the following error:
_Cannot read property 'soap:Body' of undefined_

At this time I don't have a particular preference for either one, as long as Postman and Newman show the same behaviour for xmlToJson(responseBody).

**Comment by abhijitkane** [comment]
For both cases, can you try putting a 'console.log(data)' before the "DisplayName is correct" test? 

In newman, it'll be printed to the console. For Postman, you can view the console by following the steps here - http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by joepschuurkes** [comment]
Postman output of 'console.log(data)':
```
Object {Envelope: Object}
    Envelope: Object
        Body: Object
            __prefix: "soap"
            _xmlns:soap: "http://schemas.xmlsoap.org/soap/envelope/"
            _xmlns:tns: "http://www.example.com/"
            _xmlns:xsd: "http://www.w3.org/2001/XMLSchema"
            _xmlns:xsi: "http://www.w3.org/2001/XMLSchema-instance"
        __proto__: Object
    __proto__: Object
```

Newman output of 'console.log(data)':
```
{ 'soap:Envelope':
   { '$':
      { 'xmlns:xsd': 'http://www.w3.org/2001/XMLSchema',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        'xmlns:soap': 'http://schemas.xmlsoap.org/soap/envelope/',
        'xmlns:tns': 'http://www.example.com/' },
     'soap:Body': { 'tns:GetOrCreateCompanyResponse': [Object] } } }
```

**Comment by abhijitkane** [comment]
If you put `console.log(responseBody)` before the xmlToJson call, do you get the same output in both cases?

**Comment by joepschuurkes** [comment]
I do. In both cases the output is:
```
<?xml version="1.0" ?>
<soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.example.com/">
	<soap:Body>
		<tns:GetOrCreateCompanyResponse>
			<Account>
				<DisplayName>
					<![CDATA[NewCompany]]>
				</DisplayName>
				<ComIDAccountName>
					<![CDATA[a8372781-b74a-4063-8c6d-05156d15ac20]]>
				</ComIDAccountName>
			</Account>
		</tns:GetOrCreateCompanyResponse>
	</soap:Body>
</soap:Envelope>
```

**Comment by abhijitkane** [comment]
Hm...looks like a version mismatch. We'll fix this soon.

**Comment by KevinVlaanderen** [comment]
The Xml To Json library that is used actually differs for postman and newman. Postman uses x2js (https://code.google.com/p/x2js/), while newman uses xml2js (https://www.npmjs.com/package/xml2js). Both provide access to the wrapper XmlToJson, but implement it differently. X2js seems to remove namespace-prefixes by default, while xml2json requires some configuration to achieve this behavior.

I can do a merge request for the easy fix (adding the attributes to the default TestResponseHandler), but a better solution is to use the same library for both systems, I guess.

**Comment by abhijitkane** [comment]
To avoid breaking existing tests, we'll keep the xmlToJson function. 

However, in the next releases, we'll add an xml2Json function (in both Postman and Newman), which will use the library that Newman uses currently, with a few config changes.

**Comment by abhijitkane** [comment]
--xml2Json function added in both Postman and Newman--

**Comment by DerFlash** [comment]
Thanks @abhijitkane ! I updated to Postman 4.5.0 today and wondered why I got an error because I was still using X2JS (seems removed now) :-)

xml2Json() works like a charm!
