### ISSUE TITLE
Autocomplete suggestions should clear on request, not click

### ISSUE THREAD

**Issue by cnanney** [postmanlabs/postman-app-support#913]
Currently the URL autocomplete suggestions only clear on click. If you just type in the URL and press enter, the suggestions should clear instead of hanging around until you click.

![1](https://cloud.githubusercontent.com/assets/195134/6094482/0aabd868-aef1-11e4-9b10-d19524d31ef3.gif)

**Comment by abhijitkane** [comment]
We'll push a fix in the next release.

**Comment by abhijitkane** [comment]
@cnanney Can you confirm this fixed in v3.0.4?

**Comment by cnanney** [comment]
This is fixed in v3.0.4.
