### ISSUE TITLE
Import Fails for WADL file

### ISSUE THREAD

**Issue by joeashcraft** [postmanlabs/postman-app-support#918]
I'm trying to import a WADL file but the import fails on any of the three methods available.

**Steps to recreate**:  

  1. click Import
  2. by any of the three methods (Upload file, Paste text, Download from link), try to import the contents of [this wadl](http://docs.rackspacecloud.com/auth/api/v2.0/auth.wadl) file
  3. Import fails with error: "Failed to import data: format not recognized"

**My system details**:  

Postman Version 1.0.8 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Leading comments are not being parsed. We'll fix this in the next release. Meanwhile, you can remove the comments at the beginning of the file and import.

**Comment by joeashcraft** [comment]
Removing the comment (line 2) allowed me to import the file.
Thank you!

**Comment by abhijitkane** [comment]
@joeashcraft Can you confirm this fixed in v3.0.4?

**Comment by joeashcraft** [comment]
Hooray! The file imported successfully!

**Comment by a85** [comment]
Awesome. :)

**Comment by antonio-petricca** [comment]
I have the same issue with the latest release. How could I fix it? Thank you so much!
