### ISSUE TITLE
Allow entity body for GET requests

### ISSUE THREAD

**Issue by bibhas2** [postmanlabs/postman-app-support#919]
HTTP specification seems to be unclear about if a request body is allowed for GET, DELETE etc. But some products do use them. Notably, Elasticsearch requires the use of body for GET requests. [Example](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_search_with_query_dsl.html).

POSTMan should not disallow body for these verbs.

**Comment by abhijitkane** [comment]
This is a currently a Chrome limitation. GET requests with a body are automatically stripped of it.

**Comment by a85** [comment]
Duplicat of #424
