### ISSUE TITLE
Confirm delete of environments

### ISSUE THREAD

**Issue by rprince** [postmanlabs/postman-app-support#920]
On the manage environments dialog, the (X) delete button doesn't confirm deleting, which creates a bad user experience when it is accidentally clicked on.

**Comment by abhijitkane** [comment]
We're working on a UI overhaul, and hope to release it soon. Stay tuned.

**Comment by numaanashraf** [comment]
@rprince You can undo deletion of environments, collections, requests & folders in Postman 4.0. This should help you recover any accidental deletes.
