### ISSUE TITLE
Editing The bodies

### ISSUE THREAD

**Issue by BenMackey** [postmanlabs/postman-app-support#921]
I'm not sure what to call it, but I have an authorization code that resets after a certain amount of days.  If I need it to not reset ever, how do I change the expires line on the readout.

Pretty Raw Preview  JSON XML

1
2
3
4
5
6
7
{
    "access_token": "BFy4kEH7QeItMPCfTNcI87JzFZcWUGjd",
    "expires_in": 3691,
    "restricted_to": [],
    "refresh_token": "0iV42rQeAf9xWYbsjVoio19r4iEi3cckGYl1Pbz4DO4VyZBjWcm7SH4QiMuBkvqt",
    "token_type": "bearer"
}

**Comment by abhijitkane** [comment]
I'm not sure I understand what you mean. The expiry time is defined on the server-side, so you'll need to look at the API documentation for info on configuring the token expiry time.

**Comment by stevemcmillen** [comment]
Ben, You more than likely need to call some API that renews the token.  Most services do not allow the token duration to be changed but many allow the caller to issue a call to refresh the token.  This sometimes returns a new token or may just extend the expiration of the existing token.
