### ISSUE TITLE
Feature request: Keyboard Shortcut

### ISSUE THREAD

**Issue by reilg** [postmanlabs/postman-app-support#922]
Would love to be able to launch this thing from a keyboard shortcut. Chrome let's you do that easily now, right?

EDIT:
PS for those who might be curious. Current method for being able to do this to create an app shortcut and then assign /that/ a keyboard shortcut.

**Comment by a85** [comment]
@reilg Can we close this issue now? P.S. We are launching a Mac app soon. Email us at help@getpostman.com for the link.
