### ISSUE TITLE
Simplified (more efficient) pretty print JSON repsonse view

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#925]
I have many requests that return large json result sets (e.g. return 1000 or more media records / each with ~200 fields and nested json structure).  In these cases, the pretty print can take a very long time to render.  

This is a feature request to offer the old style pretty print ( no dynamic expand collapse options / no coloring ) as an alternative to the new pretty print.  That is, a plain text formatted JSON output (new lines and indentation just like the current "Pretty" JSON output view option but as plain text).  The way old Postman used to do.

There are two advantages to plain text output:
1) I think it would be a little faster to render (just a guess since I don't have a way to side-by-side compare how much overhead the current coloring and dynamic JSON response adds).
2) It would be easy to copy just small sections of JSON (currently if you copy just a small section, you get the expand/collapse markup characters and don't get indentation in the resulting JSON).

**Comment by a85** [comment]
@stevemcmillen We switched to Ace Editor a while back that supports efficient rendering of large JSON objects through Web Workers. Are you still facing this issue?

**Comment by stevemcmillen** [comment]
No.  Rendering is much faster with 1000 items now.  It is still slow when using the copy button but in these cases I can just choose select-all copy.  Thanks.  Closing as resolved.
