### ISSUE TITLE
Usability improvements in PostMan Packaged App

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#926]
There are a few aspects of the POSTMan UI that I've been wanting for a while to help use screen space more efficiently:

1. Make the left navbar resizeable ( For me, I don't need as much space as it takes but not showing is not an option for me since it just means having to expand again a moment later to select the next API )

2. Make the expand / collapse option for the API Request Description sticky (and make it more obvious when its collapsed that there is more information there )
 * For example, here is the expanded API description:
 ![api_description_expanded](https://cloud.githubusercontent.com/assets/2750330/6268563/bc978a12-b802-11e4-9d8f-c806e7cca101.png)
 * And here it is collapsed:
 ![api_description_collapsed](https://cloud.githubusercontent.com/assets/2750330/6268574/c97f3144-b802-11e4-8059-7bb697fe2e38.png)
 * In the collapsed mode, there should be some sort of ellipses to make it obvious its got more info.

3. More horizontal space for the API URL line (reduce size or move buttons to the right)
 * For example, you can't see the entire line for following request (even with hostname as a variable) making it hard to edit the items in all caps which have to be updated for each request
![url_line](https://cloud.githubusercontent.com/assets/2750330/6268914/ddd9ecae-b804-11e4-93d9-7f128c048585.png)
 * And if the hostname was not a variable, its even worse:
![url_line_with_full_hostname](https://cloud.githubusercontent.com/assets/2750330/6268936/01fdaa1c-b805-11e4-924e-7b82570fc464.png)
 * And following example where query params with dynamic fill in variables (I prefer to leave the URL Params collapsed and just edit on the URL Line since URL Params list can take * a lot* of vertical space):
![url_line_queryparams](https://cloud.githubusercontent.com/assets/2750330/6268944/0d64b936-b805-11e4-8dc5-b65250af8219.png)
 * What would be nice if if the show/hide buttons for URL Params and Headers were much smaller (maybe with graphics) or if they were above next to the name of the API Request.  For example, how about this:
![url_line_with_full_hostname](https://cloud.githubusercontent.com/assets/2750330/6269059/cd7e61ea-b805-11e4-9f7e-b3d9f18db62f.png)

4. Finally, it would be nice if the list of Headers and URL Params did not take up quite as much vertical space.  Each row is 40 pixels high and there is always one additional blank row.  I like to leave headers open because we just about always have to edit those.  So this takes up 1/2 of the vertical space just showing 3 headers + the blank header row.  Could this be 20 pixels each with no blank row (add a "+" button to add rows)?  

For those who like the current UX,maybe offer as a new "compact Theme" ?

**Comment by abhijitkane** [comment]
We're working on a major UI revamp, and hope to have something out soon.

**Comment by stevemcmillen** [comment]
One more thing.  I had been noticing that with the new dark theme, the background color for highlighted text was not very different from the overall background color - making it had to see what was highlighted.  When I was filing bugs yesterday, I saw it was fixed so I did not file a bug.  But now I see that there is s till one place (in the POST Body in the raw window) that the highlight is still hard to distinguish from the background.    In all other places ( Response body, URL, etc ) the highlight is easily visible.

**Comment by aditikul** [comment]
@stevemcmillen We've improved a couple of things from your list - the left navbar is resizable, the request description is improved, and now we have the documenter view for viewing it in a much more legible and shareable web view, and we have updated the UI significantly. Let us know if this works for you. Thanks!

**Comment by stevemcmillen** [comment]
UX updates have been really helpful.  I think this resolves the issue.  I love the fact that you can also keep the description on each api collapsed now.  Thanks!!
