### ISSUE TITLE
Feature Request: implement for new version of Opera

### ISSUE THREAD

**Issue by JuanCAlpizar** [postmanlabs/postman-app-support#930]
As title says, the older Opera 11 and 12 presto based versions are very obsolete in terms of HTML 5 and new standards, and so far version 15+ of Opera is not being supported. Can you please implement postman for this verison? it's a great tool and I wouldn't like to install a browser just to use it

**Comment by skolman** [comment]
:+1:

**Comment by a85** [comment]
We will be announcing browser agnostic versions soon. That's a much better way forward than dealing with browser specific issues.

**Comment by thibaultmeyer** [comment]
Hi,

What's up about Opera or browser agnostic versions ?

**Comment by ruisilva450** [comment]
Any state change on this?

**Comment by DimitrK** [comment]
any news??

**Comment by a85** [comment]
There is not going to be any opera specific versions but native apps are already here. The Mac app can be downloaded from www.getpostman.com/apps. Windows will be out in a bit. :)

**Comment by thibaultmeyer** [comment]
@a85 Any release date estimation for the Windows version ?

**Comment by a85** [comment]
@0xbaadf00d This week. Just testing out the update flows. :)

**Comment by JuanCAlpizar** [comment]
@a85 is there gonna be a Linux version?

**Comment by thibaultmeyer** [comment]
@a85 Is the windows version ready ?

**Comment by thepipecat** [comment]
@a85 any news about Windows version?

**Comment by a85** [comment]
@0xbaadf00d @thepipecat Yep. https://twitter.com/postmanclient/status/742449939439984640
