### ISSUE TITLE
Basic authentication is not working with special characters 

### ISSUE THREAD

**Issue by amoerie** [postmanlabs/postman-app-support#933]
Replay scenario:

- Open Postman
- Create a new GET request
- Choose "Basic Auth"
- Fill in a random username and password
- Click "Refresh headers"
- Expand the Headers and verify that the basic auth header is not present

Postman details:
Version 1.0.9 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64
Chrome details:
Version 40.0.2214.115 m
Windows details:
Windows 8.1 Pro x64

**Comment by abhijitkane** [comment]
Can you follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/ and check if any errors show up in the console? I'm not facing this problem on OSX.

**Comment by amoerie** [comment]
Yes, I get a specific error:

Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.requester.min.js:4 Backbone.Model.extend.processCustomRequestrequester.min.js:4 Backbone.Model.extend.processrequester.min.js:5 (anonymous function)jquery.min.js:3 f.event.dispatchjquery.min.js:3 h.handle.i

I can only think of one special character in the password, which is the '€' sign. 

Just tested it without the '€' sign and then it works. So there you have your bug :-)

**Comment by abhijitkane** [comment]
Thanks. We'll fix it in the next release.

**Comment by abhijitkane** [comment]
@amoerie Can you confirm this fixed in v3.0.4?

**Comment by amoerie** [comment]
Looking good from my end! Thanks!
