### ISSUE TITLE
Tying Collections to User Accounts

### ISSUE THREAD

**Issue by Shawful** [postmanlabs/postman-app-support#936]
Hello,

I have noticed that my postman collections vary on different machines.  It would be AMAZING if we could get a user to login and have all of their end points and collections show up after simply logging in.  

I know the current work around is to export all of your collections and then import them, but I know your  user base would swoon if you guys could make this happen.

Any ideas?  I'm sure others have suggested this before me, but I didn't see anything in the current issues.  I would love to know what you guys think of this idea and how feasible it is.

Cheers!

**Comment by a85** [comment]
This is available with Postman Sync in version 3.0. :)
