### ISSUE TITLE
setting Environmental variable from a response

### ISSUE THREAD

**Issue by badjohnnyt** [postmanlabs/postman-app-support#937]
I’m having trouble setting the EnvironmentalVariable in my Collection. The first API call uses Credentials to get back an access_token. Subsequent calls then use this token. But the parameter/key remains undefined. The key I’ve called “access_token” which is also the name of the response.

var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("access_token", data.access_token);

Attached is the call with the response. Seems straight-ahead but I can’t seem to get that variable defined and updated.

![screen shot 2015-02-24 at 4 48 08 pm](https://cloud.githubusercontent.com/assets/11188414/6365868/8b0ca576-bc72-11e4-9088-64015f6a437d.png)

Thanks for any help.

Johnny

**Comment by abhijitkane** [comment]
data refers to the root response object. You'll need to use `data.response_data.access_token`.

Also make sure that you have an environment selected, otherwise `setEnvironmentVariable()` has no effect.

**Comment by badjohnnyt** [comment]
Thanks so much. Works great!
