### ISSUE TITLE
Newman run stuck at 'Iteration 1 of 1' with XML rawModeData

### ISSUE THREAD

**Issue by mdabbagh** [postmanlabs/postman-app-support#938]
I have a collection that does a post to a website with soap xml data. If I run the collection through Postman, it works perfectly and returns a response body. If I export the collection and try to run it in Newman, it gets stuck at 'Iteration 1 of 1' and nothing happens.

Here's what I tried:
- Tried the exported collection with no modifications -- Stuck
- Remove \n and any extra spaces -- Still stuck
- Tried to escape the spaces in the soap:Envelope tag with \u0020 -- Still stuck
- Send malformed xml in rawModeData -- Request happens and I get a 200 OK back. However, the same request in Postman returns an error from the application side saying it can't parse the data. 

Here's the exported json as is from Postman with no modifications:
{
	"id": "517d58b9-cbe9-6c86-7dad-6c3105a18ef2",
	"name": "CustomCollection3",
	"description": "",
	"order": [
		"96d7d0fa-50eb-4078-99d3-dc66c225c688"
	],
	"folders": [],
	"timestamp": 1425060031499,
	"synced": false,
	"remoteLink": "",
	"requests": [
		{
			"id": "96d7d0fa-50eb-4078-99d3-dc66c225c688",
			"headers": "Authorization: Basic c2Vhbjph\nContent-Type: application/xml\n",
			"url": "http://localhost:9000/app/soap/security",
			"pathVariables": {},
			"preRequestScript": "",
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"name": "Logon to app",
			"description": "",
			"descriptionFormat": "html",
			"time": 1425060044558,
			"version": 2,
			"responses": [],
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {},
			"collectionId": "517d58b9-cbe9-6c86-7dad-6c3105a18ef2",
			"synced": false,
			"rawModeData": "<?xml version=\"1.0\"?>\n<soap:Envelope\nxmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"\nxmlns:security=\"http://security.sei.webservice/\">\n  \n  <soap:Header/>\n  <soap:Body>\n    <security:logon>\n      <credentials>\n         <userId>user</userId>\n         <password>pass</password>\n      </credentials>\n    </security:logon>\n  </soap:Body>\n\n</soap:Envelope>"
		}
	]
}

My latest attempt, which I would expect to work, has this for the rawModeData line:
"rawModeData": "<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:security=\"http://security.sei.webservice/\"><soap:Header/><soap:Body><security:logon><credentials><userId>user</userId><password>pass</password></credentials></security:logon></soap:Body></soap:Envelope>"

Any help would be greatly appreciated. This might be just an issue with the application I'm sending requests to but it seems weird to me that I get something back in Postman and Newman gets stuck.

**Comment by abhijitkane** [comment]
You'll need to prepend all double-quotes in the rawModeData string with a \. Postman should have done that while exporting - we'll fix that in the next release.

I was able to run this collection:

```
{
"id": "517d58b9-cbe9-6c86-7dad-6c3105a18ef2",
"name": "CustomCollection3",
"description": "",
"order": [
"96d7d0fa-50eb-4078-99d3-dc66c225c688"
],
"folders": [],
"timestamp": 1425060031499,
"synced": false,
"remoteLink": "",
"requests": [
{
"id": "96d7d0fa-50eb-4078-99d3-dc66c225c688",
"headers": "Authorization: Basic c2Vhbjph\nContent-Type: application/xml\n",
"url": "http://localhost:9000/app/soap/security",
"pathVariables": {},
"preRequestScript": "",
"method": "POST",
"data": [],
"dataMode": "raw",
"name": "Logon to app",
"description": "",
"descriptionFormat": "html",
"time": 1425060044558,
"version": 2,
"responses": [],
"tests": "",
"currentHelper": "normal",
"helperAttributes": {},
"collectionId": "517d58b9-cbe9-6c86-7dad-6c3105a18ef2",
"synced": false,
"rawModeData": "<?xml version=\"1.0\"?>\nsoap:Envelopenxmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"nxmlns:security=\"http://security.sei.webservice/\"\n \n soap:Header/\n soap:Body\n security:logon\n \n user\n pass\n \n /security:logon\n /soap:Body\n\n/soap:Envelope"
}
]
}
```

**Comment by mdabbagh** [comment]
Thanks for the quick response!

I tried the following (escaping all double quotes) and it still gets stuck (I also removed the '\n' all over):

{
	"id": "9a913928-a9b6-bfed-7486-ea615bbc1343",
	"name": "CustomCollection",
	"description": "",
	"order": [
		"cb28570a-5a30-f892-d38b-2c1cd63b3b7c"
	],
	"folders": [],
	"timestamp": 1424803378455,
	"synced": false,
	"remoteLink": "",
	"requests": [
		{
			"id": "cb28570a-5a30-f892-d38b-2c1cd63b3b7c",
			"headers": "Authorization: Basic c2Vhbjph Content-Type: application/xml",
			"url": "http://localhost:9000/app/soap/security",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"version": 2,
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1424816483541,
			"name": "Logon to app",
			"description": "",
			"collectionId": "9a913928-a9b6-bfed-7486-ea615bbc1343",
			"responses": [],
			"synced": false,
			"rawModeData": "<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:security=\"http://security.sei.webservice/\"><soap:Header/><soap:Body><security:logon><credentials><userId>user</userId><password>pass</password></credentials></security:logon></soap:Body></soap:Envelope>"
		}
	]
}

**Comment by mdabbagh** [comment]
I tried escaping the double quotes and removing the '\n' but still no dice. Could it be the spaces in the soap:Envelope tag?

    <?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:security=\"http://security.sei.webservice/\"><soap:Header/><soap:Body><security:logon><credentials><userId>user</userId><password>pass</password></credentials></security:logon></soap:Body></soap:Envelope>

**Comment by abhijitkane** [comment]
What happens when you run this - 
```
newman -u https://www.getpostman.com/collections/e8bd2a4c5513dd330d00
```
(I've uploaded the collection at this URL)

**Comment by mdabbagh** [comment]
It seems that works! It's a bit confusing though, because if I remove the space at the beginning (right after "rawModeData": "), it doesn't work. So this doesn't work:

    {
	"id": "217d58b9-cbe9-6c86-7dad-6c3105a18ef2",
	"name": "CustomCollection3_new",
	"description": "",
	"order": [
		"96d7d0fa-50eb-4078-99d3-dc66c225c688"
	],
	"folders": [],
	"timestamp": 1425060031499,
	"synced": false,
	"remoteLink": "https://www.getpostman.com/collections/e8bd2a4c5513dd330d00",
	"requests": [
		{
			"id": "96d7d0fa-50eb-4078-99d3-dc66c225c688",
			"headers": "Authorization: Basic c2Vhbjph\nContent-Type: application/xml\n",
			"url": "http://localhost:9000/app/soap/security",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"version": 2,
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1425066933572,
			"name": "Logon to app",
			"description": "",
			"collectionId": "217d58b9-cbe9-6c86-7dad-6c3105a18ef2",
			"responses": [],
			"synced": false,
			"rawModeData": "<?xml version=\"1.0\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:security=\"http://security.sei.webservice/\"><soap:Header/><soap:Body><security:logon><credentials><userId>user</userId><password>pass</password></credentials></security:logon></soap:Body></soap:Envelope>"
		}
	]
}

**Comment by mdabbagh** [comment]
Another note, I just tried to do the same request with curl and it worked with the exact same data as what's in the "rawModeData". I just had to set --header "Content-Type:text/xml" and voila. Gave me the expected xml response back.

**Comment by mdabbagh** [comment]
For reference, here's what the expected output looks like with a successful request:

    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
        <soap:Body>
            <ns2:logonResponse xmlns:ns3="http://plcm.ibm.com/types" xmlns:ns2="http://security.sei.webservice/">
                <return>
                    <requestId />
                    <isSuccessful>true</isSuccessful>
                    <Session>
                        PLAY_SESSION="9f82241f00a59ce304d9ec77864e0af3d351c5bd-userId=1&profilePartyId=0&userGroupId=-1&csrfToken=d8c5914dfc9f53217dc662f90fd43431db8c3fa0-1425321110411-9c442e8a8246c1a51c17e88e"; Path=/app/; HTTPOnly
                    </Session>
                </return>
            </ns2:logonResponse>
        </soap:Body>
    </soap:Envelope>

**Comment by abhijitkane** [comment]
@mdabbagh If you're still seeing this, can you file this issue at https://github.com/postmanlabs/newman/issues?
Closing this issue.
