### ISSUE TITLE
Header value from variable that contains '$$' gets trimmed to just '$'

### ISSUE THREAD

**Issue by kylestittleburg** [postmanlabs/postman-app-support#939]
I've got an environment variable, {{test}} with a value of a$$b.  When I add this to a header in my request and preview the request (or actually send it), the value is a$b.

If I manually enter a$$b as the header value it works fine, so it must be an issue with the variable substitution.  Am I missing something?

Version 1.0.11 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
This is due to the special significance of '$' in the .replace() function - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/replace

We'll push a fix in the next release.

Thanks for reporting this.

**Comment by abhijitkane** [comment]
@kylestittleburg Can you confirm this fixed in v3.0.4?

**Comment by kstittleburg** [comment]
Confirmed fixed, it's working fine for me in 3.0.4
