### ISSUE TITLE
 after I made import bauckup file , The enter, tab and aother hidden characters are displayed and the code has error  java script code in Test text editor 

### ISSUE THREAD

**Issue by hanyghazal** [postmanlabs/postman-app-support#940]
I mean the code sample that I have is 

if(responseCode.code === 202)
{
	tests["responseCode equal 202"] =true;
}
else
{
	tests["responseCode equal 202"] =false;
}

but after I import the data file the code like this

if(responseCode.code === 202)\n{\n\ttests["responseCode equal 202"] =true;\n}\nelse\n{\n\ttests["responseCode equal 202"] =false;\n}

please advice , ALL codes that I written changed and to change it it is a huge effort

**Comment by abhijitkane** [comment]
What version of the app are you using? 

In the current version, v1.0.11, I'm able to import this collection (https://www.getpostman.com/collections/55e7c7c62a5e87c26aae, which has a test script) w/o any escaping problems.

**Comment by hanyghazal** [comment]
I don't make import me collection. I made import to backup data from setting then data. Please make backup from your work then remove postman then reinstall postman pchaged app. Then import . you will find the problem.

Please try and let me know

**Comment by hanyghazal** [comment]
I use latest version

**Comment by abhijitkane** [comment]
We'll fix this in tomorrow's release.

**Comment by hanyghazal** [comment]
I downloaded now v 2.0.0 and still the problem not solved

**Comment by abhijitkane** [comment]
I'm able to import the backup properly in v2.0.0. Can you mail your backup dump file to help@getpostman.com?
