### ISSUE TITLE
Feature request - REST API mocking

### ISSUE THREAD

**Issue by codemedic** [postmanlabs/postman-app-support#943]
It will be a great addition to the postman suit, which will enable developers to mock and shared the mocks.
Something like https://github.com/basicallydan/interfake
There is the node.js element to it; not sure how that can be integrated into a chrome app.

**Comment by mchambaud** [comment]
+1

**Comment by thinkstylestudio** [comment]
+1

**Comment by leonardschneider** [comment]
+1

**Comment by lateef531** [comment]
+1

**Comment by a85** [comment]
This is available as a mock server feature in Postman Pro: https://api.getpostman.com
