### ISSUE TITLE
After write an environment variable in test , then close postman then open it the variable that created by test not shown in the environment 

### ISSUE THREAD

**Issue by hanyghazal** [postmanlabs/postman-app-support#947]
defect steps

1- write a set environment in test in any request 
2- run collection by test runner for this request.
3- the variable was created in the environment
4- close postman
5- open the postman again
6- check the variable that created from step 2 ----> you will find that the variable not found

**Comment by abhijitkane** [comment]
We'll push a fix for this soon.

**Comment by hanyghazal** [comment]
I have now version 2.0.2 and still the defect the same.

**Comment by abhijitkane** [comment]
The fix wasn't in this version. We'll push it out soon.

**Comment by abhijitkane** [comment]
@hanyghazal Are you still seeing this in v3.0.4?
