### ISSUE TITLE
Any updates in test not reflected directly in the collection runner 

### ISSUE THREAD

**Issue by hanyghazal** [postmanlabs/postman-app-support#948]
steps
1- run a collection runner for any valid request.
2- when the collection runner is opened, make any update for the test in this collection for example set any global variable 
3- make new run form the opened collection runner for the updated collection 
4- check the updated ---> the variable that added to collection not set.

**Comment by hanyghazal** [comment]
this defect still exist in v 2.0.4

**Comment by jdfriedman** [comment]
Able to reproduce this as well.

**Comment by a85** [comment]
This should not be happening in 4.0+. Let us know if it does. Will reopen.
