### ISSUE TITLE
Offline Postman zip file wrong file reference

### ISSUE THREAD

**Issue by fcleynen** [postmanlabs/postman-app-support#949]
We are working on offline development machines so I downloaded the Postman zipped package and imported the extension in Chrome. Started up Postman and it wasn't doing anything.

Checked via developer tools and saw it is trying to find the file js/requester.js which is not in the package. Instead, js/Requester.min.js is available. Renaming the file resolved the issue but file reference should be fixed.

**Comment by abhijitkane** [comment]
Where did you download the zipped package from? The one in the Chrome webstore works correctly.

**Comment by fcleynen** [comment]
Hi,

yes indeed I did not use the link 'Packaged app (v0.9.6)' linked as I ended up directly in the section 'Installing the zip file' so I let Github create a zipped version of the master branche and used that one.
