### ISSUE TITLE
after remove the globals variables by delete it from global page variable one by one, then run any collection, all variables that i deleted back again

### ISSUE THREAD

**Issue by hanyghazal** [postmanlabs/postman-app-support#951]
the only way that after delete the variables form globals, by hand one by one, close postman then open it again

**Comment by abhijitkane** [comment]
Did you press "Back" after deleting the global variables? Without it, the changes aren't updated.

**Comment by hanyghazal** [comment]
Yes I pressed back.  I know this I used postman for about 1 year. The problem that after make delete then press back then run any collection. The variables back again

**Comment by a85** [comment]
The UI has been changed so this should not happen.
