### ISSUE TITLE
Error while importing Swagger: ReferenceError: dir is not defined

### ISSUE THREAD

**Issue by cimnine** [postmanlabs/postman-app-support#952]
I get this error when I try to import a simple Swagger (V1.2) spec:

![05-03-2015 11-12-25](https://cloud.githubusercontent.com/assets/804532/6502955/a250668e-c328-11e4-8927-895375fe2ed3.png)

The JSON is like this:

    {
        "apiVersion": "2",
        "swaggerVersion": "1.2",
        "apis": [
            {
                "path": "/foo/bar",
                "description": "Some Call"
            }
        ],
        "info": {
            "title": "Bla",
            "description": "",
            "termsOfServiceUrl": "",
            "contact": "",
            "license": "",
            "licenseUrl": ""
        }
    }

~Chris

**Comment by abhijitkane** [comment]
This JSON is not directly mappable to a Postman collection, as there's no HTTP verb specified, or a base URL.

This JSON is imported correctly:
```
{
    "apiVersion": "2",
    "swaggerVersion": "1.2",
    "basePath": "http://sampleurl/",
    "apis": [
        {
            "path": "/foo/bar",
            "operations": [{
                "method": "GET"
            }],
            "description": "Some Call"
        }
    ],
    "info": {
        "title": "Bla",
        "description": "",
        "termsOfServiceUrl": "",
        "contact": "",
        "license": "",
        "licenseUrl": ""
    }
}
```

We'll add a better error message in a future release.

**Comment by marcoherbst** [comment]
Hi, I'm getting the same error, but we have defined a basepath: (at the bottom)
https://api.evercam.io/v1/swagger

{
  "apiVersion": "1.0",
  "swaggerVersion": "1.2",
  "produces": [
    "application/json"
  ],
  "operations": [

  ],
  "apis": [
    {
      "path": "/swagger/users"
    },
    {
      "path": "/swagger/cameras"
    },
    {
      "path": "/swagger/public"
    },
    {
      "path": "/swagger/models"
    },
    {
      "path": "/swagger/vendors"
    },
    {
      "path": "/swagger/auth"
    }
  ],
  "info": {
  },
  "basePath": "https://api.evercam.io/v1"
}

**Comment by kennuzzo** [comment]
I Just bumped on the same issue, ive realized that the import doesnt work from the swagger root
but it does work if i pass one of the apis endpoint 

@marcoherbst, in your example if you use ```https://api.evercam.io/v1/swagger/users``` it will import it without any complain
There might be more things to change but at least is a start :)
Ive also noticed that it uses the title attribute to name the collection.

**Comment by marcoherbst** [comment]
Many thanks, that works a charm.

**Comment by Ulrhol** [comment]
I have the same issue. I've tried both import from url and pasted the raw json
