### ISSUE TITLE
Newman does not support javascript global variables while postman&collectionrunner support

### ISSUE THREAD

**Issue by youranwj** [postmanlabs/postman-app-support#953]
I defines a global variable (define variable without "var", then the variable is global) to hold all common functions which will be used across all requests. It works well in postman & collectionrunner, but not in newman.

Here is the definition:

globalFunctions = {
testcaseStartLog: function() {
console.log("\n");
console.log(Date.create().format("{yyyy}-{Month}-{dd} {hh}:{mm}:{ss}") + " TESTCASE STARTED: " + environment.currentTestCaseName);
},
testcaseEndLog: function() {
console.log(Date.create().format("{yyyy}-{Month}-{dd} {hh}:{mm}:{ss}") + " TESTCASE ENDED: " + environment.currentTestCaseName);
}
}

Usage:
globalFunctions.testcaseStartLog();

when run the collections via newman, error is:
EXCEPTION - ReferenceError: globalFunctions is not defined

**Comment by abhijitkane** [comment]
Newman creates a new context for every test run. The "window." approach was a hack of sorts to use in Postman.

In Newman, you can set the function as a global variable - 
```
postman.setGlobalVariable(\"printName\",function(name) { console.log(\"Hi \" + name);});
(postman.getGlobalVariable(\"printName\"))(\"Newman\");
```

But this will likely cause problems in Postman.

**Comment by youranwj** [comment]
It works, but only in one test run. I figure out another workaround to re-use the function: save the function as a string in global variables and use eval() to execute them later.

**Comment by shamasis** [comment]
Postman v4.5+ onwards, all contexts are separated. Providing a more reliable script environments. As such, Newman and Postman apps should behave uniformly by not retaining global variables between consecutive requests.
