### ISSUE TITLE
Folder structure is ignored (since 2.0?)

### ISSUE THREAD

**Issue by Cakez0r** [postmanlabs/postman-app-support#956]
For the past week or so (I believe since Postman auto-updated to the latest version), folders are ignored when using the import feature.

All requests and folders appear in a flat list, whereas they were previously organised correctly

Can send an example export file / import url to a private address if requested.

![postman](https://cloud.githubusercontent.com/assets/1033671/6554301/02b6f926-c652-11e4-9240-9a7c4dee7ce5.PNG)

**Comment by abhijitkane** [comment]
Can you send it to help@getpostman.com?

Also, are you seeing any errors in the console after you import? (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/)

**Comment by sbutalia** [comment]
I am also experiencing this...

**Comment by abhijitkane** [comment]
@sbutalia @Cakez0r Are you still seeing this with v3.0.4?

**Comment by Cakez0r** [comment]
Hi @abhijitkane,

We spoke via email about this issue. It turned out that our collection exporter tool was not generating the "order" field at the collection level. After fixing this problem with our exporter, this issue was resolved for us.

Our (broken) collection file was:

```
{
    "id" : "fa7f7036-d977-4651-8257-909f5b9cbb33",
    "name" : "OurCollection",
    "timestamp" : null,
    "requests" : [{

 ... *SNIP* ...
```

which you advised me to change to

```
{
    "id": "fa7f7036-d977-4651-8257-909f5b9cbb33",
    "name": "OurCollection",
    "timestamp": null,
    "order": [],
    "requests" : [{

 ... *SNIP* ...
```

**Comment by abhijitkane** [comment]
Got it, didn't connect the email chain with this issue. Thanks.

**Comment by sbutalia** [comment]
@abhijitkane 

This happened after upgrading so the collection already existed and I haven't changed anything.
