### ISSUE TITLE
Feature request:  Allow importing of OAuth 2.0 tokens

### ISSUE THREAD

**Issue by stajs** [postmanlabs/postman-app-support#957]
I’ve been evaluating Postman for my organisation and it looks really promising. However one area that may prevent our adoption is the current method of obtaining OAuth 2.0 tokens: 
1. Our organisation is deeply uncomfortable with sharing of the `Client Secret`.
2. We are first-party consumers of our own internal APIs and don’t make use of an `Authorization URL`.

We can easily obtain the required OAuth 2.0 details (access token, refresh token, expiry, etc) and ideally we would like a way to import them (perhaps from JSON or manually entered) so the tokens are stored in the same way as the existing method.

**Comment by stajs** [comment]
Also, one thing I'm not sure about is if the access token has expired, will Postman transparently use the refresh token to obtain a new access token and update it?

**Comment by DelawareConsulting** [comment]
We need the same feature as well.

**Comment by harryi3t** [comment]
@stajs You can share an environment across your team, which can have the oauth token.
And then everyone can use that env var in the Oauth-2 input. Would that work for you?

About your [second comment](https://github.com/postmanlabs/postman-app-support/issues/957#issuecomment-77949546), there is a feature request for this here https://github.com/postmanlabs/postman-app-support/issues/2452
