### ISSUE TITLE
Custom HTTP Methods

### ISSUE THREAD

**Issue by jaredhanks** [postmanlabs/postman-app-support#958]
Any chance of adding the ability for custom HTTP Methods?  I need the ability to use "QUEUE" as a method.

**Comment by francescotonini** [comment]
It has been almost a year, any changes? :)

**Comment by a85** [comment]
Closing this as duplicate of #166. The new Postman Runtime based on Node.js will solve this: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/
