### ISSUE TITLE
Resizable sidebar

### ISSUE THREAD

**Issue by AntonNiklasson** [postmanlabs/postman-app-support#965]
It would be awesome to have the sidebar be resizable.

**Comment by abhijitkane** [comment]
We're working on a major UI revamp, which includes a resizable sidebar.

**Comment by AntonNiklasson** [comment]
That sounds awesome :+1:

med vänliga hälsningar,

Anton Niklasson
www.antonniklasson.se
070 - 499 88 15

2015-03-12 12:03 GMT+01:00 Abhijit Kane <notifications@github.com>:

**Comment by a85** [comment]
Available in the latest version of Postman!
