### ISSUE TITLE
Request debugging with XDebug

### ISSUE THREAD

**Issue by nyurik** [postmanlabs/postman-app-support#966]
[Chrome extension](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc?utm_source=chrome-app-launcher-info-dialog) allows an easy way to add **XDEBUG_SESSION=XDEBUG_ECLIPSE** cookie to the request, making it very easy to debug with PhpStorm or the like. It would be ideal if POSTMan have a similar button somewhere on the UI to enable/disable an extra debugging cookie.

Doing this via a specialized proxy is overly complex if another extension can easily do it with a click.

Thanks!!!

P.S. And yes, an awesome extension this is! ))

**Comment by kirugan** [comment]
@nyurik you can use XDEBUG_SESSION_START param (POST, GET) with the same idekey-value if you wish

**Comment by l0rb** [comment]
while it does work, providing the post/get param is not a very clean solution. Especially when working in a team and not everyone wants to trigger xdebug.

**Comment by kirugan** [comment]
JFYI postman native app allows you add custom cookies to request easily

**Comment by speto** [comment]
@a85 Hi guys, I would like to kindly ask for reconsideration of this request.
It's terribly uncomfortable to add cookies, headers or parameters per requests to start xdebug session and then ad-hoc quickly turn it off and on as well.

Any chance to introduce something like a bookmarks bar into UI which could enable/disable pre-request scripts so something similar or modified like common browser bookmarklets (https://www.jetbrains.com/phpstorm/marklets/) could be used? I could imagine use cases of this feature could go on.

**Comment by rulatir** [comment]
> JFYI postman native app allows you add custom cookies to request easily

The standard for "easily" is set by browser extensions like [Xdebug helper](https://chromewebstore.google.com/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc). That standard is "enable debugging with two clicks". Postman's cookie manager UX is much below that standard. Compare and contrast:

#### Xdebug helper UX:
 1. Click on the Xdebug helper icon
 2. Click on the green bug item
 
 #### Postman cookie manager UX:
 1. Click "Cookies"
 2. The dialog covers the request URL input, so you must back out to see the domain if you don't remember it (believe me, in a flurry of debugging this can happen - you paste cURL request from Chrome and forget if it is to `cms.mysite.devhost` or `api.mysite.devhost` or what)
 3. Memorize the domain, click on Cookies again
 4. Type the domain
 5. Click "Add"
 6. Click "+ Add Cookie"
 7. Place caret in the editor
 8. Edit cookie name
 9. Edit cookie value
 10. Click "Save"
