### ISSUE TITLE
Add ability to wipe all data (or checkbox for Import to "replace all")

### ISSUE THREAD

**Issue by iurii-cartev-wellogic** [postmanlabs/postman-app-support#967]
Hello, dear POSTMAN developers!

I am permanent user of Postman and I love it very much. There is a feature which would make my life so much easier! This feature is about wiping out whole Postman data (collections and environments) as standalone button or as a checkbox during Import in Settings -> Data.

Right now workaround for that is manually click "X" near each collection, then near each environment. I have ~30 collections with ~15 environments and this process takes some time.

Thank you very much in advance!

**Comment by a85** [comment]
Any specific reason you would need this?

**Comment by ykartsev** [comment]
Of course! For example when you need to completely replace existing collections with the ones you're importing (currently collections with the same name can be replaced by clicking 'replace' for each conflict, although collections with different name still stay, so its more merge as opposed to restore)
As I mentioned, the only way now for that is manually deleting each collection which takes lot if time when you have many collections.

**Comment by ykartsev** [comment]
I see this issue was closed. What was the reason for that? Feature inplemented or won't be? Thank you.

**Comment by a85** [comment]
@iurii-cartev-wellogic We won't have this feature in our immediate roadmap. If you are using Collections individually across different machines then you can use a free Postman account to sync data across machines.

**Comment by ykartsev** [comment]
The thing is that we're using POSTMAN in a closed intranet without internet access. So syncup is not possible. So every time I want to update it with a latest backup, I need to manually delete each and every collection... And I have about 30 of them.

Recently I've found a workaround which is uninstalling and reinstalling POSTMAN. This is easier, but still overkill for such a basic operation. Maybe small checkbox (wipe before import) during data import would be ideal solution here. 

Thank you for your time.

**Comment by a85** [comment]
@iurii-cartev-wellogic When you say you need to update it with the latest backup, you mean that these Collections have been updated by someone else?

**Comment by ykartsev** [comment]
By me as well as by someone else, yes. We have our collections constantly updated and populated with new calls, while these in intranet getting out of sync.
Plus, in other scenario, someone may just scre up few collections and you want to just start from fresh with your known-to-be-good set of collections - then you also need to remove everything and replace with new set.
