### ISSUE TITLE
Create removeEnvironmentVariable() and removeGlobalVariable()

### ISSUE THREAD

**Issue by iurii-cartev-wellogic** [postmanlabs/postman-app-support#968]
Hello, dear POSTMAN developers!

There is another feature which would be very useful for those who run tests in Postman. This feature is about adding 2 methods:
- postman.removeEnvironmentVariable(“key”)
- postman.removeGlobalVariable(“key”)

These are needed to remove variables from dictionaries:
- environment
- globals

The reasons of why they are needed are:
- no ability to remove them in JavaScript way (delete environment["key"])
- removal itself is needed because having same environment used for multiple tests, it gets filled with all these test-related variables very quickly, therefore it's hard to find REAL environment variables, i.e. hostname, username, password, etc. 

One of my use cases is the following:
- execute an API
- save returned result (filename) into an environment variable (postman.setEnvironmentVariable("test_filename", data.fileName);)
- while executing another API, check whether returned filename is the same as saved above: tests["GetAll contains recently created"] = data[0].fileName === environment.test_filename; (var data = JSON.parse(responseBody))

After these 3 steps my environment which had only hostname+password, for example, would end up having "test_filename" as well. And if I have more variables used in my tests (which I do), there are lot more such variables left.

Thank you very much in advance!

**Comment by lholznagel** [comment]
+1

**Comment by katkinso** [comment]
+1

**Comment by lookitsatravis** [comment]
Is there a reason you can't use

``` js
postman.clearEnvironmentVariable("key");
//or
postman.clearGlobalVariable("key");
```

I don't know if it existed when you opened this issue, but I found this issue while searching for the exact feature. Then I noticed the above is included in the test snippets. It works for me to clear them programmatically. Hope it helps you!

**Comment by abhijitkane** [comment]
@lookitsatravis Yes, we added it recently. Forgot to update this thread. 
@KapuzenSohn @katkinso The latest version of Postman has this function in the pre-request and test script sandbox.

**Comment by ykartsev** [comment]
Yeah, it was not the there at the time I created this thread. Awesome to know it's now there! Thank you!

**Comment by abeward** [comment]
In trying to just find a way, any way to KEEP my variable, but clear the value in a reproducible way (setting to "" only works some of the time), I've tried .unset. As of this morning, .unset deletes the whole key:value pair from the environment variables list. So try that. Any variables you point at of that name will error unless you first set it again, though, since it won't exist anymore.

If you use .clear it will destroy all of your variables under current behavior even if you pass in a specific variable to .clear, so make a backup and be prepared for that outcome if you insist on using it.
