### ISSUE TITLE
Bracket breaks link parsing in atom pretty output

### ISSUE THREAD

**Issue by ShadowXVII** [postmanlabs/postman-app-support#970]
When pagination presents a <link rel="next" for the following page, the link only works up until the left parenthesis, and misses the remainder of the URL.

`<link rel="next" href="http://samplewebsite/ODATA/Name('Sample Name')/Function?$filter=endswith(No,'-W')&$skiptoken=100" />
</feed>`

The provided link to the user only applies up until the Name( and doesn't encompass the remainder of the URL.

![Link Formatting Example](http://i.imgur.com/3SRjI6X.png)...

This doesn't happen when formatting with JSON.

**Comment by abhijitkane** [comment]
The XML parser didn't include single quotes as valid URL characters. We'll fix this in the next release.

The 'sample name' is a placeholder, right? Spaces wouldn't be parsed as URLs in the JSON view either.

**Comment by ShadowXVII** [comment]
Ah, yes my bad. The should be %20 :)
