### ISSUE TITLE
Feature request - Add faker library

### ISSUE THREAD

**Issue by zakhenry** [postmanlabs/postman-app-support#971]
It would be very helpful to generate dummy data for testing multiple iterations with user date to try to find any holes in the API.

See https://github.com/marak/Faker.js/ - this is an excellent library for faking data.

**Comment by sepehr** [comment]
This would be very useful.

**Comment by richfoxton** [comment]
+1

**Comment by grifx** [comment]
It would be AWESOME!

**Comment by grifx** [comment]
It would be AWESOME!

**Usage**
body:

```
{
  "userId": {{$guid}},
  "fullName": "{{$faker name.firstName}} {{$faker name.lastName}}"
}
```

result:

```
{
  "userId": "43e40919-9a50-6334-8e15-0195abb6317e",
  "fullName": "John Doe"
}
```

**How**
It should be relatively easy to implement:

```
faker.fake("{{name.lastName}}");
// outputs: "Marks
```
- Add the function:

```
'\\$fake .*': {
    key: '$fake',
    run: (string) => faker.fake('{{' + string.substring(7) + '}}')
}
```
- Change the implementation of **processString** to pass the string through **run**

This is a killer feature! I can't wait to use it.

Thanks

**Comment by grifx** [comment]
If you can't wait to be able to do that: http://g.recordit.co/AfS7Rzjum9.gif (2MB)
Follow the instructions here: https://gist.github.com/grifx/95a99ad062945f8fe359cb6c8b8ddf40

**Comment by nicolas-despres** [comment]
@grifx , that's great! I tried it with `Postman`and it worked well. However, can this work with newman? Probably not because it uses `window` right?

**Comment by grifx** [comment]
@nicolas-despres Probably not. Have you tried? Let me know.
Thanks

**Comment by carl-parrish** [comment]
Has anyone figured out how to get this to work with the Stand Alone? I could *really* use this.

**Comment by surfjedi** [comment]
+1

**Comment by pyarun** [comment]
+1

**Comment by sinan-gul** [comment]
+1

**Comment by joshidhruv** [comment]
+1

**Comment by sepehr** [comment]
Ah, please stop commenting +1s and triggering email notifications for issue subscribers. You can instead use the reaction button.

**Comment by rawaludin** [comment]
I really want this feature available in postman. I've used http://faker.hook.io but there's limit on number of api call. Always getting timeout. In the meantime, I build this to generate faker data https://hub.docker.com/r/rahmatawaludin/faker-server

**Comment by jeson114** [comment]
This was raised in 2015 . Is there no plan to introduce this feature ? This seems like a very essential requirement .

**Comment by thpoiani** [comment]
Is possible to fake data using environment variables and an API that provides it:

**Pre-request Script**
```js
pm.sendRequest("http://faker.hook.io/?property=name.findName&name.LastName&locale=en", function (err, response) {
    pm.environment.set("name", response.text());
});
```

**Comment by aaron-sua** [comment]
While having external API setup to generate data, having this built in to Postman/Newman would be much better for me.  Working on building out infrastructure to do performance testing and generating data for more than 1000 requests a second.  Having a server I need to performance test to get to running performance tests seems ... overly complicated.

**Comment by Marak** [comment]
It would be great to not be using the hook.io hosted service for this and instead use faker.js directly

Please let us know over at faker.js if there is anything we can do to help.

We are planning to release a new major version soon and would love to see it included in Postman.

**Comment by Ahmed-Badawy** [comment]
How come, four years & this feature isn't implemented yet. 
it's needed & it will be very useful.

**Comment by NDemydenko** [comment]
would be nice
+1

**Comment by AHTA** [comment]
Please, would be very useful!

 +1

**Comment by pratik-toptal** [comment]
+1

**Comment by shamasis** [comment]
Hello. This took a while, but we ultimately got around to adding a dummy data producing method right inside Postman. And it starts with addition of over a hundred new dynamic variables that return random data of various kinds. The feature has landed in Postman v7.2, but is still in beta pending support for auto-complete and documentation.

Dynamic variables are just like the concept of global variables in Postman, with the bonus that they are pre-defined and interestingly, can return dynamic data every time it is used.

Meanwhile, here is a screenshot, the list of variables and the Pull Request that has useful information for those who want to look under the hood.

<img width="1352" alt="Screenshot 2019-06-11 at 21 46 26" src="https://user-images.githubusercontent.com/232373/59382147-a416e080-8d7a-11e9-8000-886c78760fea.png">


The Pull Request: https://github.com/postmanlabs/postman-collection/pull/873

**List of available variables:**
- `{{$randomZipCode}}`
- `{{$randomCity}}`
- `{{$randomCityPrefix}}`
- `{{$randomCitySuffix}}`
- `{{$randomStreetName}}`
- `{{$randomStreetAddress}}`
- `{{$randomStreetSuffix}}`
- `{{$randomStreetPrefix}}`
- `{{$randomSecondaryAddress}}`
- `{{$randomCounty}}`
- `{{$randomCountry}}`
- `{{$randomCountryCode}}`
- `{{$randomState}}`
- `{{$randomStateAbbr}}`
- `{{$randomLatitude}}`
- `{{$randomLongitude}}`
- `{{$randomColor}}`
- `{{$randomDepartment}}`
- `{{$randomProductName}}`
- `{{$randomPrice}}`
- `{{$randomProductAdjective}}`
- `{{$randomProductMaterial}}`
- `{{$randomProduct}}`
- `{{$randomCompanyName}}`
- `{{$randomCompanySuffix}}`
- `{{$randomCatchPhrase}}`
- `{{$randomBs}}`
- `{{$randomCatchPhraseAdjective}}`
- `{{$randomCatchPhraseDescriptor}}`
- `{{$randomCatchPhraseNoun}}`
- `{{$randomBsAdjective}}`
- `{{$randomBsBuzz}}`
- `{{$randomBsNoun}}`
- `{{$randomDatabaseColumn}}`
- `{{$randomDatabaseType}}`
- `{{$randomDatabaseCollation}}`
- `{{$randomDatabaseEngine}}`
- `{{$randomDatePast}}`
- `{{$randomDateFuture}}`
- `{{$randomDateBetween}}`
- `{{$randomDateRecent}}`
- `{{$randomMonth}}`
- `{{$randomWeekday}}`
- `{{$randomBankAccount}}`
- `{{$randomBankAccountName}}`
- `{{$randomCreditCardMask}}`
- `{{$randomCurrencyAmount}}`
- `{{$randomTransactionType}}`
- `{{$randomCurrencyCode}}`
- `{{$randomCurrencyName}}`
- `{{$randomCurrencySymbol}}`
- `{{$randomBitcoin}}`
- `{{$randomBankAccountIban}}`
- `{{$randomBankAccountBic}}`
- `{{$randomAbbreviation}}`
- `{{$randomAdjective}}`
- `{{$randomNoun}}`
- `{{$randomVerb}}`
- `{{$randomIngverb}}`
- `{{$randomPhrase}}`
- `{{$randomImage}}`
- `{{$randomAvatarImage}}`
- `{{$randomImageUrl}}`
- `{{$randomAbstractImage}}`
- `{{$randomAnimalsImage}}`
- `{{$randomBusinessImage}}`
- `{{$randomCatsImage}}`
- `{{$randomCityImage}}`
- `{{$randomFoodImage}}`
- `{{$randomNightlifeImage}}`
- `{{$randomFashionImage}}`
- `{{$randomPeopleImage}}`
- `{{$randomNatureImage}}`
- `{{$randomSportsImage}}`
- `{{$randomTechnicsImage}}`
- `{{$randomTransportImage}}`
- `{{$randomImageDataUri}}`
- `{{$randomEmail}}`
- `{{$randomExampleEmail}}`
- `{{$randomUserName}}`
- `{{$randomProtocol}}`
- `{{$randomUrl}}`
- `{{$randomDomainName}}`
- `{{$randomDomainSuffix}}`
- `{{$randomDomainWord}}`
- `{{$randomIP}}`
- `{{$randomIPV6}}`
- `{{$randomUserAgent}}`
- `{{$randomHexColor}}`
- `{{$randomMACAddress}}`
- `{{$randomPassword}}`
- `{{$randomLoremWord}}`
- `{{$randomLoremWords}}`
- `{{$randomLoremSentence}}`
- `{{$randomLoremSlug}}`
- `{{$randomLoremSentences}}`
- `{{$randomLoremParagraph}}`
- `{{$randomLoremParagraphs}}`
- `{{$randomLoremText}}`
- `{{$randomLoremLines}}`
- `{{$randomFirstName}}`
- `{{$randomLastName}}`
- `{{$randomFullName}}`
- `{{$randomJobTitle}}`
- `{{$randomNamePrefix}}`
- `{{$randomNameSuffix}}`
- `{{$randomNameTitle}}`
- `{{$randomJobDescriptor}}`
- `{{$randomJobArea}}`
- `{{$randomJobType}}`
- `{{$randomPhoneNumber}}`
- `{{$randomPhoneNumberFormat}}`
- `{{$randomPhoneFormats}}`
- `{{$randomArrayElement}}`
- `{{$randomObjectElement}}`
- `{{$randomUUID}}`
- `{{$randomBoolean}}`
- `{{$randomWord}}`
- `{{$randomWords}}`
- `{{$randomLocale}}`
- `{{$randomAlphaNumeric}}`
- `{{$randomFileName}}`
- `{{$randomCommonFileName}}`
- `{{$randomMimeType}}`
- `{{$randomCommonFileType}}`
- `{{$randomCommonFileExt}}`
- `{{$randomFileType}}`
- `{{$randomFileExt}}`
- `{{$randomDirectoryPath}}`
- `{{$randomFilePath}}`
- `{{$randomSemver}}`

Let us know how you plan to use this. Personally, I am loving the `{{$randomBs}}` variable for all situations where I need to subtly hint towards my opinion! ;-)

**Comment by shamasis** [comment]
@zakhenry and everyone else... thanks for the patience and love you have shown.

**Comment by drod3763** [comment]
This is awesome, I just started using it for some API Testing and I have a couple of bits of feedback:

1. Seperate {{$randomPhoneNumber}} from Phone numbers with extensions as not all APIs deal with these in the same fields. Perhaps have another version call {{$randomPhoneNumberExt}} or {{$randomPhoneNumberWithExt}} so that we have a choice.

~2. As I understand it, I cannot access dynamic variables in Pre-request/Test scripts. Is there some other way we can use these in those areas?~

3. Less Important - Have some way to tie {{$randomExampleEmail}} to {{$randomFirstName}}, {{$randomLastName}} and/or {{$randomFullName}} for consistency in fake customer data.

Thanks!

**Comment by shamasis** [comment]
Indeed! Thank you for such amazing feedback @drod3763. 

I can see that we need to ensure that it is documented how to use this in scripts (point 2). Plus @codenirvana  is working on an API that would open up the function that we use to do variable replacement. Using that, point 2 will be resolved.

Point 1 is very true! I should have spotted that earlier. ;-) Even the APIs I deal with takes just numbers without extension. `{{$randomPhoneNumber}}` should be just the number and `{{$randomPhoneNumberWithExt}}` becomes what $randomPhoneNumber is now. Let's fix this ASAP before it starts breaking existing usage. :-p tracking here https://github.com/postmanlabs/postman-app-support/issues/6765

Point 3, to be honest, is a limitation that is very hard to overcome since all variables, by definition, are isolated from each other. Maybe the same can be achieved by programmatically setting these random data and re-using in other places.

**Comment by drod3763** [comment]
Thanks for the quick response @shamasis. I think if the documentation is made to make it easier to use in scripts (resolving Point 2), we can resolve Point 3 on our own allowing us to reuse the relevant items in different places.

**Comment by vdespa** [comment]
I have looked over the entire list and documented here my findings:
https://postman-quick-reference-guide.readthedocs.io/en/latest/dynamic-variables.html 

Let me know if I should create any issues.

**Comment by shamasis** [comment]
@vdespa the doc itself is a huge effort. I will create all the relevant issue needed around this and push changes to canary asap.

**Comment by dnordahl1** [comment]
Any way to get {{$randomJavaWebToken}} ?

**Comment by nathanbAL** [comment]
Possible to have a variation of {{$randomZipCode}} that returns a 5 digit postalCode?

**Comment by codenirvana** [comment]
Hello Everyone 👋
We've made certain improvements in dynamic variables in the latest Postman app.

- The final list of dynamic variables is available here: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#dynamic-variables

- Added autocomplete and description for every dynamic variable.
<img width="741" alt="Screenshot 2019-09-17 at 4 12 02 PM" src="https://user-images.githubusercontent.com/4865836/65035065-f19c7e00-d965-11e9-8a57-f814e25133bc.png">

- New variable substitution API (*pm.variables.replaceIn*) to generate dynamic variables via scripts. Refer: https://github.com/postmanlabs/postman-app-support/issues/2922#issuecomment-527101679

> Note: The final list may differ from one listed above https://github.com/postmanlabs/postman-app-support/issues/971#issuecomment-501433055.

For issues and improvements, feel free to open a new feature request or bug report.

Thanks for everyone’s feedback!

**Comment by pookdeveloper** [comment]
> Hello Everyone 👋
> We've made certain improvements in dynamic variables in the latest Postman app.
> 
> * The final list of dynamic variables is available here: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#dynamic-variables
> * Added autocomplete and description for every dynamic variable.
> 
> <img alt="Screenshot 2019-09-17 at 4 12 02 PM" width="741" src="https://user-images.githubusercontent.com/4865836/65035065-f19c7e00-d965-11e9-8a57-f814e25133bc.png">
> 
> * New variable substitution API (_pm.variables.replaceIn_) to generate dynamic variables via scripts. Refer: [#2922 (comment)](https://github.com/postmanlabs/postman-app-support/issues/2922#issuecomment-527101679)
> 
> > Note: The final list may differ from one listed above [#971 (comment)](https://github.com/postmanlabs/postman-app-support/issues/971#issuecomment-501433055).
> 
> For issues and improvements, feel free to open a new feature request or bug report.
> 
> Thanks for everyone’s feedback!

In the body dosen't autocompleted

Thanks

**Comment by codenirvana** [comment]
@pookdeveloper We are tracking the "autocomplete in the request body" feature request here: #5290

**Comment by pookdeveloper** [comment]
> @pookdeveloper We are tracking the "autocomplete in the request body" feature request here: #5290

Thanksss

**Comment by SezarRasoul** [comment]
randomEmail is using existing email adresses. This is not ok.
It generate @hotmail.com, @yahoo.com and so on. Why not only generate @example.com?

**Comment by vdespa** [comment]
@SezarRasoul I agree with you that this is not optimal. You need to understand that this implementation is relying on the Faker library. 

I think you need to accept that the data-set presented does have limitations and I can assure you that email addresses are not the only ones.

You can relatively easy use other strings and append them to @examle.com so that they match your current needs.

**Comment by SezarRasoul** [comment]
@vdespa  Thank you for your attention to this matter.
I found that you can use {{$randomFirstName}}@example.com instead :-)

**Comment by arnaudjolly** [comment]
Hi there!
Is it possible to make this random generator (faker) accessible from the Pre-request Script ?
Sometimes you just want to put cohesion between different fields in body (like a userName and an email).
Actually it is not possible to do this by using separate `{{$randomXXX}}` from the Body itself.
Allowing us to use the faker module from the PreRequest Script makes it possible.

**Comment by vdespa** [comment]
Hi @arnaudjolly 

Actually it is now possible to do this in the pre-request script using the relatively new pm.variables.replaceIn.
 
Here is a simple example to get you started:

`console.log(pm.variables.replaceIn('{{$randomFirstName}}'));`

**Comment by arnaudjolly** [comment]
Hi @vdespa 

Thanks for the tip, as I can see, this triggers a value generation for the variable. I can use it like that.
```
var firstName = pm.variables.replaceIn('{{$randomFirstName}}');
var relatedData = generateDataRelatedTo(firstName);

pm.environment.set("name", firstName);
pm.environment.set("data", relatedData);
```
to then reference it in a body with `{{name}}` and `{{data}}`. 
:+1:

**Comment by schillc** [comment]
Could you please add faker to the sandbox built-in library modules?

In addition to dynamic variables, users would be able to make use of all faker features within pre-request scripts.

```
var faker = require('faker');

var randomEmail = faker.internet.email();
...
let gender = ['Male', 'Female', 'Unknown'];
console.log(gender[faker.random.number % gender.length]);
```

**Comment by anaetrezve** [comment]
+1

**Comment by pedroreys** [comment]
I second the request about adding faker to sandbox libraries.

For example, right now I want to use `faker.date.recent` but pass a specific argument of numbers of days.

**Comment by adityaLath18** [comment]
Can we have a data driven feature in Postman, something like, we provide our request template and ask postman to generate random data based on it and can use some in-memory data to store it. Now my CRUD mock API can retrieve those data and then update or add those data? Is this in your roadmap any soon or any beta app.
Basically my requirement is to have some data driven mocking server, which can add, update, get, getAll, delete data (either in-memory or from some other data source).
