### ISSUE TITLE
payload's content-type cannot be set

### ISSUE THREAD

**Issue by muatik** [postmanlabs/postman-app-support#972]
when I try to send raw payload and select json type, it sends the request as "text/plain;charset=UTF-8".

**Comment by abhijitkane** [comment]
What version of Postman are you using?

Selecting JSON from the list just sets the Content-Type header to "application/json". If the header is modified after that, it's not reset to application/json.

**Comment by muatik** [comment]
it seems I was using the old version. I upgraded. Thanks.
