### ISSUE TITLE
Hash char ('#') not encoded while used as URL param from an environment variable

### ISSUE THREAD

**Issue by iurii-cartev-wellogic** [postmanlabs/postman-app-support#973]
Hello, dear Postman supporters!

Today I have encountered an interesting issue. I have an API of creating an entity with name. My test script saves name of this newly created entity to an environment variable. But when I use this variable for the next API call, like "/entity/{{saved_name}}", only characters before the hash char are passed as variable contents. I.e. '#' is not encoded when used as part of URL. Interesting thing is that space IS encoded, see example from below.

Example:
1. Create an entity with name "Entity #777" and save its name to variable "saved_name"
2. Call "/entity/{{saved_name}}", get 404 in response, because entity name came as "Entity " (original call was ""/entity/Entity%20")

I am using

```
Version 2.0.6 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64
```

Thank you in advance for looking into this!

**Comment by abhijitkane** [comment]
The URL is passed as-is to Chrome's XHR object. The XHR object trims everything after the space, and encodes the space as %20.

You can include this line in your pre-request script to encode the environment variable before the request is sent:
```postman.setEnvironmentVariable("saved_name",encodeURIComponent(environment["saved_name"]));```

**Comment by taquanghoang** [comment]
You can change character '#' by Code ASCII  '%23'
You can send request by postman

**Comment by asgaines** [comment]
This bit my team today as well. I would expect Postman to take the full value within the param field and URL encode it, not splitting on the `#`.

I would guess this is being done as a way of handling the url anchor/fragment which comes after `#` in a standard URL, but it creates unexpected behavior and forces a cumbersome and error-prone manual handling of the issue, as either of the two issues suggested here. I'd expect Postman to have another way of providing these anchor/fragment values

**Comment by sgehrman** [comment]
Had this problem today.  This should be fixed as we are using Postman for API docs and we can't properly document all our endpoints.

**Comment by henriquemattos** [comment]
Had to parse not only the hash (#) sign but also the percentage (%) sign. Clearly I don't have a web-friendly variable to be passing, but I think this should be encoded by default, or?

**Comment by parkerroan** [comment]
Also ran into this issue, url encoding would be a nice addition
