### ISSUE TITLE
Feature Request: Shortcut to switch between environments

### ISSUE THREAD

**Issue by juanpaulo** [postmanlabs/postman-app-support#974]
Not sure if this will make a lot of people happy but the ability to switch between environments (prior to sending a request) through a shortcut would be really nice to have.
Since environments are defined by users, prev/next switch is what I have in mind. Would appreciate other ideas as well. Thanks!

Indirectly related issue: #279

**Comment by dougrchamberlain** [comment]
This really should be something to be considered, I spend a good amount of time changing context, and needing to click through 4 or so screens feels tedious.  It would be nice if clicking the 'eye' which shows the environment info could be edited directly there.

**Comment by adis-io** [comment]
+1

Needed shortcut to focus selectbox with environments

**Comment by jamatsui** [comment]
+1

**Comment by jaydipsensussoft** [comment]
+1

**Comment by tonythere** [comment]
+1

**Comment by wszk1992** [comment]
Kindly ping

**Comment by matchilling** [comment]
👍

**Comment by goldlil** [comment]
this one is must have, I can't believe that this simple shortcut takes years to implement

**Comment by berkalparslan** [comment]
+1

need this super easy feature

**Comment by PovilasAtPoq** [comment]
We are in 2022 (7 years later) and we still need this. Should be enough of an indication to implement it :)

**Comment by sanjaykumarb** [comment]
+1
This would be really helpful

**Comment by nicolabeghin** [comment]
+1

**Comment by armudgal** [comment]
Any update on this, a response from the team would be really helpful for the community. @vinitshahdeo

**Comment by vnosach-clgx** [comment]
+1

**Comment by chris-torruella** [comment]
Hi @juanpaulo and everyone. I'm glad to share with you that following on your request we have released the Environments shortcut as part of the latest 10.13.0v of Postman. It will be available to all users in the next few days. The default shortcut combination (which now you can customize anytime) is:
Mac: ⌥E
Windows: Alt + E

Hope you find it helpful. Thanks for your patience!

**Comment by sanjaykumarb** [comment]
@chris-torruella - I'm using postman 10.15.0 in Mac. Shortcut `Option + E´ to switch environments is not working. It is also not visible in shortcuts tab.

Should this be enabled somewhere? Or should the current focus on window be expected to be a specific place?

**Comment by chris-torruella** [comment]
Hi @sanjaykumarb 
I've been checking and this seems to work consistently in our team
Some possibilities that come to mind to our engineers are:
1. There are some existing customization that's conflicting with the shortcut (you mentioned you can't see it in Settings/Shortcuts/ under the Interface section right?).
2. You are in an older version (this seems to not be the case, but could you check it out once again to discard this?).
3. You are using a different keyboard layout of some kind.

Can you double check and come back to me?

<img width="698" alt="Screenshot 2023-06-21 at 12 37 45" src="https://github.com/postmanlabs/postman-app-support/assets/120389184/6a86959b-99e9-4aa5-b9b9-4db9744ebf0d">

**Comment by sanjaykumarb** [comment]
@chris-torruella - `Environment Selector` is not visible for me in the shortcuts. Attaching the respective screenshots. I'm using the default Mac keyboard layout.

<img width="823" alt="Screenshot 2023-06-21 at 16 43 26" src="https://github.com/postmanlabs/postman-app-support/assets/47520295/fac24bb7-49ec-43f9-94b7-e754d90be42a">

<img width="842" alt="Screenshot 2023-06-21 at 16 41 49" src="https://github.com/postmanlabs/postman-app-support/assets/47520295/3ae6d4ac-00f9-4e24-b033-a3f9661fad93">

**Comment by chris-torruella** [comment]
@sanjaykumarb Are you signed in? Checking as this is not available for signed out users

**Comment by sanjaykumarb** [comment]
@chris-torruella - I'm not signed-in. I didn't know that i have to sign in to use this feature. I'm using postman on my office laptop and we are not allowed to sign-in.
Do you know if there are any plans to make it available for not signed-in users too?

**Comment by chris-torruella** [comment]
Sorry @sanjaykumarb but not at the moment.
But I will let you know if this ever changed.
Thanks
