### ISSUE TITLE
When connecting to proxy, Postman Crashes Chrome (entirely)

### ISSUE THREAD

**Issue by naterkane** [postmanlabs/postman-app-support#975]
This is not happening with Canary, only the Chrome App running on Version 42.0.2311.50 beta (64-bit)

![postman](https://cloud.githubusercontent.com/assets/21930/6810363/850e1ee6-d236-11e4-8bcf-28bf06982911.png)

**Comment by kayvannj** [comment]
same here

**Comment by pidries** [comment]
The issue relies in the port you are connecting with. 

The port configured in PostmanProxy is the one that is used to host the proxy. You cannot use this port for communicating with the backend of the proxy.

Use port 5005 instead, it should work.

**Comment by SirBraneDamuj** [comment]
@pidries Gave this a try, Chrome crashes immediately.

**Comment by pidries** [comment]
Did you use the default port 5005?

Postman only crashes Chrome when you use the proxy-port (eg. 8080) instead of port 5005.
