### ISSUE TITLE
No cookies when using Accept-Language: en-US,en;q=0.8,es;q=0.6

### ISSUE THREAD

**Issue by caballerofelipe** [postmanlabs/postman-app-support#976]
I have made a request using the header
Accept-Language: en-US,en;q=0.8,es;q=0.6
Obtained from Interceptor and when I do no cookies get set (I know because I'm printing headers in my server). But when I turn off this header everything works as expected.

**Comment by abhijitkane** [comment]
@locoloop I didn't understand fully - are you seeing different results just by adding/removing the header (keeping the interceptor on in both cases)?

What are the headers received by the server in both cases?

**Comment by locoloop** [comment]
Yes, I see different results but I'm not removing the header, I'm just turning it off. Interceptor is on in both cases.

These are my results (print_r in PHP). Without the header on:
```bash
Array
(
    [Host] => localhost
    [Connection] => keep-alive
    [Content-Length] => 2391
    [Origin] => http://localhost
    [User-Agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
    [Content-Type] => application/x-www-form-urlencoded
    [Accept] => */*
    [X-Requested-With] => XMLHttpRequest
    [Postman-Token] => 9cb5e8fd-75d2-4c55-2af0-2820099086ea
    [Accept-Encoding] => gzip, deflate
    [Cookie] => _pk_id.1.1fff=b2bbdb87aa7d13f2.1406063320.1.1406063320.1406063320.; PHPSESSID=b1c8f86d731ba1e92d2eb1b0d46ec5a4; _pk_id.1.1fff=b2bbdb87aa7d13f2.1406063320.1.1406063320.1406063320.; PHPSESSID=e83cfb1122bd160d7e6392ae822e1799
    [Referer] => http://localhost/{MY APP}/
)
```

With the header on:
```bash
Array
(
    [Host] => localhost
    [Connection] => keep-alive
    [Content-Length] => 2391
    [Origin] => http://localhost
    [User-Agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
    [Content-Type] => application/x-www-form-urlencoded
    [Accept] => */*
    [X-Requested-With] => XMLHttpRequest
    [Postman-Token] => 4c5120d0-0e5f-2fd9-e932-eca50d0d6ab1
    [Accept-Encoding] => gzip, deflate
    [Referer] => http://localhost/{MY APP}/
)
```

**Comment by abhijitkane** [comment]
Can you try sending the same request to this url:
http://dump.getpostman.com/get  (or /post, /put - depends on the HTTP method you're using)
This service will echo your request headers in the response body. (Note that you'll need to visit the site in your browser for a cookie to be set)
For me, the Accept-Language header is showing up when it's enabled, and the Cookie header is being sent in both cases.

What versions of Postman and the interceptor are you using? The latest versions are 2.0.11 and 0.2.9 respectively.

**Comment by hekailiang** [comment]
I have the same issue. When interceptor is enabled, and POST request header contains "Accept-Language:zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4", the "Cookie:{{my-cookies}}" will not be attached to the request. (Disable "Accept-Language" then everything works fine.)

Postman:  4.1.3
Postman Interceptor: 0.2.18

**Comment by abhijitkane** [comment]
@hekailiang We've made a number of updates to the app and the interceptor. Feel free to reopen if you're still seeing this.
