### ISSUE TITLE
How to set timeout in newman

### ISSUE THREAD

**Issue by youranwj** [postmanlabs/postman-app-support#977]
I got an ETIMEDOUT error of my request when run it with newman command, is there any way to set timeout in command line mode?

**Comment by abhijitkane** [comment]
There's no option right now. The current timeout is 15 seconds. We'll add a command-line option in a future release.

**Comment by digital-abyss** [comment]
I made a pull request implementing this feature:
https://github.com/a85/Newman/pull/203
Let me know your thoughts :)

**Comment by amandabouman** [comment]
+1 Need this ability.

**Comment by vishbin** [comment]
+1 This will be helpful

**Comment by abhijitkane** [comment]
v1.2.17 of Newman has the -r option
Thanks @digital-abyss!
