### ISSUE TITLE
Trim whitespace around request url

### ISSUE THREAD

**Issue by brabeji** [postmanlabs/postman-app-support#981]
Today I accidentally pasted url with space before scheme and then struggled like for an hour :( It would be really nice to have this whitespace trimmed or higlighted. I understand that it is inapropriate to programmaticaly change user input when you essentially want to assemble raw request and you know what you are doing - hence the highlight alternative.

Thanks

**Comment by abhijitkane** [comment]
Hm...according to the spec, URLs cannot include non-encoded spaces. We'll find a way to notify the user of leading/trailing spaces soon.

**Comment by a85** [comment]
This can be quite tricky so we'll take a pass on this. Whenever we change user input, this causes tests to break.

**Comment by jyoti-c** [comment]
Hey!  Anything on this? Are we adding this improvement?
